import Link from 'next/link';
import { ArrowRight, BarChart3, Bot, ChartNoAxesCombined, CircleDollarSign, Gauge, Layers3, Server, ShieldAlert, Waypoints } from 'lucide-react';
import CustomerMenu from '../../components/CustomerMenu';

const services = [
  ['Social Trading', 'Choose a trading platform first, then select the broker through which Arcus currently offers trade replication.', '/services/social-trading', '01', BarChart3],
  ['Crypto Copy Trading', 'Follow supported crypto strategies through selected exchange environments, with your capital remaining on your exchange account.', '/services/crypto-copy-trading', '02', CircleDollarSign],
  ['MAM Trading', 'A structured multi-account management environment for customers seeking professionally managed trading.', '/services/mam-trading', '03', Layers3],
  ['ServerLess Algotrading', 'Automated execution infrastructure designed to operate without requiring you to maintain a local trading workstation.', '/services/serverless-algotrading', '04', Server],
  ['TradingView Indicator', 'TradingView-based technical analysis technology designed for structured market decision support.', '/services/tradingview-indicator', '05', ChartNoAxesCombined],
  ['TradingView Strategy', 'Strategy automation workflows built around TradingView alerts and supported execution integrations.', '/services/tradingview-strategy', '06', Waypoints],
  ['TradingView Bridge', 'Connect TradingView webhook events with supported automated execution workflows.', '/services/tradingview-bridge', '07', Bot],
  ['Retail Tradar', 'Retail-focused trading technology for systematic execution, automation and structured workflows.', '/services/retail-tradar', '08', BarChart3],
  ['Prop Firm A.T', 'This service is currently unavailable while Arcus completes the required licensing and operational readiness.', '/coming-soon?service=Prop%20Firm%20A.T', '09', Gauge],
  ['Trading Signals', 'This service is currently unavailable while Arcus completes the required licensing and operational readiness.', '/coming-soon?service=Trading%20Signals', '10', ShieldAlert],
];

export default function ServicesPage() {
  return (
    <main className="min-h-screen bg-[#f7f9f8] text-[#101512]">
      <header className="sticky top-0 z-40 border-b border-[#e4e9e6] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex min-h-[76px] max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/dashboard" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#087f3f] text-sm font-black text-white">A</span><span><strong className="block text-[15px] tracking-[.16em]">ARCUS</strong><small className="block text-[8px] font-black tracking-[.35em] text-[#087f3f]">STRATEGY</small></span></Link><CustomerMenu /></div></header>

      <section className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-10 lg:py-16"><div className="max-w-4xl"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">SERVICES HUB</span><h1 className="mt-3 text-4xl font-black tracking-[-.045em] sm:text-5xl">Select the Arcus service that matches your trading objective.</h1><p className="mt-5 max-w-3xl text-[15px] leading-7 text-[#68726e]">Arcus services are presented as independent workflows. For copy trading, you first select the platform you use and then select an available broker. This lets you review broker-specific information, performance and onboarding instructions before starting.</p></div><div className="mt-7 flex flex-wrap gap-2 text-[10px] font-bold text-[#59645f]"><span className="rounded-full border border-[#dce6e0] bg-[#f6faf7] px-3 py-2">Broker-specific copy trading</span><span className="rounded-full border border-[#dce6e0] bg-[#f6faf7] px-3 py-2">Algorithmic execution</span><span className="rounded-full border border-[#dce6e0] bg-[#f6faf7] px-3 py-2">Risk-aware controls</span><span className="rounded-full border border-[#eadcdc] bg-[#fff8f8] px-3 py-2 text-[#a52b36]">Some services unavailable</span></div></div></section>

      <section className="mx-auto max-w-[1440px] px-5 py-10 sm:px-8 lg:px-10 lg:py-14"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{services.map(([title, description, href, number, Icon]) => { const comingSoon = title === 'Prop Firm A.T' || title === 'Trading Signals'; return <Link key={title} href={href} className="group flex min-h-[270px] flex-col rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-[#add8bd] hover:shadow-xl"><div className="flex items-center justify-between"><span className="text-[9px] font-black tracking-[.18em] text-[#9aa39f]">SERVICE {number}</span><span className={`grid h-10 w-10 place-items-center rounded-xl ${comingSoon ? 'bg-[#fff1f2] text-[#c93642]' : 'bg-[#edf8f1] text-[#087f3f]'}`}><Icon size={18} /></span></div><div className="mt-9 flex items-start justify-between gap-4"><h2 className="text-xl font-black tracking-tight">{title}</h2>{comingSoon && <span className="shrink-0 rounded-full bg-[#fff1f2] px-2.5 py-1 text-[8px] font-black uppercase tracking-wider text-[#c93642]">Coming Soon</span>}</div><p className="mt-3 text-[13px] leading-6 text-[#68726e]">{description}</p><span className={`mt-auto flex items-center gap-1 pt-7 text-[12px] font-extrabold ${comingSoon ? 'text-[#c93642]' : 'text-[#087f3f]'}`}>{comingSoon ? 'View availability' : 'Explore service'} <ArrowRight size={15} className="transition group-hover:translate-x-1" /></span></Link>})}</div></section>

      <section className="border-t border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1440px] px-5 py-10 sm:px-8 lg:px-10"><div className="grid gap-5 md:grid-cols-3"><div><span className="text-[9px] font-black tracking-[.18em] text-[#087f3f]">01</span><h3 className="mt-2 text-sm font-extrabold">Choose the environment</h3><p className="mt-1 text-[11px] leading-5 text-[#68726e]">For copy trading, select the platform and then the broker available to you.</p></div><div><span className="text-[9px] font-black tracking-[.18em] text-[#087f3f]">02</span><h3 className="mt-2 text-sm font-extrabold">Review the service</h3><p className="mt-1 text-[11px] leading-5 text-[#68726e]">Read the service information, limitations, performance information and applicable risks.</p></div><div><span className="text-[9px] font-black tracking-[.18em] text-[#087f3f]">03</span><h3 className="mt-2 text-sm font-extrabold">Start when eligible</h3><p className="mt-1 text-[11px] leading-5 text-[#68726e]">Follow the service-specific onboarding process. Unavailable services remain locked until Arcus opens them.</p></div></div></div></section>
    </main>
  );
}
