'use client';

import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { Activity, AlertTriangle, BarChart3, Bell, BriefcaseBusiness, ChevronRight, CircleDollarSign, Gauge, LineChart, ShieldCheck, TrendingDown, TrendingUp } from 'lucide-react';

const cards = [
  ['Total AUM', '$XX,XXX,XXX', 'Across monitored accounts', CircleDollarSign],
  ['Average Drawdown', 'X.XX%', 'Portfolio average', TrendingDown],
  ['Active Accounts', 'XXX', 'MT4 · MT5 · cTrader · Synthetic', BriefcaseBusiness],
  ['Average Monthly Return', 'X.XX%', 'Current reporting period', TrendingUp],
];
const performance = [['Equity', '$XX,XXX,XXX'], ['Balance', '$XX,XXX,XXX'], ['Profit Factor', 'X.XX'], ['Win Rate', 'XX.XX%'], ['Recovery Factor', 'X.XX'], ['Sharpe Ratio', 'X.XX'], ['Sortino Ratio', 'X.XX'], ['Exposure', 'XX.XX%']];
const brokers = [['MT4', 'XX accounts', 'X.XX%'], ['MT5', 'XX accounts', 'X.XX%'], ['cTrader', 'XX accounts', 'X.XX%'], ['Synthetic / Deriv', 'XX accounts', 'X.XX%']];
const services = [['Copy Trading', 'XX.XX%'], ['MAM', 'XX.XX%'], ['PAMM', 'XX.XX%'], ['Other services', 'XX.XX%']];

function Chart({ type }: { type: 'equity' | 'drawdown' }) {
  const bars = type === 'equity' ? [32,38,35,46,44,58,55,66,62,74,70,82,78,91] : [20,28,22,36,30,45,39,52,44,34,40,29,32,24];
  return <div className="mt-4 flex h-52 items-end gap-1 border-b border-l border-[#e2e8e4] px-3">{bars.map((v,i)=><div key={i} className={`flex-1 rounded-t-sm ${type==='equity'?'bg-[#087f3f]/75':'bg-[#b54747]/65'}`} style={{height:`${v}%`}} />)}</div>;
}

export default function FinancialAnalystDashboard() {
  const params = useSearchParams();
  const role = params.get('role') || 'financial_analyst';
  return <main className="min-h-screen bg-[#f5f7f6] text-[#101512]">
    <header className="sticky top-0 z-20 border-b border-[#dfe6e2] bg-white/95 backdrop-blur"><div className="flex min-h-[76px] items-center justify-between px-5 sm:px-8 xl:px-10"><div><p className="text-[8px] font-black uppercase tracking-[.22em] text-[#087f3f]">Arcus Analytics · Internal</p><h1 className="mt-1 text-xl font-black tracking-[-.025em]">Financial Analyst Dashboard</h1></div><div className="flex items-center gap-2"><span className="hidden rounded-full border border-[#dfe6e2] bg-[#f7f9f8] px-3 py-2 text-[9px] font-black uppercase tracking-[.1em] text-[#5e6964] sm:inline-flex">Analysis workspace</span><button className="grid h-9 w-9 place-items-center rounded-xl border border-[#dfe6e2] bg-white"><Bell size={15}/></button></div></div></header>
    <section className="px-5 pb-3 pt-7 sm:px-8 xl:px-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[9px] font-black uppercase tracking-[.17em] text-[#7b8580]">Portfolio intelligence</p><h2 className="mt-1 text-2xl font-black tracking-[-.035em]">Performance & risk source of truth</h2><p className="mt-1 max-w-3xl text-[11px] text-[#707a75]">Analyze trading performance, risk, broker accounts, Myfxbook verification and financial reporting used by Arcus customer-facing statistics.</p></div><div className="flex gap-2"><Link href={`/admin/analytics/reports?role=${role}`} className="inline-flex items-center gap-2 rounded-xl border border-[#cfd9d3] bg-white px-4 py-2.5 text-[10px] font-black">Reports <ChevronRight size={13}/></Link><Link href={`/admin/analytics/alerts?role=${role}`} className="inline-flex items-center gap-2 rounded-xl bg-[#087f3f] px-4 py-2.5 text-[10px] font-black text-white">Alerts <ChevronRight size={13}/></Link></div></div></section>
    <section className="grid gap-3 px-5 py-4 sm:grid-cols-2 xl:grid-cols-4 xl:px-10">{cards.map(([label,value,note,Icon])=><div key={label as string} className="rounded-2xl border border-[#dfe6e2] bg-white p-5 shadow-[0_1px_2px_rgba(16,24,20,.03)]"><div className="flex justify-between"><span className="text-[9px] font-black uppercase tracking-[.12em] text-[#7b8580]">{label as string}</span><Icon size={17} className="text-[#087f3f]"/></div><strong className="mt-3 block text-2xl font-black tracking-[-.04em]">{value as string}</strong><span className="mt-1 block text-[9px] text-[#7b8580]">{note as string}</span></div>)}</section>
    <section className="grid gap-5 px-5 py-4 sm:px-8 xl:grid-cols-[1.5fr_.75fr] xl:px-10"><div className="rounded-2xl border border-[#dfe6e2] bg-white p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[8px] font-black uppercase tracking-[.18em] text-[#087f3f]">Trading performance</p><h3 className="mt-1 text-base font-black">Equity curve</h3></div><select className="rounded-lg border border-[#dfe6e2] bg-white px-3 py-2 text-[9px] font-bold"><option>Last 12 months</option><option>Last 30 days</option><option>Last 7 days</option></select></div><Chart type="equity"/><div className="mt-3 grid grid-cols-4 gap-3">{performance.slice(0,4).map(([a,b])=><div key={a} className="rounded-xl bg-[#f6f8f7] p-3"><span className="text-[8px] font-black uppercase text-[#7b8580]">{a}</span><strong className="mt-1 block text-sm font-black">{b}</strong></div>)}</div></div><div className="rounded-2xl border border-[#dfe6e2] bg-white p-6"><p className="text-[8px] font-black uppercase tracking-[.18em] text-[#b54747]">Capital risk</p><h3 className="mt-1 text-base font-black">Drawdown chart</h3><Chart type="drawdown"/><div className="mt-4 grid grid-cols-2 gap-3">{[['Max Drawdown','X.XX%'],['Current Drawdown','X.XX%'],['Worst Loss','X.XX%'],['Risk Score','XX/100']].map(([a,b])=><div key={a} className="rounded-xl border border-[#eadede] bg-[#fffafa] p-3"><span className="text-[8px] font-black uppercase text-[#8a7373]">{a}</span><strong className="mt-1 block text-sm font-black">{b}</strong></div>)}</div></div></section>
    <section className="grid gap-5 px-5 py-4 sm:px-8 xl:grid-cols-3 xl:px-10"><div className="rounded-2xl border border-[#dfe6e2] bg-white p-6"><div className="flex items-center gap-2"><Gauge size={16} className="text-[#087f3f]"/><h3 className="text-base font-black">Performance comparison</h3></div><div className="mt-4 space-y-2.5">{performance.map(([a,b])=><div key={a} className="flex items-center justify-between border-b border-[#eef1ef] py-2 text-[9px]"><span className="font-bold text-[#65706b]">{a}</span><strong>{b}</strong></div>)}</div></div><div className="rounded-2xl border border-[#dfe6e2] bg-white p-6"><div className="flex items-center gap-2"><BarChart3 size={16} className="text-[#087f3f]"/><h3 className="text-base font-black">Broker performance</h3></div><div className="mt-4 space-y-4">{brokers.map(([a,b,c])=><div key={a}><div className="flex justify-between text-[9px]"><span className="font-black">{a}</span><span className="text-[#7b8580]">{b}</span></div><div className="mt-1.5 h-2 rounded-full bg-[#edf1ef]"><div className="h-full rounded-full bg-[#087f3f]" style={{width:c}}/></div></div>)}</div></div><div className="rounded-2xl border border-[#dfe6e2] bg-white p-6"><div className="flex items-center gap-2"><Activity size={16} className="text-[#087f3f]"/><h3 className="text-base font-black">Service performance</h3></div><div className="mt-4 space-y-3">{services.map(([a,b])=><div key={a} className="flex items-center justify-between rounded-xl bg-[#f7f9f8] p-3 text-[9px]"><span className="font-bold">{a}</span><strong>{b}</strong></div>)}</div></div></section>
    <section className="grid gap-5 px-5 py-4 pb-10 sm:px-8 xl:grid-cols-[1.2fr_.8fr] xl:px-10"><div className="rounded-2xl border border-[#dfe6e2] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-[8px] font-black uppercase tracking-[.18em] text-[#087f3f]">Account intelligence</p><h3 className="mt-1 text-base font-black">Account alerts</h3></div><Link href={`/admin/analytics/alerts?role=${role}`} className="text-[9px] font-black text-[#087f3f]">View alerts</Link></div><div className="mt-4 grid gap-2 md:grid-cols-3">{[['Drawdown threshold','Accounts approaching configured threshold','Review'],['Data freshness','Performance feed requires review','Investigate'],['Myfxbook verification','Accounts pending verification','Verify']].map(([a,b,c])=><div key={a} className="rounded-xl border border-[#e4eae6] p-4"><strong className="block text-[10px]">{a}</strong><span className="mt-1 block text-[8px] leading-4 text-[#77817c]">{b}</span><button className="mt-3 text-[8px] font-black text-[#087f3f]">{c}</button></div>)}</div></div><div className="rounded-2xl border border-[#f0d7d7] bg-white p-6"><div className="flex items-center gap-2"><ShieldCheck size={16} className="text-[#087f3f]"/><h3 className="text-base font-black">Credential security boundary</h3></div><p className="mt-3 text-[10px] leading-5 text-[#69736e]">Financial Analysts receive broker, account, platform, performance, risk, equity, drawdown and exposure data. Plaintext investor or trading passwords are not part of the normal analyst workspace.</p><div className="mt-3 flex items-center gap-2 rounded-xl bg-[#fff6f6] p-3 text-[8px] font-bold text-[#8f4b4b]"><AlertTriangle size={13}/> Credential access, when ever required, must be separately authorized and audited.</div></div></section>
  </main>;
}
