import Link from 'next/link';
import { ArrowRight, BarChart3, ChartCandlestick, Layers3, WalletCards } from 'lucide-react';
import CustomerMenu from '../../../components/CustomerMenu';
import { mt4Brokers, mt5Brokers, pammBrokers, mamBrokers } from '../../../lib/broker-config';

const definitions: Record<string, { title: string; description: string; platforms: {name:string;slug:string;count:number;icon:typeof BarChart3}[] }> = {
  'copy-trading': { title: 'Copy Trading Performance', description: 'Select the execution environment. Broker-level performance remains isolated on the next layer.', platforms: [{name:'MT4',slug:'mt4',count:10,icon:ChartCandlestick},{name:'MT5',slug:'mt5',count:10,icon:BarChart3},{name:'Deriv Synthetic',slug:'synthetic',count:1,icon:WalletCards},{name:'cTrader',slug:'ctrader',count:1,icon:Layers3}] },
  pamm: { title: 'PAMM Performance', description: 'Choose MT4 or MT5, then select the exact PAMM broker environment.', platforms: [{name:'MT4',slug:'mt4',count:pammBrokers.length,icon:ChartCandlestick},{name:'MT5',slug:'mt5',count:pammBrokers.length,icon:BarChart3}] },
  mam: { title: 'MAM Performance', description: 'Choose MT4 or MT5, then select the exact MAM broker environment.', platforms: [{name:'MT4',slug:'mt4',count:mamBrokers.length,icon:ChartCandlestick},{name:'MT5',slug:'mt5',count:mamBrokers.length,icon:BarChart3}] },
};

export default async function PerformanceCategoryPage({params}:{params:Promise<{category:string}>}) { const {category}=await params; const data=definitions[category]; if(!data) return <main className="min-h-screen bg-[#f7f9f8] p-10"><Link href="/performance-statistics">← Performance Statistics</Link><h1 className="mt-10 text-3xl font-black">Dashboard unavailable</h1></main>; return <main className="min-h-screen bg-[#f7f9f8] text-[#101512]"><header className="sticky top-0 z-40 border-b border-[#e4e9e6] bg-white/95"><div className="mx-auto flex min-h-[76px] max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/performance-statistics" className="font-black text-[#087f3f]">← Performance Statistics</Link><CustomerMenu/></div></header><section className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1200px] px-5 py-12 sm:px-8 lg:px-10"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">PERFORMANCE / {category.toUpperCase()}</span><h1 className="mt-3 text-4xl font-black">{data.title}</h1><p className="mt-4 max-w-2xl text-[14px] leading-7 text-[#68726e]">{data.description}</p></div></section><section className="mx-auto max-w-[1200px] px-5 py-10 sm:px-8 lg:px-10"><div className="grid gap-4 md:grid-cols-2">{data.platforms.map(({name,slug,count,icon:Icon})=><Link key={slug} href={`/performance-statistics/${category}/${slug}`} className="group rounded-2xl border border-[#dfe7e2] bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="flex items-center justify-between"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#edf8f1] text-[#087f3f]"><Icon size={20}/></span><span className="text-[9px] font-black tracking-[.18em] text-[#9aa39f]">{count} ENVIRONMENT{count>1?'S':''}</span></div><h2 className="mt-7 text-2xl font-black">{name}</h2><p className="mt-2 text-[12px] leading-6 text-[#68726e]">Open the {name} performance dashboard and continue to broker-level isolation.</p><span className="mt-6 inline-flex items-center gap-2 text-[12px] font-extrabold text-[#087f3f]">Continue <ArrowRight size={15}/></span></Link>)}</div></section></main>; }
