import Link from 'next/link';
import { ArrowRight, CheckCircle2, CircleAlert, ShieldCheck } from 'lucide-react';
import CustomerMenu from '../../../../../components/CustomerMenu';

const brokers: Record<string, { name: string; platform: string; description: string; externalUrl: string }> = {
  'hantec-markets': { name: 'Hantec Markets', platform: 'MetaTrader 4', description: 'Arcus MT4 copy trading environment for customers who maintain their own Hantec Markets trading account.', externalUrl: 'https://hmarkets.com/' },
};

export function generateStaticParams() { return [{ broker: 'hantec-markets' }]; }

export default async function MT4BrokerPage({ params }: { params: Promise<{ broker: string }> }) {
  const { broker } = await params;
  const data = brokers[broker];
  if (!data) return <main className="min-h-screen bg-[#f7f9f8] p-10 text-[#101512]"><Link href="/services/social-trading/mt4" className="font-bold text-[#087f3f]">← Back to MT4 brokers</Link><h1 className="mt-10 text-3xl font-black">Broker unavailable</h1><p className="mt-3 text-[#68726e]">This broker environment has not been enabled in Arcus Strategy.</p></main>;

  return <main className="min-h-screen bg-[#f7f9f8] text-[#101512]">
    <header className="sticky top-0 z-40 border-b border-[#e4e9e6] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex min-h-[76px] max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/services/social-trading/mt4" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#087f3f] text-sm font-black text-white">A</span><span><strong className="block text-[15px] tracking-[.16em]">ARCUS</strong><small className="block text-[8px] font-black tracking-[.35em] text-[#087f3f]">STRATEGY</small></span></Link><CustomerMenu /></div></header>

    <section className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-12 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:px-10 lg:py-16"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.2em] text-[#087f3f]"><CheckCircle2 size={14}/> MT4 / BROKER ENVIRONMENT</div><h1 className="mt-4 text-4xl font-black tracking-[-.045em] sm:text-5xl">Arcus MT4 Copy Trading on {data.name}.</h1><p className="mt-5 max-w-2xl text-[15px] leading-7 text-[#68726e]">{data.description} Your trading account remains under your ownership and control. Arcus provides the strategy and replication workflow; the broker provides the trading account and execution environment.</p><div className="mt-7 flex flex-wrap gap-3"><a href={data.externalUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-[#087f3f] px-5 py-3 text-[12px] font-extrabold text-white hover:bg-[#066b35]">Visit {data.name} <ArrowRight size={15}/></a><a href="#onboarding" className="inline-flex items-center gap-2 rounded-lg border border-[#d7e0da] bg-white px-5 py-3 text-[12px] font-extrabold hover:border-[#087f3f] hover:text-[#087f3f]">How to start</a></div></div><div className="rounded-2xl border border-[#dfe7e2] bg-[#101714] p-6 text-white"><span className="text-[9px] font-black tracking-[.2em] text-[#65d995]">BROKER PROFILE</span><h2 className="mt-3 text-2xl font-black">{data.name}</h2><p className="mt-2 text-[12px] text-[#aab4ae]">{data.platform} environment</p><div className="my-6 h-px bg-white/10"/><div className="space-y-3"><div className="flex items-center gap-2 text-[12px]"><CheckCircle2 size={15} className="text-[#65d995]"/> Arcus strategy environment</div><div className="flex items-center gap-2 text-[12px]"><ShieldCheck size={15} className="text-[#65d995]"/> Customer retains broker account control</div><div className="flex items-center gap-2 text-[12px]"><CircleAlert size={15} className="text-[#f08b95]"/> Trading losses remain possible</div></div></div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-10 sm:px-8 lg:px-10 lg:py-14"><div className="grid gap-5 md:grid-cols-3"><div className="rounded-2xl border border-[#dfe7e2] bg-white p-6"><span className="text-[9px] font-black tracking-[.18em] text-[#087f3f]">01</span><h3 className="mt-4 text-lg font-black">Open your broker account</h3><p className="mt-2 text-[12px] leading-6 text-[#68726e]">Use the broker's own registration process and complete any identity or suitability checks it requires.</p></div><div className="rounded-2xl border border-[#dfe7e2] bg-white p-6"><span className="text-[9px] font-black tracking-[.18em] text-[#087f3f]">02</span><h3 className="mt-4 text-lg font-black">Set up MT4</h3><p className="mt-2 text-[12px] leading-6 text-[#68726e]">Install or access the broker's MT4 environment and ensure the account is ready for the supported replication workflow.</p></div><div id="onboarding" className="rounded-2xl border border-[#dfe7e2] bg-white p-6"><span className="text-[9px] font-black tracking-[.18em] text-[#087f3f]">03</span><h3 className="mt-4 text-lg font-black">Start Arcus replication</h3><p className="mt-2 text-[12px] leading-6 text-[#68726e]">Follow the Arcus onboarding instructions for this broker. Never provide Arcus with your broker password or request remote access to your device.</p></div></div></section>

    <section className="border-y border-[#e4e9e6] bg-white"><div className="mx-auto grid max-w-[1440px] gap-8 px-5 py-10 sm:px-8 lg:grid-cols-2 lg:px-10 lg:py-14"><div><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">PERFORMANCE</span><h2 className="mt-2 text-2xl font-black">Review the broker-specific results.</h2><p className="mt-3 text-[13px] leading-6 text-[#68726e]">Performance information should be reviewed for the exact platform and broker environment you intend to use. Results can differ because of execution, spread, slippage, account size and market conditions.</p><Link href="/performance-statistics" className="mt-5 inline-flex items-center gap-2 text-[12px] font-extrabold text-[#087f3f]">Open Performance Statistics <ArrowRight size={15}/></Link></div><div className="rounded-2xl bg-[#f7f9f8] p-6"><span className="text-[10px] font-black tracking-[.2em] text-[#c93642]">RISK NOTICE</span><p className="mt-3 text-[12px] leading-6 text-[#59645f]">Copy trading does not guarantee identical results. Slippage, spreads, latency, liquidity, sizing and broker execution can cause copied trades to differ from the source strategy. Past performance is not a guarantee of future results.</p><Link href="/risk-analysis" className="mt-5 inline-flex items-center gap-2 text-[12px] font-extrabold text-[#c93642]">Review Risk Analysis <ArrowRight size={15}/></Link></div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-10 sm:px-8 lg:px-10"><div className="rounded-2xl border border-[#dfe7e2] bg-white p-7"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">IMPORTANT</span><h2 className="mt-2 text-xl font-black">Arcus is not your broker.</h2><p className="mt-3 max-w-3xl text-[12px] leading-6 text-[#68726e]">Your broker account, deposits, withdrawals, execution and account-level terms remain governed by the broker. Arcus does not ask for your broker password, custody your trading capital or guarantee profits.</p></div></section>
  </main>;
}
