import Link from 'next/link';
import { ArrowLeft, Download, Plus, Search, ShieldCheck, SlidersHorizontal, MoreHorizontal, CheckCircle2, Clock3, AlertTriangle } from 'lucide-react';

type Row = { id: string; name: string; detail: string; status: string; value?: string };

const modules: Record<string, { title: string; subtitle: string; action?: string; tabs?: string[]; rows: Row[] }> = {
  'customers': { title: 'All Customers', subtitle: 'Search and manage customer profiles, verification, service access and account status.', action: 'Add customer', rows: [
    {id:'CUS-10024',name:'Customer 10024',detail:'customer10024@example.com',status:'Active',value:'3 services'}, {id:'CUS-10023',name:'Customer 10023',detail:'customer10023@example.com',status:'Active',value:'1 service'}, {id:'CUS-10022',name:'Customer 10022',detail:'customer10022@example.com',status:'KYC pending',value:'2 services'}, {id:'CUS-10021',name:'Customer 10021',detail:'customer10021@example.com',status:'Suspended',value:'0 services'}]},
  'customers/kyc': { title:'KYC & Compliance', subtitle:'Review identity verification queues, verification status and compliance exceptions.', action:'Review queue', tabs:['Pending','Approved','Rejected','Expired'], rows:[{id:'KYC-8821',name:'Customer 10022',detail:'Identity + address verification',status:'Pending'},{id:'KYC-8819',name:'Customer 10018',detail:'Enhanced due diligence',status:'Pending'},{id:'KYC-8817',name:'Customer 10015',detail:'Identity verification',status:'Approved'}]},
  'customers/suspended': {title:'Suspended Customers',subtitle:'Review suspended accounts, reasons, restrictions and reinstatement actions.',action:'Review cases',rows:[{id:'CUS-10021',name:'Customer 10021',detail:'Payment dispute review',status:'Suspended'},{id:'CUS-10004',name:'Customer 10004',detail:'Compliance restriction',status:'Suspended'}]},
  'customers/activity': {title:'Customer Activity',subtitle:'Operational view of sign-ins, security events, service changes and support history.',tabs:['All activity','Security','Services','Support'],rows:[{id:'ACT-9012',name:'Customer 10024',detail:'Successful sign-in · 08:42',status:'Security'},{id:'ACT-9011',name:'Customer 10022',detail:'KYC document submitted',status:'KYC'},{id:'ACT-9010',name:'Customer 10018',detail:'Copy Trading subscription renewed',status:'Subscription'}]},
  'services/copy-trading': {title:'Copy Trading',subtitle:'Manage Copy Trading service configuration, broker environments and account onboarding.',action:'Add broker environment',rows:[{id:'MT4',name:'MT4',detail:'10 broker environments',status:'Operational'},{id:'MT5',name:'MT5',detail:'10 broker environments',status:'Operational'},{id:'DERIV',name:'Synthetic / Deriv',detail:'1 broker environment',status:'Operational'},{id:'CTRADER',name:'cTrader',detail:'1 broker environment',status:'Operational'}]},
  'services/mam': {title:'MAM',subtitle:'Manage MAM service platforms, broker environments and account status.',action:'Add environment',rows:[{id:'MAM-MT4',name:'MT4 MAM',detail:'5 broker environments · $3,000 minimum',status:'Operational'},{id:'MAM-MT5',name:'MT5 MAM',detail:'5 broker environments · $3,000 minimum',status:'Operational'}]},
  'services/pamm': {title:'PAMM',subtitle:'Manage PAMM service platforms, broker environments and account status.',action:'Add environment',rows:[{id:'PAMM-MT4',name:'MT4 PAMM',detail:'5 broker environments · $3,000 minimum',status:'Operational'},{id:'PAMM-MT5',name:'MT5 PAMM',detail:'5 broker environments · $3,000 minimum',status:'Operational'}]},
  'services/serverless': {title:'ServerLess Algotrading',subtitle:'Manage subscriptions, onboarding queues, account connections and service status.',action:'Create service plan',tabs:['Plans','Subscribers','Onboarding','Service status'],rows:[{id:'SL-M',name:'Monthly',detail:'Subscription plan',status:'Active'},{id:'SL-Q',name:'Quarterly',detail:'Subscription plan',status:'Active'},{id:'SL-Y',name:'Yearly',detail:'Subscription plan',status:'Active'}]},
  'services/prop-firm-at': {title:'Prop Firm Assisted Trading',subtitle:'Manage prop firm services, KYC gates, subscriptions, challenges and onboarding.',action:'Create plan',tabs:['Plans','Accounts','KYC queue','Onboarding'],rows:[{id:'PFA-01',name:'Challenge accounts',detail:'KYC required before subscription',status:'Active'},{id:'PFA-02',name:'Funded accounts',detail:'KYC required before subscription',status:'Active'},{id:'PFA-03',name:'One-step / Two-step',detail:'Challenge workflow',status:'Active'}]},
  'services/tradingview': {title:'TradingView',subtitle:'Manage TradingView Indicator and Strategy products and supported automation integrations.',action:'Add integration',rows:[{id:'TV-IND',name:'TradingView Indicator',detail:'Product configuration',status:'Active'},{id:'TV-STR',name:'TradingView Strategy',detail:'Relay, Zignaly, Pine Bridge, WunderTrading, Cornix, 3Commas and webhook automation',status:'Active'}]},
  'trading/broker-accounts': {title:'Broker Accounts',subtitle:'Monitor connected trading accounts, broker environments and account service status.',action:'Add account',tabs:['All','MT4','MT5','cTrader','Synthetic'],rows:[{id:'BRK-2201',name:'MT5 · Broker environment',detail:'Customer 10024 · Copy Trading',status:'Connected'},{id:'BRK-2200',name:'MT4 · Broker environment',detail:'Customer 10023 · MAM',status:'Connected'},{id:'BRK-2199',name:'cTrader · Broker environment',detail:'Customer 10018 · Copy Trading',status:'Attention'}]},
  'trading/performance': {title:'Performance Statistics',subtitle:'Operational performance records for strategies, brokers and managed trading accounts.',action:'Refresh records',tabs:['All','Copy Trading','MAM','PAMM'],rows:[{id:'PERF-01',name:'Arcus Strategy · MT5',detail:'Performance record',status:'Connected'},{id:'PERF-02',name:'Arcus Strategy · MT4',detail:'Performance record',status:'Connected'},{id:'PERF-03',name:'MAM Portfolio',detail:'Performance record',status:'Connected'}]},
  'trading/risk': {title:'Risk Analysis',subtitle:'Monitor drawdown, exposure, risk rules and stress-test records.',action:'Run risk review',tabs:['Overview','Drawdown','Exposure','Stress tests'],rows:[{id:'RISK-01',name:'MT5 Copy Trading',detail:'Max drawdown · exposure · risk rules',status:'Low-moderate'},{id:'RISK-02',name:'MAM Portfolio',detail:'Portfolio risk profile',status:'Moderate'},{id:'RISK-03',name:'Prop Firm A.T',detail:'Daily loss and account drawdown limits',status:'Controlled'}]},
  'trading/investor-credentials': {title:'Investor Credentials',subtitle:'Controlled access to investor-password records. Sensitive values must never be exposed in ordinary analytics roles.',action:'Review access log',rows:[{id:'INV-01',name:'MT5 investor record',detail:'Customer 10024 · access controlled',status:'Protected'},{id:'INV-02',name:'MT4 investor record',detail:'Customer 10023 · access controlled',status:'Protected'}]},
  'trading/myfxbook': {title:'Myfxbook',subtitle:'Manage Myfxbook integrations and account-level dashboard connections.',action:'Add integration',rows:[{id:'MFX-01',name:'MT5 performance dashboard',detail:'Widget configuration',status:'Connected'},{id:'MFX-02',name:'MT4 performance dashboard',detail:'Widget configuration',status:'Pending'}]},
  'subscriptions/active': {title:'Active Subscriptions',subtitle:'Monitor active services, billing cycles, renewals and customer entitlements.',action:'Create subscription',rows:[{id:'SUB-5001',name:'Copy Trading · MT5',detail:'Customer 10024 · monthly',status:'Active',value:'Renews in 12 days'},{id:'SUB-5000',name:'MAM · MT4',detail:'Customer 10018 · annual',status:'Active',value:'Renews in 84 days'}]},
  'subscriptions/trials': {title:'Trial Accounts',subtitle:'Manage trial eligibility, expiry dates and conversion follow-up.',tabs:['Active trials','Expiring','Converted'],rows:[{id:'TR-101',name:'Customer 10022',detail:'14-day trial',status:'Active',value:'6 days left'},{id:'TR-102',name:'Customer 10019',detail:'14-day trial',status:'Expiring',value:'1 day left'}]},
  'subscriptions/expired': {title:'Expired Subscriptions',subtitle:'Review expired entitlements, renewal opportunities and service access.',rows:[{id:'SUB-4901',name:'Customer 10011',detail:'Copy Trading · MT4',status:'Expired'},{id:'SUB-4898',name:'Customer 10008',detail:'ServerLess',status:'Expired'}]},
  'subscriptions/cancelled': {title:'Cancelled Subscriptions',subtitle:'Review cancellations, reasons, effective dates and retention actions.',rows:[{id:'SUB-4881',name:'Customer 10005',detail:'PAMM · MT5',status:'Cancelled'},{id:'SUB-4879',name:'Customer 10003',detail:'TradingView Strategy',status:'Cancelled'}]},
  'finance/transactions': {title:'Transactions',subtitle:'Review payment transactions across Paystack, PayPal and crypto rails.',action:'Export transactions',tabs:['All','Paystack','PayPal','Crypto'],rows:[{id:'TX-90211',name:'Customer 10024',detail:'Subscription payment · Paystack',status:'Completed',value:'—'},{id:'TX-90210',name:'Customer 10023',detail:'Subscription payment · PayPal',status:'Completed',value:'—'},{id:'TX-90209',name:'Customer 10022',detail:'Subscription payment · Crypto',status:'Pending',value:'—'}]},
  'finance/revenue': {title:'Revenue',subtitle:'Revenue reporting by period, service and payment method.',action:'Export report',tabs:['7 days','30 days','12 months'],rows:[{id:'REV-01',name:'Copy Trading',detail:'Revenue category',status:'Reported'},{id:'REV-02',name:'MAM / PAMM',detail:'Revenue category',status:'Reported'},{id:'REV-03',name:'ServerLess / Prop Firm A.T',detail:'Revenue category',status:'Reported'}]},
  'finance/refunds': {title:'Refunds',subtitle:'Manage refund requests, approval workflow and payment reconciliation.',action:'Create refund case',rows:[{id:'REF-301',name:'Customer 10014',detail:'Subscription refund request',status:'Pending'},{id:'REF-299',name:'Customer 10009',detail:'Duplicate payment review',status:'Approved'}]},
  'finance/chargebacks': {title:'Chargebacks',subtitle:'Track payment disputes, evidence deadlines and resolution status.',action:'Open dispute case',rows:[{id:'CB-102',name:'Customer 10004',detail:'Card payment dispute',status:'Evidence due'},{id:'CB-099',name:'Customer 10002',detail:'Payment dispute',status:'Resolved'}]},
  'content/blog': {title:'Blog',subtitle:'Create, edit, schedule and publish public Arcus Strategy articles.',action:'New article',tabs:['All','Drafts','Scheduled','Published'],rows:[{id:'BLOG-12',name:'Understanding Algorithmic Trading',detail:'Public article',status:'Published'},{id:'BLOG-11',name:'Risk Management Essentials',detail:'Public article',status:'Draft'}]},
  'content/education': {title:'Education',subtitle:'Manage courses and learning content: articles, videos and documents.',action:'New course',rows:[{id:'COURSE-01',name:'Algorithmic Trading Fundamentals',detail:'Article · Video · Documents',status:'Published'},{id:'COURSE-02',name:'Risk Management',detail:'Article · Video · Documents',status:'Draft'}]},
  'content/faq': {title:'FAQ',subtitle:'Manage public frequently asked questions and publishing state.',action:'New FAQ',rows:[{id:'FAQ-01',name:'How does Copy Trading work?',detail:'Public FAQ',status:'Published'},{id:'FAQ-02',name:'How do I verify my account?',detail:'Public FAQ',status:'Published'}]},
  'content/announcements': {title:'Announcements',subtitle:'Create operational and customer-facing announcements.',action:'New announcement',rows:[{id:'ANN-01',name:'Scheduled maintenance',detail:'Customer notice',status:'Scheduled'},{id:'ANN-02',name:'New service availability',detail:'Customer notice',status:'Draft'}]},
  'support/tickets': {title:'Support Tickets',subtitle:'Customer support queue with ownership, priority, SLA and escalation controls.',action:'Create ticket',tabs:['Open','Assigned','Pending','Resolved'],rows:[{id:'TCK-771',name:'Customer 10024',detail:'Copy Trading onboarding · High priority',status:'Open'},{id:'TCK-770',name:'Customer 10022',detail:'KYC assistance · Normal',status:'Assigned'},{id:'TCK-769',name:'Customer 10018',detail:'Subscription question · Normal',status:'Pending'}]},
  'support/complaints': {title:'Complaints',subtitle:'Formal complaint intake, investigation, ownership and resolution tracking.',action:'Register complaint',rows:[{id:'CMP-31',name:'Customer 10017',detail:'Service complaint',status:'Investigating'},{id:'CMP-30',name:'Customer 10012',detail:'Billing complaint',status:'Resolved'}]},
  'support/escalations': {title:'Escalations',subtitle:'Cross-team escalations requiring compliance, finance, trading or management review.',action:'Create escalation',rows:[{id:'ESC-18',name:'KYC escalation',detail:'Compliance review required',status:'High'},{id:'ESC-17',name:'Payment escalation',detail:'Finance review required',status:'Medium'}]},
  'staff': {title:'Staff & Permissions',subtitle:'Create staff accounts, assign roles, manage permissions and suspend staff access.',action:'Add staff',rows:[{id:'STF-01',name:'Administrator',detail:'Full platform control',status:'Active'},{id:'STF-02',name:'Customer Support',detail:'Support operations',status:'Active'},{id:'STF-03',name:'Financial Analyst',detail:'Reporting access',status:'Active'},{id:'STF-04',name:'Copywriter',detail:'Content publishing',status:'Active'}]},
  'reports': {title:'Reports',subtitle:'Operational reporting across customers, services, trading, subscriptions, finance and support.',action:'Generate report',tabs:['Executive','Customers','Trading','Finance','Support'],rows:[{id:'RPT-01',name:'Executive operations report',detail:'Platform activity and service overview',status:'Ready'},{id:'RPT-02',name:'Trading performance report',detail:'Performance and risk',status:'Ready'},{id:'RPT-03',name:'Finance report',detail:'Transactions and revenue',status:'Ready'}]},
  'reports/financial': {title:'Financial Reports',subtitle:'Revenue, transactions, refunds and chargeback reporting for authorized financial staff.',action:'Generate report',rows:[{id:'FIN-01',name:'Revenue report',detail:'Period and service breakdown',status:'Ready'},{id:'FIN-02',name:'Payment reconciliation',detail:'Paystack · PayPal · Crypto',status:'Ready'}]},
  'audit-logs': {title:'Audit Logs',subtitle:'Immutable operational trail for privileged actions, access events and configuration changes.',action:'Export logs',tabs:['All','Authentication','Customers','Finance','Trading','Staff'],rows:[{id:'LOG-901',name:'Administrator',detail:'Updated service configuration',status:'Logged'},{id:'LOG-900',name:'Financial Analyst',detail:'Viewed financial report',status:'Logged'},{id:'LOG-899',name:'Customer Support',detail:'Updated ticket assignment',status:'Logged'}]},
  'settings': {title:'Settings',subtitle:'Platform administration settings, service configuration, notifications and security controls.',rows:[{id:'SET-01',name:'Platform configuration',detail:'Global operational settings',status:'Protected'},{id:'SET-02',name:'Notifications',detail:'Email and operational alerts',status:'Configured'},{id:'SET-03',name:'Security',detail:'Session, access and privileged-action controls',status:'Protected'}]},
};

function key(slug: string[]) { return slug.join('/'); }

export default async function AdminModulePage({ params }: { params: Promise<{ slug: string[] }> }) {
  const { slug } = await params;
  const module = modules[key(slug)] || modules.customers;
  const canBack = slug.length > 1;
  return <main className="min-h-screen bg-[#f7f9f8] px-5 py-7 text-[#101512] lg:px-8">
    <div className="mx-auto max-w-[1400px]">
      <div className="mb-6 flex flex-wrap items-center justify-between gap-4">
        <div>{canBack && <Link href={`/admin/${slug.slice(0,-1).join('/')}`} className="mb-3 inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.12em] text-[#6a756f]"><ArrowLeft size={13}/>Back</Link>}<div className="text-[9px] font-black uppercase tracking-[.2em] text-[#087f3f]">Arcus Strategy · Administration</div><h1 className="mt-1 text-[25px] font-black tracking-[-.03em]">{module.title}</h1><p className="mt-1 max-w-3xl text-[12px] leading-5 text-[#69746f]">{module.subtitle}</p></div>
        {module.action && <button className="inline-flex items-center gap-2 rounded-xl bg-[#087f3f] px-4 py-3 text-[11px] font-black text-white shadow-sm hover:bg-[#066c35]"><Plus size={15}/>{module.action}</button>}
      </div>
      {module.tabs && <div className="mb-4 flex flex-wrap gap-2">{module.tabs.map((tab,i)=><button key={tab} className={`rounded-lg border px-3 py-2 text-[10px] font-black ${i===0?'border-[#b9dcc7] bg-[#eaf7ef] text-[#087f3f]':'border-[#dfe6e2] bg-white text-[#66716c]'}`}>{tab}</button>)}</div>}
      <section className="overflow-hidden rounded-2xl border border-[#dfe6e2] bg-white shadow-[0_4px_18px_rgba(16,21,18,.04)]">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#e8eeeb] p-4"><div className="flex min-w-[240px] flex-1 items-center gap-2 rounded-xl border border-[#dfe6e2] bg-[#fafcfb] px-3 py-2.5"><Search size={15} className="text-[#84908a]"/><span className="text-[10px] text-[#8a948f]">Search records...</span></div><button className="inline-flex items-center gap-2 rounded-xl border border-[#dfe6e2] px-3 py-2.5 text-[10px] font-black text-[#5e6964]"><SlidersHorizontal size={14}/>Filters</button><button className="inline-flex items-center gap-2 rounded-xl border border-[#dfe6e2] px-3 py-2.5 text-[10px] font-black text-[#5e6964]"><Download size={14}/>Export</button></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#f8faf9]"><tr><th className="px-4 py-3 text-[8px] font-black uppercase tracking-[.15em] text-[#87918c]">Record</th><th className="px-4 py-3 text-[8px] font-black uppercase tracking-[.15em] text-[#87918c]">Details</th><th className="px-4 py-3 text-[8px] font-black uppercase tracking-[.15em] text-[#87918c]">Status</th><th className="px-4 py-3 text-[8px] font-black uppercase tracking-[.15em] text-[#87918c]">Value</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-[#edf1ef]">{module.rows.map(row=><tr key={row.id} className="hover:bg-[#fbfdfc]"><td className="px-4 py-4"><div className="text-[11px] font-black">{row.name}</div><div className="mt-1 text-[9px] font-bold text-[#9aa39f]">{row.id}</div></td><td className="px-4 py-4 text-[10px] text-[#66716c]">{row.detail}</td><td className="px-4 py-4"><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[9px] font-black ${row.status.toLowerCase().includes('pending')||row.status.toLowerCase().includes('attention')||row.status.toLowerCase().includes('due')?'bg-[#fff6df] text-[#966c00]':row.status.toLowerCase().includes('suspend')||row.status.toLowerCase().includes('high')?'bg-[#fff0ef] text-[#b43a32]':'bg-[#eaf7ef] text-[#087f3f]'}`}>{row.status.includes('Protected')?<ShieldCheck size={11}/>:row.status.includes('Pending')||row.status.includes('Expiring')?<Clock3 size={11}/>:row.status.includes('High')?<AlertTriangle size={11}/>:<CheckCircle2 size={11}/>} {row.status}</span></td><td className="px-4 py-4 text-[10px] font-bold text-[#59645f]">{row.value || '—'}</td><td className="px-4 py-4 text-right"><button aria-label="More actions" className="rounded-lg p-2 text-[#7b8681] hover:bg-[#f1f5f3]"><MoreHorizontal size={16}/></button></td></tr>)}</tbody></table></div>
      </section>
      <div className="mt-4 flex items-center gap-2 rounded-xl border border-[#dfe6e2] bg-white px-4 py-3 text-[9px] text-[#75807a]"><ShieldCheck size={13} className="text-[#087f3f]"/>Administrative actions are subject to role permissions and should be enforced server-side with Firebase custom claims before production.</div>
    </div>
  </main>;
}
