import Link from 'next/link';
import { ArrowLeft, Clock3, ShieldAlert } from 'lucide-react';
import CustomerMenu from '../../components/CustomerMenu';

export default async function ComingSoonPage({ searchParams }: { searchParams: Promise<{ service?: string }> }) {
  const params = await searchParams;
  const service = params.service || 'This service';
  return <main className="min-h-screen bg-[#f7f9f8] text-[#101512]"><header className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto flex min-h-[76px] max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/dashboard" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#087f3f] text-sm font-black text-white">A</span><span><strong className="block text-[15px] tracking-[.16em]">ARCUS</strong><small className="block text-[8px] font-black tracking-[.35em] text-[#087f3f]">STRATEGY</small></span></Link><CustomerMenu /></div></header><section className="mx-auto flex min-h-[calc(100vh-77px)] max-w-[1440px] items-center justify-center px-5 py-16 sm:px-8 lg:px-10"><div className="w-full max-w-2xl rounded-3xl border border-[#e0e6e2] bg-white p-8 text-center shadow-sm sm:p-12"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-[#fff1f2] text-[#c93642]"><Clock3 size={28}/></div><span className="mt-7 block text-[10px] font-black tracking-[.22em] text-[#c93642]">SERVICE COMING SOON</span><h1 className="mt-3 text-4xl font-black tracking-[-.04em]">{service}</h1><p className="mx-auto mt-5 max-w-xl text-[14px] leading-7 text-[#68726e]">This service is not currently open to customers. Arcus Strategy is completing the required licensing, compliance and operational readiness before making the service available.</p><div className="mt-7 rounded-2xl bg-[#f8faf9] p-5 text-left"><div className="flex gap-3"><ShieldAlert className="mt-0.5 shrink-0 text-[#c93642]" size={18}/><p className="text-[12px] leading-6 text-[#59645f]">Do not make payments or submit trading-account credentials for this service while it is marked Coming Soon. Availability will be announced through the official Arcus Strategy application.</p></div></div><Link href="/services" className="mt-8 inline-flex items-center gap-2 rounded-lg bg-[#087f3f] px-5 py-3 text-[12px] font-extrabold text-white hover:bg-[#066b35]"><ArrowLeft size={15}/> Back to Services</Link></div></section></main>;
}
