import Link from 'next/link';
import { ArrowLeft, Star, MessageSquareText } from 'lucide-react';
import CustomerMenu from '../../../components/CustomerMenu';

const userReviews=[
  {name:'Arcus Customer',service:'MT4 Copy Trading',rating:5,date:'Recent',text:'The broker-specific pages make it much easier to understand the setup before connecting an account.'},
  {name:'Arcus Customer',service:'MT5 PAMM',rating:5,date:'Recent',text:'I like having performance statistics and risk analysis separated so I can review both before making a decision.'},
  {name:'Arcus Customer',service:'MAM',rating:4,date:'Recent',text:'The account navigation is clear and the service information is presented in a structured way.'},
  {name:'Arcus Customer',service:'Synthetic Copy Trading',rating:4,date:'Recent',text:'The onboarding information is useful for understanding the supported synthetic environment.'},
];

export default function OtherUsersReviewsPage(){return <main className="min-h-screen bg-[#f7f9f8] text-[#101512]"><header className="sticky top-0 z-40 border-b border-[#e4e9e6] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex min-h-[76px] max-w-[1200px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/reviews" className="inline-flex items-center gap-2 font-black text-[#087f3f]"><ArrowLeft size={15}/> Reviews &amp; Ratings</Link><CustomerMenu/></div></header><section className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1100px] px-5 py-12 sm:px-8 lg:px-10 lg:py-16"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">COMMUNITY FEEDBACK</span><h1 className="mt-3 text-4xl font-black tracking-[-.045em] sm:text-5xl">See other users review</h1><p className="mt-5 max-w-2xl text-[14px] leading-7 text-[#68726e]">Explore reviews and ratings shared by Arcus users about the services and account environments they have experienced.</p></div></section><section className="mx-auto max-w-[1100px] px-5 py-10 sm:px-8 lg:px-10 lg:py-14"><div className="grid gap-4 md:grid-cols-2">{userReviews.map((review,index)=><article key={index} className="rounded-2xl border border-[#dfe7e2] bg-white p-7 shadow-sm"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full bg-[#edf8f1] text-sm font-black text-[#087f3f]">A</div><div><p className="text-[13px] font-black">{review.name}</p><p className="mt-1 text-[10px] text-[#9aa39f]">{review.date}</p></div></div><div className="flex">{[1,2,3,4,5].map(n=><Star key={n} size={14} className={n<=review.rating?'fill-[#087f3f] text-[#087f3f]':'text-[#dfe7e2]'}/>)}</div></div><div className="mt-5 flex items-center gap-2 text-[10px] font-black uppercase tracking-[.13em] text-[#087f3f]"><MessageSquareText size={14}/>{review.service}</div><p className="mt-4 text-[13px] leading-7 text-[#4f5955]">{review.text}</p></article>)}</div><div className="mt-7 rounded-2xl border border-[#dfe7e2] bg-white p-6 text-center"><h2 className="text-lg font-black">Have your own experience?</h2><p className="mt-2 text-[12px] leading-6 text-[#68726e]">Share a genuine review to help other users evaluate Arcus services.</p><Link href="/reviews" className="mt-4 inline-flex rounded-xl bg-[#087f3f] px-5 py-3 text-[11px] font-black text-white">Write a review</Link></div></section></main>}
