import Link from 'next/link';
import { ArrowLeft, Star, MessageSquareText, ThumbsUp, CheckCircle2, Filter } from 'lucide-react';
import CustomerMenu from '../../../components/CustomerMenu';

const userReviews=[
  {name:'Arcus Customer',service:'MT4 Copy Trading',rating:5,date:'Recent',text:'The broker-specific pages make it much easier to understand the setup before connecting an account.',helpful:12},
  {name:'Arcus Customer',service:'MT5 PAMM',rating:5,date:'Recent',text:'I like having performance statistics and risk analysis separated so I can review both before making a decision.',helpful:9},
  {name:'Arcus Customer',service:'MAM',rating:4,date:'Recent',text:'The account navigation is clear and the service information is presented in a structured way.',helpful:7},
  {name:'Arcus Customer',service:'Synthetic Copy Trading',rating:4,date:'Recent',text:'The onboarding information is useful for understanding the supported synthetic environment.',helpful:5},
];

const distribution=[{stars:5,count:2},{stars:4,count:2},{stars:3,count:0},{stars:2,count:0},{stars:1,count:0}];

function Stars({rating}:{rating:number}){return <div className="flex items-center gap-0.5" aria-label={`${rating} out of 5 stars`}>{[1,2,3,4,5].map(n=><Star key={n} size={16} className={n<=rating?'fill-[#f6b800] text-[#f6b800]':'text-[#d7ddd9]'}/>)}</div>}

export default function OtherUsersReviewsPage(){return <main className="min-h-screen bg-[#f7f9f8] text-[#101512]"><header className="sticky top-0 z-40 border-b border-[#e4e9e6] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex min-h-[76px] max-w-[1280px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/reviews" className="inline-flex items-center gap-2 text-[13px] font-black text-[#087f3f]"><ArrowLeft size={16}/> Reviews &amp; Ratings</Link><CustomerMenu/></div></header>

<section className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1100px] px-5 py-12 sm:px-8 lg:px-10 lg:py-16"><span className="text-[10px] font-black uppercase tracking-[.2em] text-[#087f3f]">CUSTOMER FEEDBACK</span><h1 className="mt-3 text-4xl font-black tracking-[-.045em] sm:text-5xl">Arcus Strategy reviews</h1><p className="mt-4 max-w-2xl text-[14px] leading-7 text-[#68726e]">See what other users are saying about Arcus Strategy services, account environments and customer experience.</p></div></section>

<section className="mx-auto max-w-[1100px] px-5 py-8 sm:px-8 lg:px-10 lg:py-12"><div className="overflow-hidden rounded-3xl border border-[#dfe7e2] bg-white shadow-sm"><div className="grid gap-8 p-7 sm:p-9 md:grid-cols-[260px_1fr] md:items-center"><div className="text-center md:border-r md:border-[#e7ece9] md:pr-8"><div className="text-6xl font-black tracking-[-.06em]">4.5</div><div className="mt-3 flex justify-center"><Stars rating={5}/></div><p className="mt-3 text-[11px] font-semibold text-[#68726e]">Based on 4 user reviews</p></div><div className="space-y-3">{distribution.map(row=><div key={row.stars} className="flex items-center gap-3"><span className="w-12 text-right text-[11px] font-bold text-[#59635f]">{row.stars} star</span><div className="h-2.5 flex-1 overflow-hidden rounded-full bg-[#edf1ee]"><div className="h-full rounded-full bg-[#f6b800]" style={{width:`${row.count ? row.count/2*100 : 0}%`}}/></div><span className="w-5 text-[11px] font-bold text-[#7a847f]">{row.count}</span></div>)}</div></div><div className="border-t border-[#e7ece9] bg-[#fbfcfb] px-7 py-5 sm:px-9"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[12px] font-black">What users are saying</p><p className="mt-1 text-[10px] text-[#7a847f]">Reviews are displayed by service and account environment.</p></div><Link href="/reviews" className="inline-flex items-center gap-2 rounded-xl bg-[#087f3f] px-4 py-2.5 text-[11px] font-black text-white"><MessageSquareText size={14}/> Write a review</Link></div></div></div>

<div className="mt-8 flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-black tracking-tight">All reviews</h2><button type="button" className="inline-flex items-center gap-2 rounded-xl border border-[#dfe7e2] bg-white px-4 py-2.5 text-[11px] font-black text-[#46514c]"><Filter size={14}/> Most relevant</button></div>

<div className="mt-4 divide-y divide-[#e7ece9] overflow-hidden rounded-3xl border border-[#dfe7e2] bg-white shadow-sm">{userReviews.map((review,index)=><article key={index} className="p-7 sm:p-8"><div className="flex items-start gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#087f3f] text-sm font-black text-white">A</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><p className="text-[13px] font-black">{review.name}</p><span className="inline-flex items-center gap-1 rounded-full bg-[#edf8f1] px-2 py-1 text-[9px] font-black text-[#087f3f]"><CheckCircle2 size={11}/> Arcus user</span></div><p className="mt-1 text-[10px] text-[#8a938e]">{review.date}</p></div><Stars rating={review.rating}/></div><div className="mt-4 flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#f2f6f3] px-2.5 py-1 text-[9px] font-black uppercase tracking-[.1em] text-[#087f3f]">{review.service}</span><span className="text-[10px] font-semibold text-[#8a938e]">Rated {review.rating}.0 / 5</span></div><p className="mt-4 max-w-3xl text-[13px] leading-7 text-[#4f5955]">{review.text}</p><button type="button" className="mt-5 inline-flex items-center gap-2 text-[10px] font-bold text-[#68726e] hover:text-[#087f3f]"><ThumbsUp size={14}/> Helpful · {review.helpful}</button></div></div></article>)}</div>

<div className="mt-7 rounded-2xl border border-[#dfe7e2] bg-white p-6 text-center"><h2 className="text-lg font-black">Have you used an Arcus service?</h2><p className="mt-2 text-[12px] leading-6 text-[#68726e]">Share your genuine experience and help other users evaluate the service before subscribing.</p><Link href="/reviews" className="mt-4 inline-flex rounded-xl bg-[#087f3f] px-5 py-3 text-[11px] font-black text-white">Write a review</Link></div></section></main>}
