import Link from 'next/link';
import { ArrowRight, BarChart3, Bot, ChartCandlestick, CircleHelp, GraduationCap, Mail, Network, ShieldCheck, Users } from 'lucide-react';

const services = [
  {title:'MT4 Copy Trading',icon:ChartCandlestick,text:'Replicate qualifying Arcus Strategy trades through supported MetaTrader 4 broker environments while your capital remains with your broker.'},
  {title:'MT5 Copy Trading',icon:BarChart3,text:'Access trade-replication workflows through supported MetaTrader 5 broker environments with dedicated performance and risk information.'},
  {title:'Synthetic & Deriv Copy Trading',icon:Network,text:'A copy-trading environment designed for supported synthetic and Deriv markets, with account-specific information for evaluation.'},
  {title:'cTrader Copy Trading',icon:ChartCandlestick,text:'Trade replication through supported cTrader environments with dedicated account performance and risk dashboards.'},
  {title:'PAMM Trading',icon:Users,text:'PAMM account environments that allow users to review the relevant broker structure, performance and risk information before participating.'},
  {title:'MAM Trading',icon:Users,text:'Multi-account management environments with account-specific performance and risk information across supported MT4 and MT5 brokers.'},
  {title:'PropFirm Assisted Trading',icon:ShieldCheck,text:'An assisted trading service designed around supported prop-firm account environments and the applicable account workflow.'},
  {title:'Serverless Algo Trading',icon:Bot,text:'Cloud-hosted algorithmic trading infrastructure for supported accounts, combining the Arcus algorithm with account hosting.'},
  {title:'TradingView Strategy',icon:BarChart3,text:'TradingView strategy automation that can deliver qualifying signals through supported webhook automation platforms.'},
  {title:'TradingView Indicator',icon:ChartCandlestick,text:'A professional TradingView indicator designed to provide structured buy and sell signals for supported markets.'},
  {title:'Pine Bridge',icon:Network,text:'A bridge service designed to allow users to automate trades from their TradingView setup to supported MT4, MT5 and cTrader environments.'},
  {title:'Crypto Social Trading',icon:Users,text:'Crypto social-trading environments where users can follow Arcus Strategy trades through supported crypto brokers without connecting their exchange API to Arcus.'},
];

export default function AboutPage(){
  return <main className="min-h-screen bg-[#f7f9f8] text-[#101512]">
    <header className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto flex min-h-[76px] max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#087f3f] text-sm font-black text-white">A</span><span><strong className="block text-[15px] tracking-[.16em]">ARCUS</strong><small className="block text-[8px] font-black tracking-[.35em] text-[#087f3f]">STRATEGY</small></span></Link><div className="flex items-center gap-3"><Link href="/blog" className="hidden text-[11px] font-black text-[#68726e] sm:block">Blog</Link><Link href="/signup" className="rounded-xl bg-[#087f3f] px-5 py-3 text-[11px] font-black text-white">Get Started</Link></div></div></header>

    <section className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="grid gap-12 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><span className="text-[10px] font-black tracking-[.22em] text-[#087f3f]">ABOUT ARCUS STRATEGY</span><h1 className="mt-5 max-w-5xl text-5xl font-black tracking-[-.055em] sm:text-6xl lg:text-[72px] lg:leading-[1.02]">Algorithmic trading technology built around execution, transparency and control.</h1><p className="mt-7 max-w-3xl text-[15px] leading-8 text-[#68726e]">Arcus Strategy develops systematic trading technology, trade-replication infrastructure and customer-facing tools for traders and investors who want structured access to algorithmic trading services.</p></div><div className="rounded-3xl border border-[#1f2a25] bg-[#101714] p-7 text-white"><span className="text-[9px] font-black tracking-[.2em] text-[#65d995]">THE ARCUS APPROACH</span><div className="mt-7 space-y-5"><Point title="Systematic" text="Rules-based strategy and execution workflows."/><Point title="Risk-aware" text="Performance is evaluated alongside drawdown and exposure."/><Point title="Transparent" text="Service, account and strategy information is separated by environment."/><Point title="Technology-led" text="Automation and infrastructure support disciplined execution."/></div></div></div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-10 lg:py-20"><div className="max-w-3xl"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">WHAT ARCUS STRATEGY DOES</span><h2 className="mt-3 text-4xl font-black tracking-tight">A trading ecosystem, not just a signal.</h2><p className="mt-5 text-[14px] leading-8 text-[#68726e]">Arcus Strategy combines algorithmic strategy development, trade replication, account-specific analytics and automation infrastructure. Our services are organised so users can review the relevant environment, performance information, risk information and onboarding requirements before using a service.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3"><Feature icon={Bot} title="Algorithmic Infrastructure" text="Systematic trading logic and automated execution workflows."/><Feature icon={BarChart3} title="Performance Intelligence" text="Dedicated performance statistics for supported account environments."/><Feature icon={ShieldCheck} title="Risk Transparency" text="Risk analysis designed to help users understand strategy behaviour before participating."/></div></section>

    <section className="border-y border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-10 lg:py-20"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">OUR SERVICES</span><h2 className="mt-3 text-4xl font-black tracking-tight">Explore the Arcus Strategy ecosystem.</h2></div><Link href="/services" className="inline-flex items-center gap-2 text-[11px] font-black text-[#087f3f]">View services <ArrowRight size={14}/></Link></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{services.map(({title,icon:Icon,text})=><article key={title} className="rounded-2xl border border-[#dfe7e2] bg-[#fbfcfb] p-6 transition hover:-translate-y-0.5 hover:shadow-lg"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#edf8f1] text-[#087f3f]"><Icon size={19}/></span><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-3 text-[12px] leading-6 text-[#68726e]">{text}</p></article>)}</div></div></section>

    <section className="bg-[#101714] text-white"><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-10 lg:py-20"><div className="grid gap-10 lg:grid-cols-2"><div><span className="text-[10px] font-black tracking-[.2em] text-[#65d995]">CONTACT ARCUS STRATEGY</span><h2 className="mt-3 text-4xl font-black tracking-tight">Need help choosing or using a service?</h2><p className="mt-5 max-w-xl text-[13px] leading-7 text-[#b9c4be]">Use the official Arcus customer support channel for service questions, account assistance and onboarding support. Always use information published through the official Arcus Strategy website.</p><Link href="/support" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#087f3f] px-5 py-3 text-[11px] font-black text-white">Contact Customer Support <ArrowRight size={14}/></Link></div><div className="grid gap-4 sm:grid-cols-2"><ContactCard icon={Mail} title="Customer Support" text="Contact Arcus through the official customer support centre." href="/support"/><ContactCard icon={CircleHelp} title="Help & Onboarding" text="Get guidance with services, account setup and customer workflows." href="/support"/><ContactCard icon={Network} title="Official Social Networks" text="Follow Arcus Strategy through the official social channels published by Arcus."/><ContactCard icon={GraduationCap} title="Education & Insights" text="Read the Arcus blog and explore structured trading education." href="/education"/></div></div></div></section>

    <footer className="border-t border-white/10 bg-[#101714] px-5 pb-10 text-[10px] text-[#8d9993] sm:px-8 lg:px-10"><div className="mx-auto flex max-w-[1440px] flex-col gap-3 pt-6 sm:flex-row sm:items-center sm:justify-between"><span>© 2026 Arcus Strategy Ltd. All rights reserved.</span><div className="flex gap-4"><Link href="/blog">Blog</Link><Link href="/education">Education</Link><Link href="/risk-analysis">Risk Analysis</Link></div></div></footer>
  </main>
}

function Point({title,text}:{title:string;text:string}){return <div><strong className="block text-sm font-black">{title}</strong><span className="mt-1 block text-[11px] leading-5 text-[#b9c4be]">{text}</span></div>}
function Feature({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <div className="rounded-2xl border border-[#dfe7e2] bg-white p-6"><Icon size={20} className="text-[#087f3f]"/><h3 className="mt-5 text-base font-black">{title}</h3><p className="mt-2 text-[12px] leading-6 text-[#68726e]">{text}</p></div>}
function ContactCard({icon:Icon,title,text,href}:{icon:any;title:string;text:string;href?:string}){const content=<div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><Icon size={18} className="text-[#65d995]"/><h3 className="mt-4 text-sm font-black">{title}</h3><p className="mt-2 text-[11px] leading-5 text-[#b9c4be]">{text}</p></div>;return href?<Link href={href} className="block transition hover:-translate-y-0.5">{content}</Link>:content}
