import Link from 'next/link';
import { ArrowRight, ChartCandlestick, CheckCircle2 } from 'lucide-react';
import CustomerMenu from '../../../../components/CustomerMenu';

const brokers = [{ name: 'Hantec Markets', slug: 'hantec-markets', description: 'Arcus MT4 copy trading environment for customers using Hantec Markets.', status: 'Available' }];

export default function MT4CopyTradingPage() {
  return <main className="min-h-screen bg-[#f7f9f8] text-[#101512]">
    <header className="sticky top-0 z-40 border-b border-[#e4e9e6] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex min-h-[76px] max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/services/social-trading" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#087f3f] text-sm font-black text-white">A</span><span><strong className="block text-[15px] tracking-[.16em]">ARCUS</strong><small className="block text-[8px] font-black tracking-[.35em] text-[#087f3f]">STRATEGY</small></span></Link><CustomerMenu /></div></header>
    <section className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-12 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:px-10 lg:py-16"><div><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">SOCIAL TRADING / MT4</span><h1 className="mt-3 text-4xl font-black tracking-[-.045em] sm:text-5xl">Choose your MT4 broker.</h1><p className="mt-5 max-w-2xl text-[15px] leading-7 text-[#68726e]">Arcus does not require you to hand over your trading account. You open and maintain your own broker account, then follow the broker-specific process that allows qualifying Arcus trades to be replicated on your account.</p></div><div className="rounded-2xl border border-[#dfe7e2] bg-[#101714] p-6 text-white"><ChartCandlestick className="text-[#65d995]" size={25}/><span className="mt-5 block text-[9px] font-black tracking-[.2em] text-[#8d9993]">MT4 ENVIRONMENT</span><strong className="mt-2 block text-xl">Broker-specific execution</strong><p className="mt-3 text-[12px] leading-6 text-[#aab4ae]">Select your broker below. Each broker gets its own Arcus information and onboarding page.</p></div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-10 sm:px-8 lg:px-10 lg:py-14"><div className="mb-7"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">AVAILABLE BROKERS</span><h2 className="mt-2 text-2xl font-black">MT4 copy trading environments</h2></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{brokers.map((broker)=><Link key={broker.slug} href={`/services/social-trading/mt4/${broker.slug}`} className="group rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-[#add8bd] hover:shadow-xl"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#edf8f1] text-[#087f3f]"><ChartCandlestick size={19}/></span><span className="inline-flex items-center gap-1 rounded-full bg-[#edf8f1] px-2.5 py-1 text-[8px] font-black uppercase tracking-wider text-[#087f3f]"><CheckCircle2 size={11}/> {broker.status}</span></div><h3 className="mt-7 text-xl font-black">{broker.name}</h3><p className="mt-2 text-[13px] leading-6 text-[#68726e]">{broker.description}</p><span className="mt-6 inline-flex items-center gap-2 text-[12px] font-extrabold text-[#087f3f]">View broker page <ArrowRight size={15}/></span></Link>)}</div></section>
  </main>;
}
