'use client';

import Link from 'next/link';
import { Star, MessageSquareText, ShieldCheck } from 'lucide-react';
import CustomerMenu from '../../components/CustomerMenu';
import { useState } from 'react';

const reviews = [
  { name: 'Arcus Customer', service: 'Copy Trading', rating: 5, text: 'Professional onboarding experience and clear instructions.' },
  { name: 'Arcus Customer', service: 'PAMM', rating: 5, text: 'The service structure makes it easy to understand where my account belongs.' },
  { name: 'Arcus Customer', service: 'AlgoTrading', rating: 4, text: 'A clean platform with a straightforward customer experience.' },
];

export default function ReviewsPage() {
  const [rating, setRating] = useState(0);
  return <main className="min-h-screen bg-[#f7f9f8] text-[#101512]"><header className="sticky top-0 z-40 border-b border-[#e4e9e6] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex min-h-[76px] max-w-[1200px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/dashboard" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#087f3f] text-sm font-black text-white">A</span><span><strong className="block text-[15px] tracking-[.16em]">ARCUS</strong><small className="block text-[8px] font-black tracking-[.35em] text-[#087f3f]">STRATEGY</small></span></Link><CustomerMenu/></div></header>
    <section className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1200px] px-5 py-12 sm:px-8 lg:px-10 lg:py-16"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">REVIEWS & RATINGS</span><h1 className="mt-3 max-w-3xl text-4xl font-black tracking-[-.045em] sm:text-5xl">Hear from the Arcus community.</h1><p className="mt-5 max-w-2xl text-[14px] leading-7 text-[#68726e]">Read customer feedback about Arcus services and share your own experience.</p></div></section>
    <section className="mx-auto max-w-[1200px] px-5 py-10 sm:px-8 lg:px-10 lg:py-14"><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#edf8f1] text-[#087f3f]"><Star size={19}/></span><h2 className="mt-5 text-xl font-black">Share your experience</h2><p className="mt-2 text-[13px] leading-6 text-[#68726e]">Rate the Arcus service you have used and leave a short review.</p><div className="mt-6 flex gap-1">{[1,2,3,4,5].map(value=><button type="button" key={value} aria-label={`${value} star`} onClick={()=>setRating(value)}><Star size={25} className={value<=rating?'fill-[#087f3f] text-[#087f3f]':'text-[#cbd3ce]'}/></button>)}</div><select className="mt-6 w-full rounded-xl border border-[#dfe7e2] px-4 py-3 text-[12px] outline-none"><option>Select service</option><option>Copy Trading</option><option>PAMM</option><option>MAM</option><option>Serverless AlgoTrading</option><option>PropFirm Assisted Trading</option></select><textarea rows={4} placeholder="Write your review..." className="mt-3 w-full rounded-xl border border-[#dfe7e2] px-4 py-3 text-[12px] outline-none focus:border-[#087f3f]"/><button type="button" className="mt-3 w-full rounded-xl bg-[#087f3f] px-5 py-3 text-[12px] font-black text-white">Submit review</button><p className="mt-3 text-[10px] text-[#9aa39f]">Reviews can be connected to the customer account and backend moderation workflow.</p></div>
    <div className="space-y-4"><div className="rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm"><div className="flex items-center gap-4"><div className="grid h-12 w-12 place-items-center rounded-xl bg-[#edf8f1] text-[#087f3f]"><MessageSquareText size={19}/></div><div><h2 className="text-xl font-black">Customer reviews</h2><p className="text-[12px] text-[#68726e]">Feedback from Arcus customers.</p></div></div></div>{reviews.map((review,index)=><article key={index} className="rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-[13px] font-black">{review.name}</p><p className="mt-1 text-[10px] font-black tracking-[.12em] text-[#087f3f]">{review.service}</p></div><div className="flex">{[1,2,3,4,5].map(n=><Star key={n} size={13} className={n<=review.rating?'fill-[#087f3f] text-[#087f3f]':'text-[#dfe7e2]'}/>)}</div></div><p className="mt-4 text-[13px] leading-6 text-[#4f5955]">{review.text}</p></article>)}</div></div><div className="mt-5 flex items-start gap-3 rounded-2xl border border-[#dfe7e2] bg-white p-5"><ShieldCheck size={18} className="mt-0.5 shrink-0 text-[#087f3f]"/><p className="text-[11px] leading-5 text-[#68726e]">Reviews should reflect genuine customer experiences. Arcus may moderate submissions for spam, abuse or content unrelated to the service.</p></div></section>
  </main>;
}
