'use client';

import Link from 'next/link';
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, Search, AlertTriangle } from 'lucide-react';

const services = [
  ['Customer 10024','Copy Trading · MT5','Active','Account configured and service activated'],
  ['Customer 10018','ServerLess Algotrading','Configuration pending','Account details received; configuration queue'],
  ['Customer 10022','Prop Firm A.T','Blocked','Required credentials/details have not been submitted'],
  ['Customer 10015','Copy Trading · MT4','Active','Account configured and service activated'],
  ['Customer 10011','MAM · MT5','Onboarding','Awaiting customer details'],
];
function cls(value:string){return value==='Active'?'bg-[#eaf7ef] text-[#087f3f]':value==='Blocked'?'bg-[#fff0f0] text-[#a23a3a]':'bg-[#fff6e4] text-[#966816]';}
export default function ServiceStatusPage(){return <main className="min-h-screen bg-[#f5f7f6] text-[#101512]"><header className="border-b border-[#dfe6e2] bg-white"><div className="flex min-h-[72px] items-center gap-3 px-5 sm:px-8 xl:px-10"><Link href="/admin/support" className="grid h-9 w-9 place-items-center rounded-xl border border-[#dfe6e2]"><ArrowLeft size={15}/></Link><div><p className="text-[8px] font-black uppercase tracking-[.2em] text-[#087f3f]">Customers</p><h1 className="mt-1 text-lg font-black">Service status</h1></div></div></header><section className="px-5 py-7 sm:px-8 xl:px-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-black tracking-[-.035em]">Customer service delivery</h2><p className="mt-1 text-[10px] text-[#707a75]">A support-facing view of purchased services and their current onboarding or activation state.</p></div><div className="flex items-center gap-2 rounded-xl border border-[#dfe6e2] bg-white px-3 py-2.5"><Search size={14} className="text-[#7b8580]"/><span className="text-[9px] text-[#8a938f]">Customer, service or status…</span></div></div><div className="mt-6 rounded-2xl border border-[#dfe6e2] bg-white p-6"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-[#f1f6f3] p-4"><CheckCircle2 size={16} className="text-[#087f3f]"/><strong className="mt-2 block text-xl font-black">2,184</strong><span className="text-[8px] text-[#718079]">Active services</span></div><div className="rounded-xl bg-[#fff6e4] p-4"><Clock3 size={16} className="text-[#966816]"/><strong className="mt-2 block text-xl font-black">74</strong><span className="text-[8px] text-[#718079]">Onboarding in progress</span></div><div className="rounded-xl bg-[#fff0f0] p-4"><AlertTriangle size={16} className="text-[#a23a3a]"/><strong className="mt-2 block text-xl font-black">18</strong><span className="text-[8px] text-[#718079]">Blocked cases</span></div></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b border-[#e8ecea] text-[8px] uppercase tracking-[.12em] text-[#88928d]"><th className="pb-3">Customer</th><th className="pb-3">Service</th><th className="pb-3">Status</th><th className="pb-3">Support detail</th><th></th></tr></thead><tbody>{services.map(([customer,service,status,detail])=><tr key={`${customer}-${service}`} className="border-b border-[#f0f2f1] text-[9px]"><td className="py-4 font-black">{customer}</td><td className="py-4 text-[#59645f]">{service}</td><td className="py-4"><span className={`rounded-full px-2 py-1 text-[7px] font-black ${cls(status)}`}>{status}</span></td><td className="py-4 text-[#68736e]">{detail}</td><td className="py-4 text-right"><Link href="/admin/customers" className="font-black text-[#087f3f]">Open customer <ArrowRight size={12} className="inline"/></Link></td></tr>)}</tbody></table></div></div></section></main>;}
