import Link from 'next/link';
import { ArrowLeft, BarChart3, CheckCircle2, CircleHelp, ExternalLink, ShieldAlert } from 'lucide-react';
import CustomerMenu from '../../../../../components/CustomerMenu';
import { singleBrokers } from '../../../../../lib/broker-config';

export function generateStaticParams(){return [{broker:'deriv'}]}

export default async function SyntheticBrokerPage({params}:{params:Promise<{broker:string}>}){
  const {broker}=await params;
  if(broker!=='deriv') return <main className="p-10"><Link href="/services/social-trading/synthetic">← Back</Link><h1 className="mt-10 text-3xl font-black">Broker unavailable</h1></main>;
  const b=singleBrokers.synthetic;
  const minimumDeposit=300;
  return <main className="min-h-screen bg-[#f7f9f8] text-[#101512]">
    <header className="sticky top-0 z-40 border-b border-[#e4e9e6] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex min-h-[76px] max-w-[1100px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/services/social-trading/synthetic" className="inline-flex items-center gap-2 font-black text-[#087f3f]"><ArrowLeft size={15}/> Deriv &amp; Synthetic</Link><CustomerMenu/></div></header>
    <section className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1100px] px-5 py-8 sm:px-8 lg:px-10"><div className="flex items-center justify-between gap-3"><Link href="/services/social-trading/synthetic" className="text-[11px] font-extrabold text-[#68726e]">Synthetic Broker</Link><div className="flex gap-2"><Link href={`/performance-statistics/copy-trading/synthetic/${b.slug}`} className="inline-flex items-center gap-2 rounded-xl bg-[#087f3f] px-4 py-2.5 text-[11px] font-extrabold text-white"><BarChart3 size={14}/> Performance Statistics</Link><Link href={`/risk-analysis/copy-trading/synthetic/${b.slug}`} className="inline-flex items-center gap-2 rounded-xl border border-[#f0c9cd] bg-[#fff7f7] px-4 py-2.5 text-[11px] font-extrabold text-[#c93642]"><ShieldAlert size={14}/> Risk Analysis</Link></div></div></div></section>
    <section className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1100px] px-5 py-12 sm:px-8 lg:px-10 lg:py-16"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">DERIV &amp; SYNTHETIC COPY TRADING / {b.name.toUpperCase()}</span><h1 className="mt-3 max-w-4xl text-4xl font-black tracking-[-.045em] sm:text-5xl">Copy Arcus Strategy trades on {b.name}.</h1><p className="mt-5 max-w-3xl text-[15px] leading-7 text-[#68726e]">Your broker account remains yours. Arcus does not ask you to transfer funds or hand over your broker password. Follow the broker-specific onboarding process below to access the Arcus synthetic-index copy-trading environment.</p></div></section>
    <section className="mx-auto max-w-[1000px] px-5 py-10 sm:px-8 lg:px-10 lg:py-14"><div className="space-y-4">
      <article className="rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#edf8f1] text-[12px] font-black text-[#087f3f]">01</span><div className="flex-1"><span className="text-[9px] font-black tracking-[.18em] text-[#087f3f]">INSTRUCTION 1</span><h2 className="mt-2 text-xl font-black">Sign up on {b.name} synthetic copy trading</h2><p className="mt-2 max-w-2xl text-[13px] leading-6 text-[#68726e]">Create your own {b.name} account through the broker's registration process and complete the required onboarding checks.</p><a href="#" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#087f3f] px-5 py-3 text-[11px] font-extrabold text-white">Register with {b.name} <ExternalLink size={14}/></a><p className="mt-2 text-[10px] text-[#9aa39f]">Affiliate registration link will be enabled when supplied.</p></div></div></article>
      <article className="rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#edf8f1] text-[12px] font-black text-[#087f3f]">02</span><div><span className="text-[9px] font-black tracking-[.18em] text-[#087f3f]">INSTRUCTION 2</span><h2 className="mt-2 text-xl font-black">Verify your account and Deposit</h2><p className="mt-2 text-[13px] leading-6 text-[#68726e]">Complete the broker's verification requirements, then fund the account before proceeding to copy Arcus Strategy.</p><div className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#f5f8f6] px-4 py-3 text-[11px] font-extrabold text-[#101512]"><CheckCircle2 size={15} className="text-[#087f3f]"/> Minimum deposit: <span className="text-[#087f3f]">${minimumDeposit.toLocaleString()}</span></div></div></div></article>
      <article className="rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#edf8f1] text-[12px] font-black text-[#087f3f]">03</span><div><span className="text-[9px] font-black tracking-[.18em] text-[#087f3f]">INSTRUCTION 3</span><h2 className="mt-2 text-xl font-black">Search Arcus Strategy on the copy-trading platform</h2><p className="mt-2 text-[13px] leading-6 text-[#68726e]">Open the supported synthetic-index copy-trading environment and search for the official Arcus Strategy profile or strategy identifier.</p></div></div></article>
      <article className="rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#edf8f1] text-[12px] font-black text-[#087f3f]">04</span><div><span className="text-[9px] font-black tracking-[.18em] text-[#087f3f]">INSTRUCTION 4</span><h2 className="mt-2 text-xl font-black">Follow Arcus Strategy to copy our trades</h2><p className="mt-2 text-[13px] leading-6 text-[#68726e]">Select the official Arcus Strategy profile and complete the platform's follow/copy confirmation. Review the risk and allocation settings before activating replication.</p></div></div></article>
      <article className="rounded-2xl border border-[#dfe7e2] bg-[#101714] p-6 text-white shadow-sm sm:p-8"><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white/10 text-[12px] font-black text-[#65d995]"><CircleHelp size={17}/></span><div className="flex-1"><span className="text-[9px] font-black tracking-[.18em] text-[#65d995]">NEXT ASSISTANCE</span><h2 className="mt-2 text-xl font-black">Need help?</h2><p className="mt-2 text-[13px] leading-6 text-[#b4beb9]">If you are unsure about any step, contact Arcus customer support before activating copy trading. Never send your broker password to support.</p><Link href="/support" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-[11px] font-extrabold text-[#101714]">ASK SUPPORT</Link></div></div></article>
    </div></section>
    <section className="border-t border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1000px] px-5 py-8 sm:px-8 lg:px-10"><div className="flex items-start gap-3 rounded-2xl bg-[#fff7f7] p-5"><ShieldAlert className="mt-0.5 shrink-0 text-[#c93642]" size={18}/><p className="text-[11px] leading-5 text-[#6f5b5e]">Synthetic-index and copy trading can produce substantial losses. Execution, pricing, liquidity, sizing and platform conditions can cause results to differ from Arcus source activity. Past performance does not guarantee future results.</p></div></div></section>
  </main>
}
