'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { ArrowLeft, CheckCircle2, ChevronDown, Clock3, LockKeyhole, MessageSquare, Paperclip, Send, ShieldCheck, UserRound, UserPlus, AlertTriangle } from 'lucide-react';
import { useState } from 'react';

const ticket = { customer: 'Customer 10024', email: 'customer10024@example.com', category: 'Copy Trading', subject: 'MT5 copy trading account has not activated', priority: 'High', status: 'Open', assigned: 'Support 01', created: '14 Aug 2026 · 13:22' };

const messages = [
  { from: 'Customer 10024', role: 'Customer', time: '13:22', body: 'I completed the payment and submitted my MT5 account details, but the service has not activated yet. Please help me check the setup.' },
  { from: 'Support 01', role: 'Support', time: '13:31', body: 'Thanks for contacting Arcus Strategy. I am checking your onboarding status and will update you here.' },
];

export default function SupportTicketWorkspace() {
  const { ticketId } = useParams<{ ticketId: string }>();
  const [status, setStatus] = useState(ticket.status);
  const [priority, setPriority] = useState(ticket.priority);
  const [reply, setReply] = useState('');

  return <main className="min-h-screen bg-[#f5f7f6] text-[#101512]">
    <header className="sticky top-0 z-20 border-b border-[#dfe6e2] bg-white/95 backdrop-blur"><div className="flex min-h-[72px] items-center justify-between gap-4 px-5 sm:px-8 xl:px-10"><div className="flex items-center gap-3"><Link href="/admin/support/tickets" className="grid h-9 w-9 place-items-center rounded-xl border border-[#dfe6e2] bg-white"><ArrowLeft size={15}/></Link><div><p className="text-[8px] font-black uppercase tracking-[.2em] text-[#087f3f]">Support workspace</p><h1 className="mt-1 text-lg font-black">Ticket #{ticketId}</h1></div></div><div className="flex items-center gap-2"><span className={`rounded-full px-3 py-2 text-[8px] font-black ${priority === 'High' ? 'bg-[#fff0f0] text-[#a23a3a]' : 'bg-[#fff6e4] text-[#966816]'}`}>{priority} priority</span><span className="rounded-full bg-[#eaf7ef] px-3 py-2 text-[8px] font-black text-[#087f3f]">{status}</span></div></div></header>

    <section className="grid gap-5 px-5 py-6 sm:px-8 xl:grid-cols-[1.35fr_.65fr] xl:px-10">
      <div className="space-y-5">
        <div className="rounded-2xl border border-[#dfe6e2] bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[8px] font-black uppercase tracking-[.18em] text-[#087f3f]">{ticket.category}</p><h2 className="mt-1 text-xl font-black tracking-[-.025em]">{ticket.subject}</h2><p className="mt-2 text-[9px] text-[#7b8580]">Created {ticket.created}</p></div><Link href="/admin/customers" className="inline-flex items-center gap-2 rounded-xl border border-[#dfe6e2] px-3 py-2 text-[9px] font-black"><UserRound size={13}/> View customer</Link></div><div className="mt-5 flex flex-wrap gap-2"><select value={status} onChange={e => setStatus(e.target.value)} className="rounded-xl border border-[#dfe6e2] bg-white px-3 py-2 text-[9px] font-black"><option>Open</option><option>In Progress</option><option>Waiting for Customer</option><option>Escalated</option><option>Resolved</option><option>Closed</option></select><select value={priority} onChange={e => setPriority(e.target.value)} className="rounded-xl border border-[#dfe6e2] bg-white px-3 py-2 text-[9px] font-black"><option>High</option><option>Medium</option><option>Low</option></select><button className="inline-flex items-center gap-2 rounded-xl border border-[#dfe6e2] bg-white px-3 py-2 text-[9px] font-black"><UserPlus size={13}/> Assign</button><button className="inline-flex items-center gap-2 rounded-xl bg-[#b33a3a] px-3 py-2 text-[9px] font-black text-white"><AlertTriangle size={13}/> Escalate</button></div></div>

        <div className="rounded-2xl border border-[#dfe6e2] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-[8px] font-black uppercase tracking-[.18em] text-[#087f3f]">Conversation</p><h3 className="mt-1 text-base font-black">Customer communication</h3></div><span className="inline-flex items-center gap-1.5 text-[8px] font-bold text-[#7b8580]"><MessageSquare size={13}/> 2 messages</span></div><div className="mt-5 space-y-4">{messages.map(message => <div key={`${message.from}-${message.time}`} className={`rounded-2xl border p-4 ${message.role === 'Customer' ? 'border-[#e2e8e4] bg-[#f8faf9]' : 'border-[#cfe5d7] bg-[#f2faf5]'}`}><div className="flex items-center justify-between gap-3"><div><strong className="text-[10px] font-black">{message.from}</strong><span className="ml-2 rounded-full bg-white px-2 py-1 text-[7px] font-black text-[#087f3f]">{message.role}</span></div><span className="text-[8px] text-[#89928e]">{message.time}</span></div><p className="mt-3 text-[10px] leading-5 text-[#4f5b55]">{message.body}</p></div>)}</div><div className="mt-5 rounded-2xl border border-[#dfe6e2] bg-white"><textarea value={reply} onChange={e => setReply(e.target.value)} placeholder="Write a reply to the customer…" className="min-h-[120px] w-full resize-none rounded-2xl p-4 text-[10px] outline-none"/><div className="flex items-center justify-between border-t border-[#edf0ee] px-4 py-3"><button className="inline-flex items-center gap-2 text-[9px] font-black text-[#68736e]"><Paperclip size={13}/> Attach</button><button className="inline-flex items-center gap-2 rounded-xl bg-[#087f3f] px-4 py-2.5 text-[9px] font-black text-white"><Send size={13}/> Send reply</button></div></div></div>

        <div className="rounded-2xl border border-[#e6ddd0] bg-[#fffaf2] p-5"><div className="flex gap-3"><LockKeyhole size={15} className="mt-0.5 shrink-0 text-[#966816]"/><div><strong className="text-[9px] font-black text-[#725817]">Internal note</strong><textarea placeholder="Add a private note for support staff…" className="mt-2 min-h-[70px] w-full rounded-xl border border-[#eadfcf] bg-white p-3 text-[9px] outline-none"/><button className="mt-2 rounded-lg bg-[#102019] px-3 py-2 text-[8px] font-black text-white">Add internal note</button></div></div></div>
      </div>

      <aside className="space-y-5">
        <div className="rounded-2xl border border-[#dfe6e2] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-[8px] font-black uppercase tracking-[.18em] text-[#087f3f]">Customer</p><h3 className="mt-1 text-base font-black">{ticket.customer}</h3></div><UserRound size={18} className="text-[#087f3f]"/></div><p className="mt-2 text-[9px] text-[#7b8580]">{ticket.email}</p><div className="mt-5 space-y-3"><div className="flex justify-between text-[9px]"><span className="text-[#7b8580]">Subscription</span><strong>Active</strong></div><div className="flex justify-between text-[9px]"><span className="text-[#7b8580]">Services</span><strong>2 active</strong></div><div className="flex justify-between text-[9px]"><span className="text-[#7b8580]">KYC</span><span className="rounded-full bg-[#eaf7ef] px-2 py-1 text-[7px] font-black text-[#087f3f]">Approved</span></div><div className="flex justify-between text-[9px]"><span className="text-[#7b8580]">Onboarding</span><span className="rounded-full bg-[#fff6e4] px-2 py-1 text-[7px] font-black text-[#966816]">Configuration pending</span></div></div><Link href="/admin/customers" className="mt-5 flex items-center justify-center rounded-xl border border-[#dfe6e2] px-3 py-2.5 text-[9px] font-black">Open customer profile</Link></div>
        <div className="rounded-2xl border border-[#dfe6e2] bg-white p-6"><div className="flex items-center gap-2"><ShieldCheck size={16} className="text-[#087f3f]"/><h3 className="text-base font-black">Onboarding status</h3></div><div className="mt-5 space-y-3">{[['Payment completed', true], ['Service purchased', true], ['Credentials/details submitted', true], ['Account configured', false], ['Service activated', false]].map(([label,done]) => <div key={label as string} className="flex items-center gap-3"><div className={`grid h-7 w-7 place-items-center rounded-full ${done ? 'bg-[#eaf7ef] text-[#087f3f]' : 'bg-[#fff6e4] text-[#966816]'}`}>{done ? <CheckCircle2 size={14}/> : <Clock3 size={14}/>}</div><div><strong className="block text-[9px] font-black">{label as string}</strong><span className="text-[8px] text-[#7b8580]">{done ? 'Complete' : 'Requires action'}</span></div></div>)}</div></div>
        <div className="rounded-2xl border border-[#dfe6e2] bg-white p-6"><p className="text-[8px] font-black uppercase tracking-[.18em] text-[#087f3f]">Ticket controls</p><div className="mt-4 space-y-2"><button className="flex w-full items-center justify-between rounded-xl border border-[#dfe6e2] px-3 py-2.5 text-[9px] font-black">Assigned to <span>{ticket.assigned} <ChevronDown size={12} className="ml-1 inline"/></span></button><button className="flex w-full items-center justify-between rounded-xl border border-[#dfe6e2] px-3 py-2.5 text-[9px] font-black">SLA <span className="text-[#087f3f]">2h 14m remaining</span></button></div></div>
      </aside>
    </section>
  </main>;
}
