import Link from 'next/link';
import { ArrowLeft, ArrowRight, CheckCircle2, ExternalLink, HelpCircle, ShieldCheck } from 'lucide-react';
import CustomerMenu from '../../../../components/CustomerMenu';

type Platform = {
  name: string;
  eyebrow: string;
  headline: string;
  description: string;
  features: string[];
  steps: string[];
  requirements: string[];
  faq: [string, string][];
  cta: string;
};

const data: Record<string, Platform> = {
  zignaly: {
    name: 'Zignaly', eyebrow: 'ARCUS STRATEGY × ZIGNALY', headline: 'Automate Your Trading with Zignaly',
    description: 'Connect Arcus Strategy to your Zignaly workflow and automatically execute qualifying trades generated by our TradingView strategies. Webhook alerts are delivered to the configured automation workflow while you retain control of your exchange account.',
    features: ['Automated strategy execution', 'Cloud-based trading', 'Multiple exchange support', 'Real-time webhook processing', 'Secure exchange connection workflow'],
    steps: ['Subscribe to Arcus Strategy.', 'Create or sign in to your Zignaly account.', 'Connect your supported exchange according to Zignaly requirements.', 'Import and configure the Arcus Strategy webhook.', 'Test the workflow, review your risk settings and activate automation.'],
    requirements: ['Active Arcus Strategy subscription', 'Zignaly account', 'Supported exchange account', 'TradingView webhook access', 'A reviewed automation and risk configuration'],
    faq: [['Do I connect my exchange API to Arcus Strategy?', 'No. Your exchange connection is configured through the supported automation platform. Arcus Strategy provides the strategy workflow and onboarding guidance.'], ['Can I test before using live capital?', 'Yes. You should test the complete webhook and execution workflow and review all risk settings before live trading.']],
    cta: 'Connect with Zignaly →'
  },
  cryptohopper: {
    name: 'Cryptohopper', eyebrow: 'ARCUS STRATEGY × CRYPTOHOPPER', headline: 'Intelligent Trading Automation with Cryptohopper',
    description: 'Integrate Arcus Strategy with Cryptohopper to transform TradingView webhook alerts into automated trade execution while you maintain control of your exchange account and bot configuration.',
    features: ['Webhook automation', 'Cloud trading', 'Portfolio management workflow', 'Exchange connectivity', '24/7 automation capability'],
    steps: ['Subscribe to Arcus Strategy.', 'Create or sign in to Cryptohopper.', 'Connect your exchange inside Cryptohopper.', 'Configure the Arcus Strategy webhook.', 'Test the bot and enable automated execution after reviewing your settings.'],
    requirements: ['Active Arcus Strategy subscription', 'Cryptohopper account', 'Supported exchange account', 'TradingView alerts/webhook access', 'Configured bot and risk parameters'],
    faq: [['Does Arcus hold my exchange funds?', 'No. Your exchange account and funds remain under your control.'], ['Is automation guaranteed to be profitable?', 'No. Automated execution does not guarantee profits and can result in losses.']],
    cta: 'Connect with Cryptohopper →'
  },
  '3commas': {
    name: '3Commas', eyebrow: 'ARCUS STRATEGY × 3COMMAS', headline: 'Automated Strategy Execution with 3Commas',
    description: 'Deploy Arcus Strategy TradingView alerts into a structured 3Commas automation workflow. The configured workflow can translate qualifying alerts into trade actions on your connected exchange.',
    features: ['TradingView webhook support', 'Smart Trade automation workflow', 'Exchange integration', 'Risk management controls', 'Continuous monitoring workflow'],
    steps: ['Subscribe to Arcus Strategy.', 'Connect your exchange to 3Commas.', 'Configure the TradingView webhook workflow.', 'Review trade sizing and risk controls.', 'Test the integration and activate the strategy.'],
    requirements: ['Active Arcus Strategy subscription', '3Commas account', 'Supported exchange connection', 'TradingView webhook configuration', 'Reviewed execution and risk settings'],
    faq: [['Can I control my exchange connection?', 'Yes. The exchange connection is maintained through your configured 3Commas environment.'], ['Should I test webhook execution first?', 'Yes. Verify alerts, payloads and execution behavior before deploying live capital.']],
    cta: 'Connect with 3Commas →'
  },
  relay: {
    name: 'Relay', eyebrow: 'ARCUS STRATEGY × RELAY', headline: 'Fast Webhook-Based Trade Automation',
    description: 'Use Relay to receive TradingView webhook alerts from Arcus Strategy and automate supported trading actions through a guided workflow with minimal configuration.',
    features: ['Fast webhook processing', 'Automated execution workflow', 'Guided setup', 'Secure workflow automation'],
    steps: ['Subscribe to Arcus Strategy.', 'Create or sign in to your Relay account.', 'Configure the Arcus Strategy webhook.', 'Connect the supported trading destination.', 'Test the workflow and activate automated execution.'],
    requirements: ['Active Arcus Strategy subscription', 'Relay account', 'Supported destination', 'TradingView webhook access', 'Tested automation workflow'],
    faq: [['What does Relay do in the workflow?', 'Relay receives the configured TradingView event and routes it into the supported automation workflow.'], ['Do I still control my trading account?', 'Yes. Your account remains under your control and you are responsible for its settings and risk.']],
    cta: 'Connect with Relay →'
  },
  dash2trade: {
    name: 'Dash2Trade', eyebrow: 'ARCUS STRATEGY × DASH2TRADE', headline: 'Smarter Trading Through Automation',
    description: 'Combine Dash2Trade workflows with Arcus Strategy TradingView alerts to create a structured automation process for supported markets and execution environments.',
    features: ['Strategy automation', 'Market intelligence workflow', 'Signal execution', 'Risk monitoring'],
    steps: ['Subscribe to Arcus Strategy.', 'Configure your Dash2Trade account.', 'Add the Arcus Strategy webhook.', 'Review execution and risk settings.', 'Test the workflow before beginning automated execution.'],
    requirements: ['Active Arcus Strategy subscription', 'Dash2Trade account', 'Compatible execution environment', 'TradingView webhook access', 'Reviewed risk settings'],
    faq: [['Is Dash2Trade required to use the Arcus strategy?', 'It is one of the supported automation integrations presented by Arcus Strategy.'], ['Can market conditions affect results?', 'Yes. Market conditions, liquidity and execution quality can materially affect automated trading results.']],
    cta: 'Connect with Dash2Trade →'
  },
  'alpha-insider': {
    name: 'Alpha Insider', eyebrow: 'ARCUS STRATEGY × ALPHA INSIDER', headline: 'Professional Strategy Automation',
    description: 'Connect an Alpha Insider automation workflow to Arcus Strategy and use TradingView webhook technology for rules-based execution with a structured onboarding process.',
    features: ['Automated trading workflow', 'Professional execution workflow', 'Secure connection process', 'Cloud-based automation'],
    steps: ['Subscribe to Arcus Strategy.', 'Create or sign in to Alpha Insider.', 'Connect your supported broker or execution environment.', 'Activate the Arcus Strategy workflow.', 'Test the configuration before using live capital.'],
    requirements: ['Active Arcus Strategy subscription', 'Alpha Insider account', 'Supported broker/execution environment', 'TradingView webhook access', 'Completed configuration and testing'],
    faq: [['Who is responsible for the connected account?', 'You remain responsible for your account, configuration, capital and risk decisions.'], ['Does automation remove trading risk?', 'No. Automation changes execution mechanics but does not eliminate market or execution risk.']],
    cta: 'Connect with Alpha Insider →'
  },
  wundertrading: {
    name: 'WunderTrading', eyebrow: 'ARCUS STRATEGY × WUNDERTRADING', headline: 'Advanced Crypto Trading Automation',
    description: 'Integrate Arcus Strategy with WunderTrading to automate supported cryptocurrency strategies using TradingView webhook alerts. Connect your exchange through WunderTrading and configure the Arcus workflow.',
    features: ['TradingView integration', 'Multi-exchange support', 'Portfolio automation', 'Cloud execution', 'Webhook trading'],
    steps: ['Subscribe to Arcus Strategy.', 'Create your WunderTrading account.', 'Connect your exchange.', 'Configure the Arcus Strategy webhook alerts.', 'Test the integration and activate automated trading.'],
    requirements: ['Active Arcus Strategy subscription', 'WunderTrading account', 'Supported cryptocurrency exchange', 'TradingView webhook access', 'Reviewed bot and risk configuration'],
    faq: [['Does Arcus directly access my exchange?', 'The intended workflow uses the selected automation platform for the exchange connection rather than requiring you to hand your exchange credentials to Arcus Strategy.'], ['Is crypto automation risk-free?', 'No. Cryptocurrency markets can be highly volatile and automated execution can amplify losses.']],
    cta: 'Connect with WunderTrading →'
  }
};

export function generateStaticParams() { return Object.keys(data).map(platform => ({ platform })); }

export default async function PlatformPage({ params }: { params: Promise<{ platform: string }> }) {
  const { platform } = await params;
  const item = data[platform];
  if (!item) return null;

  return <main className="min-h-screen bg-[#f7f9f8] text-[#101512]">
    <header className="sticky top-0 z-40 border-b border-[#e4e9e6] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex min-h-[76px] max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/dashboard" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#087f3f] text-sm font-black text-white">A</span><span><strong className="block text-[15px] tracking-[.16em]">ARCUS</strong><small className="block text-[8px] font-black tracking-[.35em] text-[#087f3f]">STRATEGY</small></span></Link><CustomerMenu /></div></header>
    <div className="mx-auto max-w-[1200px] px-5 py-7 sm:px-8 lg:px-10"><Link href="/services/tradingview-strategy" className="inline-flex items-center gap-2 text-[12px] font-extrabold text-[#087f3f]"><ArrowLeft size={15}/> TradingView Strategy</Link></div>
    <section className="mx-auto max-w-[1200px] px-5 pb-10 sm:px-8 lg:px-10"><div className="overflow-hidden rounded-3xl border border-[#dfe7e2] bg-white shadow-sm"><div className="border-b border-[#e4e9e6] px-7 py-8 sm:px-11 sm:py-11"><span className="text-[10px] font-black tracking-[.22em] text-[#087f3f]">{item.eyebrow}</span><div className="mt-6 flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-4xl"><h1 className="text-4xl font-black tracking-[-.045em] sm:text-5xl">{item.headline}</h1><p className="mt-5 text-[15px] leading-7 text-[#68726e]">{item.description}</p></div><Link href={`/services/tradingview-strategy/${platform}/subscribe`} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-[#087f3f] px-5 py-3.5 text-[12px] font-black text-white">Subscribe & Get Started <ArrowRight size={15}/></Link></div></div><div className="grid gap-px bg-[#e4e9e6] sm:grid-cols-3"><div className="bg-white p-6"><span className="text-[9px] font-black tracking-[.18em] text-[#9aa39f]">PLATFORM</span><p className="mt-2 text-lg font-black">{item.name}</p></div><div className="bg-white p-6"><span className="text-[9px] font-black tracking-[.18em] text-[#9aa39f]">AUTOMATION</span><p className="mt-2 text-lg font-black">TradingView Webhooks</p></div><div className="bg-white p-6"><span className="text-[9px] font-black tracking-[.18em] text-[#9aa39f]">MODEL</span><p className="mt-2 text-lg font-black">Rules-based execution</p></div></div></div></section>
    <section className="mx-auto max-w-[1200px] px-5 pb-10 sm:px-8 lg:px-10"><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-[#dfe7e2] bg-white p-7 sm:p-8"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">FEATURES</span><h2 className="mt-3 text-2xl font-black">Built for structured automation.</h2><div className="mt-7 space-y-4">{item.features.map(feature => <div key={feature} className="flex gap-3"><CheckCircle2 size={18} className="mt-0.5 shrink-0 text-[#087f3f]"/><p className="text-[13px] leading-6">{feature}</p></div>)}</div></div><div className="rounded-2xl border border-[#dfe7e2] bg-white p-7 sm:p-8"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">HOW IT WORKS</span><h2 className="mt-3 text-2xl font-black">From subscription to automation.</h2><div className="mt-7 space-y-5">{item.steps.map((step,index) => <div key={step} className="flex gap-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#edf8f1] text-[11px] font-black text-[#087f3f]">{index + 1}</span><p className="text-[13px] leading-6">{step}</p></div>)}</div></div></div></section>
    <section className="border-y border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1200px] px-5 py-12 sm:px-8 lg:px-10"><div className="grid gap-5 lg:grid-cols-2"><div><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">REQUIREMENTS</span><h2 className="mt-3 text-2xl font-black">Before you connect</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{item.requirements.map(req => <div key={req} className="rounded-xl bg-[#f7f9f8] p-4 text-[12px] font-semibold leading-5">{req}</div>)}</div></div><div><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">FAQ</span><h2 className="mt-3 text-2xl font-black">Common questions</h2><div className="mt-5 space-y-3">{item.faq.map(([q,a]) => <details key={q} className="rounded-xl border border-[#dfe7e2] bg-white p-4"><summary className="cursor-pointer text-[13px] font-black">{q}</summary><p className="mt-3 text-[12px] leading-6 text-[#68726e]">{a}</p></details>)}</div></div></div></div></section>
    <section className="mx-auto max-w-[1200px] px-5 py-10 sm:px-8 lg:px-10"><div className="rounded-2xl bg-[#101512] p-7 text-white sm:p-9"><div className="flex gap-4"><ShieldCheck className="mt-0.5 shrink-0"/><div><h2 className="text-xl font-black">Risk & execution disclaimer</h2><p className="mt-3 max-w-4xl text-[12px] leading-6 text-white/65">Automated trading involves substantial risk. Market conditions, volatility, liquidity, execution quality, third-party platform availability and configuration can affect outcomes. No strategy guarantees profits. Review and test your complete automation setup before using live capital.</p></div></div><Link href={`/services/tradingview-strategy/${platform}/subscribe`} className="mt-7 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-[12px] font-black text-[#101512]">{item.cta} <ExternalLink size={14}/></Link></div></section>
    <div className="mx-auto max-w-[1200px] px-5 pb-12 sm:px-8 lg:px-10"><Link href="/support" className="inline-flex items-center gap-2 text-[12px] font-extrabold text-[#087f3f]"><HelpCircle size={15}/> Need help with setup? Ask Support</Link></div>
  </main>;
}
