import Link from 'next/link';
import { ArrowLeft, ChevronDown, Clock3, MessageSquare, Paperclip, Send, ShieldCheck, UserRound } from 'lucide-react';

const ticket = { id: '1028', customer: 'Customer 10024', email: 'customer10024@example.com', category: 'Copy Trading', priority: 'High', status: 'Open', assigned: 'Support 01', service: 'Copy Trading · MT5', opened: 'Today, 08:34' };

export default async function TicketWorkspace({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  return <main className="min-h-screen bg-[#f5f7f6] text-[#101512]">
    <header className="border-b border-[#dfe6e2] bg-white px-5 py-5 sm:px-8 xl:px-10"><Link href="/admin/support" className="inline-flex items-center gap-2 text-[9px] font-black text-[#087f3f]"><ArrowLeft size={14}/> Back to support dashboard</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="text-[8px] font-black uppercase tracking-[.18em] text-[#7b8580]">Support workspace</p><h1 className="mt-1 text-2xl font-black tracking-[-.035em]">Ticket #{id}</h1><p className="mt-1 text-[10px] text-[#707a75]">Copy Trading onboarding · opened {ticket.opened}</p></div><div className="flex gap-2"><button className="rounded-xl border border-[#d3ddd7] bg-white px-3 py-2 text-[9px] font-black">Assign</button><button className="rounded-xl bg-[#087f3f] px-4 py-2 text-[9px] font-black text-white">Resolve ticket</button></div></div></header>
    <div className="grid gap-5 p-5 sm:p-8 xl:grid-cols-[1fr_320px] xl:p-10">
      <section className="space-y-4">
        <div className="rounded-2xl border border-[#dfe6e2] bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[8px] font-black uppercase tracking-[.16em] text-[#087f3f]">Conversation</p><h2 className="mt-1 text-base font-black">Customer request</h2></div><div className="flex gap-2"><span className="rounded-full bg-[#fff0f0] px-2 py-1 text-[7px] font-black text-[#a23a3a]">High</span><span className="rounded-full bg-[#f1f4f2] px-2 py-1 text-[7px] font-black text-[#65706b]">Open</span></div></div><div className="mt-5 rounded-xl bg-[#f7f9f8] p-4"><div className="flex gap-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#dfeee5] text-[9px] font-black text-[#087f3f]">CU</div><div><div className="text-[9px] font-black">{ticket.customer}</div><div className="mt-0.5 text-[7px] text-[#89928e]">Customer · {ticket.opened}</div><p className="mt-3 text-[10px] leading-5 text-[#39443f]">I completed payment for Copy Trading and selected the MT5 service. I would like to confirm whether my account has been configured and when I can start using the service.</p></div></div></div><div className="mt-4 rounded-xl border border-[#dfe6e2] p-4"><div className="flex gap-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#102019] text-[9px] font-black text-white">CS</div><div className="w-full"><div className="text-[9px] font-black">Support 01 <span className="font-normal text-[#89928e]">· Internal support reply</span></div><p className="mt-3 text-[10px] leading-5 text-[#39443f]">Thanks for contacting Arcus Strategy. We are checking your onboarding status and will update you shortly.</p></div></div></div></div>
        <div className="rounded-2xl border border-[#dfe6e2] bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><MessageSquare size={15} className="text-[#087f3f]"/><h2 className="text-sm font-black">Reply to customer</h2></div><textarea className="mt-4 min-h-32 w-full resize-none rounded-xl border border-[#d5ded9] bg-[#fbfcfb] p-4 text-[10px] outline-none focus:border-[#087f3f]" placeholder="Write a customer-facing reply..."/><div className="mt-3 flex flex-wrap justify-between gap-2"><button className="inline-flex items-center gap-2 rounded-lg border border-[#d5ded9] px-3 py-2 text-[9px] font-bold"><Paperclip size={13}/> Attach</button><div className="flex gap-2"><button className="rounded-lg border border-[#d5ded9] px-3 py-2 text-[9px] font-bold">Save internal note</button><button className="inline-flex items-center gap-2 rounded-lg bg-[#087f3f] px-4 py-2 text-[9px] font-black text-white"><Send size={13}/> Send reply</button></div></div></div>
      </section>
      <aside className="space-y-4">
        <div className="rounded-2xl border border-[#dfe6e2] bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><UserRound size={15} className="text-[#087f3f]"/><h2 className="text-sm font-black">Customer</h2></div><div className="mt-4 space-y-3 text-[9px]"><div><span className="block text-[7px] uppercase tracking-wide text-[#8a938f]">Name</span><strong>{ticket.customer}</strong></div><div><span className="block text-[7px] uppercase tracking-wide text-[#8a938f]">Email</span><span>{ticket.email}</span></div><div><span className="block text-[7px] uppercase tracking-wide text-[#8a938f]">Service</span><span>{ticket.service}</span></div><Link href="/admin/customers" className="inline-block pt-1 font-black text-[#087f3f]">View customer profile →</Link></div></div>
        <div className="rounded-2xl border border-[#dfe6e2] bg-white p-5 shadow-sm"><h2 className="text-sm font-black">Ticket controls</h2><div className="mt-4 space-y-3"><label className="block"><span className="mb-1 block text-[7px] font-bold uppercase tracking-wide text-[#8a938f]">Status</span><button className="flex w-full items-center justify-between rounded-lg border border-[#d5ded9] px-3 py-2 text-[9px] font-bold">{ticket.status}<ChevronDown size={13}/></button></label><label className="block"><span className="mb-1 block text-[7px] font-bold uppercase tracking-wide text-[#8a938f]">Priority</span><button className="flex w-full items-center justify-between rounded-lg border border-[#d5ded9] px-3 py-2 text-[9px] font-bold">{ticket.priority}<ChevronDown size={13}/></button></label><label className="block"><span className="mb-1 block text-[7px] font-bold uppercase tracking-wide text-[#8a938f]">Assigned</span><button className="flex w-full items-center justify-between rounded-lg border border-[#d5ded9] px-3 py-2 text-[9px] font-bold">{ticket.assigned}<ChevronDown size={13}/></button></label></div></div>
        <div className="rounded-2xl border border-[#e4e9e6] bg-[#f9fbfa] p-5"><div className="flex gap-2"><ShieldCheck size={15} className="mt-0.5 text-[#087f3f]"/><div><strong className="text-[9px] font-black">Support security boundary</strong><p className="mt-1 text-[8px] leading-4 text-[#707a75]">Sensitive financial administration and investor credential values are outside this workspace.</p></div></div></div>
      </aside>
    </div>
  </main>;
}
