import Link from 'next/link';
import { ArrowRight, CheckCircle2, Cable, ShieldCheck } from 'lucide-react';
import CustomerMenu from '../../../components/CustomerMenu';

const platforms = ['MT4', 'MT5', 'cTrader'];

export default function PineBridgePage() {
  return (
    <main className="min-h-screen bg-[#f7f9f8] text-[#101512]">
      <header className="sticky top-0 z-40 border-b border-[#e4e9e6] bg-white/95 backdrop-blur-xl">
        <div className="mx-auto flex min-h-[76px] max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-10">
          <Link href="/dashboard" className="flex items-center gap-3">
            <span className="grid h-10 w-10 place-items-center rounded-xl bg-[#087f3f] text-sm font-black text-white">A</span>
            <span><strong className="block text-[15px] tracking-[.16em]">ARCUS</strong><small className="block text-[8px] font-black tracking-[.35em] text-[#087f3f]">STRATEGY</small></span>
          </Link>
          <CustomerMenu />
        </div>
      </header>

      <section className="border-b border-[#e4e9e6] bg-white">
        <div className="mx-auto max-w-[1200px] px-5 py-14 sm:px-8 lg:px-10 lg:py-20">
          <span className="text-[10px] font-black tracking-[.22em] text-[#087f3f]">PINE BRIDGE</span>
          <div className="mt-5 flex max-w-5xl flex-col gap-8 lg:flex-row lg:items-end lg:justify-between">
            <div>
              <h1 className="text-4xl font-black tracking-[-.045em] sm:text-5xl lg:text-6xl">Take trades from TradingView to your trading platform.</h1>
              <p className="mt-6 max-w-3xl text-[15px] leading-7 text-[#68726e]">Pine Bridge is a service that allows users to automatically take trades from their TradingView setup on supported MT4, MT5 and cTrader environments. Connect your TradingView strategy workflow to the execution environment you choose.</p>
            </div>
            <a href="#use-pine-bridge" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-[#087f3f] px-6 py-3.5 text-[12px] font-black text-white">USE PINE BRIDGE <ArrowRight size={15} /></a>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-[1200px] px-5 py-12 sm:px-8 lg:px-10">
        <div className="grid gap-5 md:grid-cols-3">
          {platforms.map((platform) => (
            <div key={platform} className="rounded-2xl border border-[#dfe7e2] bg-white p-7 shadow-sm">
              <CheckCircle2 className="text-[#087f3f]" size={21} />
              <h2 className="mt-5 text-xl font-black">{platform}</h2>
              <p className="mt-3 text-[13px] leading-6 text-[#68726e]">Supported execution environment for TradingView-driven trade automation through Pine Bridge.</p>
            </div>
          ))}
        </div>
      </section>

      <section className="border-y border-[#e4e9e6] bg-white">
        <div className="mx-auto max-w-[1200px] px-5 py-12 sm:px-8 lg:px-10">
          <div className="grid gap-5 md:grid-cols-3">
            <div className="rounded-2xl bg-[#f7f9f8] p-7"><Cable className="text-[#087f3f]" /><h3 className="mt-4 font-black">TradingView to execution</h3><p className="mt-2 text-[13px] leading-6 text-[#68726e]">Move trading actions generated by your TradingView setup into a supported execution platform.</p></div>
            <div className="rounded-2xl bg-[#f7f9f8] p-7"><CheckCircle2 className="text-[#087f3f]" /><h3 className="mt-4 font-black">Multi-platform</h3><p className="mt-2 text-[13px] leading-6 text-[#68726e]">Designed for MT4, MT5 and cTrader workflows.</p></div>
            <div className="rounded-2xl bg-[#f7f9f8] p-7"><ShieldCheck className="text-[#087f3f]" /><h3 className="mt-4 font-black">Controlled setup</h3><p className="mt-2 text-[13px] leading-6 text-[#68726e]">You remain responsible for your TradingView configuration, execution settings and trading risk.</p></div>
          </div>
        </div>
      </section>

      <section id="use-pine-bridge" className="mx-auto max-w-[1200px] px-5 py-12 sm:px-8 lg:px-10">
        <div className="rounded-3xl bg-[#101512] p-8 text-white sm:p-11">
          <span className="text-[10px] font-black tracking-[.2em] text-[#8ed0a9]">PINE BRIDGE ACCESS</span>
          <h2 className="mt-3 text-3xl font-black">Ready to use Pine Bridge?</h2>
          <p className="mt-4 max-w-2xl text-[13px] leading-6 text-white/65">The Pine Bridge webapp will handle the connection and setup workflow. The external application link will be added when it is provided.</p>
          <span className="mt-7 inline-flex items-center gap-2 rounded-xl bg-white/10 px-5 py-3 text-[12px] font-black text-white/55">USE PINE BRIDGE <ArrowRight size={15} /></span>
        </div>
      </section>
    </main>
  );
}
