import Link from 'next/link';

const documents: Record<string,{title:string;summary:string;updated:string;sections:{heading:string;body:string}[]}> = {
  'terms-conditions': {
    title:'Terms & Conditions', summary:'The master agreement governing access to and use of Arcus Strategy products, services, website and customer account.', updated:'19 August 2026',
    sections:[
      {heading:'1. Acceptance of these Terms',body:'These Terms & Conditions form a legally binding agreement between you and Arcus Strategy in relation to your use of the Arcus Strategy website, customer account, software, educational material, trading technology, subscriptions and other services made available through the platform. By creating an account, accessing a service, purchasing a subscription, connecting a trading account, or otherwise using the platform, you confirm that you have read, understood and agreed to these Terms, the Privacy Policy, Cookie Policy, Risk Disclosure, Disclaimer and any product-specific terms incorporated by reference. If you do not agree, you must not use the relevant service. Where a product-specific agreement imposes a higher or more specific requirement, that requirement applies to the relevant product in addition to these Terms.'},
      {heading:'2. Definitions',body:'“Arcus Strategy”, “Arcus”, “we”, “us” and “our” refer to the Arcus Strategy service and its operators. “User”, “you” and “your” refer to the individual or entity using the platform. “Services” means any software, trading technology, copy trading, MAM, PAMM, TradingView, Prop Firm Assisted Trading, ServerLess Algotrading, educational, analytical or community service offered through the platform. “Broker” means a third-party broker, exchange, platform or liquidity provider. “Trading Account” means an account maintained with a broker or exchange. “Content” includes text, graphics, videos, indicators, algorithms, documentation, signals, software and other material. “Subscription” means a recurring or fixed-term paid entitlement. “Performance Data” means historical or current account statistics supplied by Arcus, a broker or a third-party reporting provider.'},
      {heading:'3. Eligibility and jurisdiction',body:'You must be legally capable of entering a contract in your jurisdiction and must comply with all laws applicable to you. You must not use Arcus Strategy where doing so would violate a law, sanctions regime, financial-services restriction, broker rule or contractual obligation applicable to you. Arcus may refuse access where a service is unavailable, unsuitable or restricted in a jurisdiction. You are responsible for determining whether you may lawfully use a particular product.'},
      {heading:'4. Account registration and security',body:'You must provide accurate information and keep it current. You are responsible for safeguarding passwords, authentication codes, recovery information and access devices. You must promptly notify Arcus of suspected compromise. You may not create accounts using false identities, disposable identities intended to evade controls, or another person’s information without authority. Arcus may require identity verification before enabling regulated, high-risk, payment or account-connection functionality. Account credentials must never be published in public areas of the platform.'},
      {heading:'5. User responsibilities',body:'You remain responsible for your trading decisions, account settings, broker relationship, capital, leverage, tax obligations and compliance with broker rules. You must review service documentation and test integrations before committing live capital. You must not rely on an alert, signal, risk score, performance figure, algorithm, AI output or educational statement as a promise of a particular result. You must independently assess suitability and risk.'},
      {heading:'6. Website and platform use',body:'The website is provided for lawful use. You may not interfere with its operation, probe or bypass security controls, introduce malicious code, scrape protected data, overload infrastructure, impersonate Arcus or another user, or attempt unauthorised access. Automated access is permitted only where expressly authorised. Arcus may rate-limit, block or investigate activity that threatens platform integrity.'},
      {heading:'7. Service availability',body:'Arcus aims to maintain reliable services but does not promise uninterrupted availability. Maintenance, upgrades, network failures, broker outages, exchange outages, cloud-provider incidents, security events and circumstances outside Arcus control may affect availability. A temporary outage does not create an automatic entitlement to compensation or additional trading time unless a specific written service commitment says otherwise.'},
      {heading:'8. Payments and subscriptions',body:'Prices, billing intervals and applicable taxes are presented at checkout or in the relevant service terms. You authorise the selected payment processor to charge the applicable amount when due. Subscriptions renew according to their stated cycle unless cancelled before renewal. Access may be suspended for failed, reversed or disputed payments. A successful payment does not by itself guarantee account activation where additional onboarding, KYC or eligibility checks are required.'},
      {heading:'9. Performance fees and trading charges',body:'Where a service expressly states that performance fees, profit shares, management charges, broker fees or other trading costs apply, those charges are additional to any subscription unless the service page states otherwise. Third-party broker, exchange, payment, data, network and execution charges are outside Arcus control. Performance figures should be assessed after considering applicable costs.'},
      {heading:'10. Copy Trading',body:'Copy trading permits eligible trading activity from a source strategy or account to be replicated to a connected account through supported infrastructure. Replication is not guaranteed to be identical. Differences in broker pricing, liquidity, execution speed, leverage, minimum trade size, symbol specification, account currency, position limits, slippage and connectivity can produce materially different results. The separate Copy Trading Terms form part of this agreement.'},
      {heading:'11. MAM and PAMM',body:'MAM and PAMM services involve allocation or management structures provided through third-party broker infrastructure or supported account arrangements. Allocation methods, minimum deposits, fees, risk parameters and withdrawal procedures vary by service. Users must read the applicable account terms and risk analysis before participating. No representation is made that an allocation will produce the same return as another account.'},
      {heading:'12. TradingView products',body:'TradingView indicators, strategies and webhook automation products are licensed digital products. Access may require account verification and may be limited to the subscription period. Users may not redistribute, resell, copy, reverse engineer, publish private scripts, extract protected logic or provide access to unauthorised persons. Webhook automation depends on TradingView and supported third-party automation services, each of which has its own terms and technical limitations.'},
      {heading:'13. Prop Firm Assisted Trading',body:'Prop Firm Assisted Trading may involve challenge or funded-account workflows, appointment booking, account credentials and specific trading rules. Eligibility may require completed KYC. Users must comply with the applicable prop firm rules and Arcus onboarding requirements. Passing a challenge, receiving a funded account or obtaining a payout is never guaranteed. The separate Prop Firm A.T Terms govern service-specific matters.'},
      {heading:'14. ServerLess Algotrading',body:'ServerLess Algotrading provides automated execution infrastructure or supported strategy connectivity without requiring the user to maintain a traditional local trading server. A paid subscription may be required before onboarding. After successful payment, users may be required to submit trading-account details securely. Automation remains subject to broker connectivity, platform availability, strategy conditions, risk controls and execution quality. The separate ServerLess Algotrading Terms apply.'},
      {heading:'15. Intellectual property',body:'Arcus and its licensors retain all rights in Arcus Strategy branding, software, algorithms, indicators, trading robots, source code, designs, documentation, articles, videos, images, databases and other protected material except third-party material identified as such. Your subscription gives you only the limited access or licence expressly granted for the purchased product. No ownership is transferred.'},
      {heading:'16. User content and conduct',body:'You retain rights in lawful content you submit, but you grant Arcus the limited rights necessary to host, process, display and moderate it for the service. You must not upload unlawful, defamatory, fraudulent, infringing, malicious or abusive material. Community features must not be used for scams, solicitation, market manipulation, harassment or distribution of unauthorised investment advice.'},
      {heading:'17. Third-party services',body:'Arcus may integrate with brokers, exchanges, TradingView, payment processors, cloud providers, analytics providers, identity-verification providers, communication services and automation platforms. Those providers operate independently and may impose additional terms. Arcus is not responsible for third-party outages, policies, pricing, execution, security incidents outside Arcus control or changes to their APIs.'},
      {heading:'18. Suspension and termination',body:'Arcus may suspend or terminate access where there is a security concern, suspected fraud, non-payment, KYC failure, breach of these Terms, unlawful use, abuse of an integration, chargeback activity or a material risk to users or the platform. Where appropriate, Arcus may provide notice and an opportunity to remedy. Termination does not remove obligations that by their nature survive termination, including payment obligations, intellectual-property restrictions, confidentiality, disclaimers, limitation of liability and dispute provisions.'},
      {heading:'19. Disclaimers and limitation of liability',body:'To the maximum extent permitted by applicable law, Arcus provides trading technology, information and educational material without guaranteeing uninterrupted service, accuracy of every data point, profitability or suitability for a particular user. Nothing on the platform overrides the separate Risk Disclosure or Disclaimer. Arcus is not liable for losses arising from market movements, broker or exchange actions, slippage, outages, rejected orders, leverage, user settings, unauthorised access caused by the user, third-party failures or circumstances beyond reasonable control. Nothing in these Terms excludes liability that cannot lawfully be excluded.'},
      {heading:'20. Indemnification',body:'To the extent permitted by law, you agree to indemnify and hold harmless Arcus and its personnel from claims, losses, liabilities and reasonable costs arising from your unlawful use of the platform, breach of these Terms, infringement of third-party rights, misuse of integrations, fraud or intentional misconduct.'},
      {heading:'21. Force majeure',body:'Arcus is not responsible for delay or failure caused by events beyond reasonable control, including natural disasters, war, civil unrest, terrorism, government action, sanctions, infrastructure failure, telecommunications outages, cyber incidents, widespread cloud failures, broker or exchange closures, or other extraordinary events.'},
      {heading:'22. Governing law and disputes',body:'These Terms are intended to be interpreted under the laws applicable to the legal entity operating the relevant Arcus service and the mandatory consumer laws applicable to the user. Where legally permitted, disputes should first be submitted through the complaint process so the parties have a reasonable opportunity to resolve them. If a dispute cannot be resolved, it may be referred to a competent court or, where a valid arbitration agreement applies, to arbitration in the forum specified by that agreement. Mandatory rights of consumers are not excluded.'},
      {heading:'23. Changes to the Terms',body:'Arcus may update these Terms to reflect service changes, legal requirements, security improvements or operational changes. Material changes will be communicated through the website, account interface or another reasonable method. Continued use after the effective date constitutes acceptance to the extent permitted by law. If you do not accept a material change, you should stop using the affected service and follow the applicable cancellation process.'},
      {heading:'24. Contact and notices',body:'Legal and service notices may be delivered through the Arcus website, customer account, registered email address or other contact channel associated with your account. You are responsible for keeping contact information current. Product pages may contain additional instructions for support and onboarding. The official Arcus Strategy website and authenticated customer account are the authoritative channels for service notices and credentials.'}
    ]
  },
  'privacy-policy': {title:'Privacy Policy',summary:'How Arcus Strategy handles personal information across the website, customer account and connected services.',updated:'19 August 2026',sections:[
    {heading:'1. Scope',body:'This Privacy Policy explains how Arcus Strategy collects, uses, stores, shares and protects personal information when you browse the website, register, subscribe, complete KYC, use customer features, communicate with support, participate in communities or connect a trading service. It should be read with the Cookie Policy and applicable product terms.'},
    {heading:'2. Information collected',body:'We may collect identity and contact information such as name, email address, telephone number, country, account identifiers and KYC information where verification is required. We may collect service information including subscriptions, payment status, connected broker information, account metadata, support messages, community activity, preferences and consent records. We may collect technical information such as IP address, browser type, device information, operating system, approximate location derived from IP, logs and security events.'},
    {heading:'3. KYC and AML data',body:'Where a service requires verification, we may process identity documents, verification results, date of birth, address information, source-of-funds information and related compliance records. Such processing is used for identity verification, fraud prevention, sanctions screening, risk management and legal compliance. Sensitive documents are handled through authorised providers or secured systems where available.'},
    {heading:'4. Cookies and analytics',body:'We use necessary cookies and similar technologies to provide authentication, security and core functionality. With appropriate consent where required, functional, analytics and marketing technologies may help us understand website usage, remember preferences and improve communications. The separate Cookie Policy explains these categories and available controls.'},
    {heading:'5. Telegram Mini App data',body:'If you access an Arcus experience through a Telegram Mini App, Telegram may provide information required for the Mini App to operate, such as Telegram user identifiers, display information and technical context. We use that information only for the relevant service, authentication, support, security and lawful operational purposes. Telegram independently controls its own platform and privacy practices.'},
    {heading:'6. Firebase and cloud infrastructure',body:'Arcus may use Firebase and related Google Cloud services for authentication, databases, hosting, application functionality, security and operational logging. Information processed through these services is subject to applicable contractual and security controls. We configure access according to the needs of the application and do not treat a third-party cloud provider as permission to use data for unrelated purposes.'},
    {heading:'7. Payment processors',body:'Payments may be processed by third-party payment providers. We generally receive transaction identifiers, payment status and limited billing information needed to reconcile a purchase rather than storing full payment-card credentials. The payment provider may process payment information under its own privacy terms and security obligations.'},
    {heading:'8. How information is used',body:'Information may be used to create and secure accounts, deliver subscriptions, verify identity, process payments, provide customer support, operate integrations, prevent fraud, enforce terms, analyse service reliability, improve products, send requested or consented marketing communications and comply with legal obligations. We do not use personal data for a materially incompatible purpose without a lawful basis.'},
    {heading:'9. Marketing communications',body:'Where permitted, we may send product updates, educational material, service announcements and marketing communications. You can unsubscribe from marketing communications at any time. Transactional and security messages may continue where necessary to operate your account.'},
    {heading:'10. Sharing and international transfers',body:'Information may be shared with service providers that help us operate hosting, authentication, KYC, payments, analytics, email, customer support, security and integrations. We may disclose information where required by law, court order, regulatory request or to protect users and platform security. Service providers may operate in countries other than your own. Where applicable, we use appropriate safeguards for international transfers.'},
    {heading:'11. Retention',body:'We retain information for as long as reasonably necessary for the purposes described in this Policy, including account administration, contractual obligations, fraud prevention, dispute resolution, tax and accounting requirements and legal compliance. Retention periods vary by data type. When information is no longer required, it is deleted, anonymised or securely disposed of where practicable.'},
    {heading:'12. GDPR rights',body:'Where the GDPR applies, you may have rights including access, rectification, erasure, restriction, objection, portability and withdrawal of consent, subject to legal exceptions. You may also have the right to complain to the relevant supervisory authority. Requests can be made through the official Arcus support or legal contact channel associated with the website.'},
    {heading:'13. CCPA and similar rights',body:'Where applicable, California residents may have rights concerning access, correction, deletion, portability and certain disclosures about personal information. Arcus does not sell personal information in the ordinary meaning of a consumer data sale. Where applicable law provides additional rights, Arcus will process valid requests in accordance with that law.'},
    {heading:'14. Security',body:'We use reasonable administrative, technical and organisational safeguards appropriate to the nature of information processed. These may include authentication controls, least-privilege access, encrypted transport, monitoring, backups and security review. No internet service can guarantee absolute security. Users must protect their credentials and report suspected compromise promptly.'},
    {heading:'15. Children',body:'Arcus services are intended for persons legally able to use the relevant financial or technology service. We do not knowingly collect personal information from children in violation of applicable law. If you believe a child has provided information unlawfully, contact Arcus so the matter can be investigated.'},
    {heading:'16. Contact',body:'Privacy requests should identify the account email and describe the request sufficiently for Arcus to verify the requester and locate the relevant information. We may request additional information to prevent unauthorised disclosure. We will respond within the period required by applicable law.'}
  ]},
  'cookie-policy': {title:'Cookie Policy',summary:'A practical explanation of cookies and similar technologies used by the Arcus Strategy website.',updated:'19 August 2026',sections:[
    {heading:'1. Necessary cookies',body:'Necessary cookies support authentication, session management, security, load balancing and core website functionality. The site may not operate correctly if these technologies are disabled. They are generally used because they are necessary to provide a service requested by the user.'},
    {heading:'2. Functional cookies',body:'Functional technologies remember preferences and interface choices to improve usability. They may include language, interface state and other settings that are not strictly necessary for the basic delivery of the website.'},
    {heading:'3. Analytics cookies',body:'Analytics technologies help Arcus understand how pages are used, which features are useful and where technical problems occur. Analytics information may include page views, device information, approximate location and interaction events. Where required, analytics technologies are enabled only after the relevant consent.'},
    {heading:'4. Marketing cookies',body:'Marketing technologies may help measure campaigns, limit repetitive advertising and understand interactions with promotional content. These technologies are used only where permitted by applicable law and consent requirements.'},
    {heading:'5. Third-party cookies',body:'Integrated services such as analytics, video, payment, authentication or social platforms may place their own cookies or similar technologies. Those technologies are controlled by the relevant provider and are subject to its policies.'},
    {heading:'6. Managing cookies',body:'You can control cookies through your browser settings and, where provided, Arcus consent controls. Blocking necessary cookies can prevent login, checkout or other core functionality. You can also delete existing cookies through browser settings. Cookie controls may vary by browser and device.'}
  ]},
  'risk-disclosure': {title:'Risk Disclosure',summary:'A dedicated disclosure of the financial, technical and operational risks associated with Arcus Strategy services.',updated:'19 August 2026',sections:[
    {heading:'1. General risk',body:'Trading financial instruments can result in rapid and substantial loss of capital. You may lose some or all of the capital committed to a trading account. Leverage can magnify both gains and losses. A risk score, historical statistic or strategy label does not change the underlying market risk.'},
    {heading:'2. Forex and CFD risk',body:'Foreign exchange and CFDs are affected by leverage, spreads, liquidity, interest-rate expectations, economic events and broker execution. Positions can move against you quickly and may be closed automatically when margin requirements are breached.'},
    {heading:'3. Crypto risk',body:'Cryptocurrency markets can experience extreme volatility, fragmented liquidity, exchange outages, technological failures, custody risks, market manipulation and regulatory intervention. Prices can change substantially outside normal trading hours.'},
    {heading:'4. Synthetic index risk', body:"Synthetic indices and similar derivative products are generated or quoted by their respective providers and can behave differently from traditional markets. Users must understand the provider's methodology, trading hours, volatility and contract rules before trading."},
    {heading:'5. Copy trading risk',body:'Copied orders may not match the source order because of latency, price differences, account restrictions, position sizing, minimum volumes, slippage, rejected orders, partial fills and broker-specific conditions. Copying a profitable source account does not guarantee profitable results in the receiving account.'},
    {heading:'6. MAM and PAMM risk', body:"Allocation structures may concentrate exposure across multiple positions or investors. Different allocation methods, fees, execution conditions and withdrawal constraints can affect outcomes. A manager's historical record is not a forecast."},
    {heading:'7. ServerLess Algotrading risk',body:'Automated execution can continue without manual intervention and may therefore place trades while the user is unavailable. Strategy logic, connectivity, account permissions, platform state and risk parameters can all affect execution. Automation does not remove market risk.'},
    {heading:'8. Indicator and TradingView strategy risk',body:'Indicators and strategies are analytical tools. Signals can be false, delayed, contradictory or invalidated by new market information. TradingView alerts and webhook systems depend on external infrastructure and may not execute at the price, time or quantity expected.'},
    {heading:'9. Algorithmic and AI decision risk',body:'Algorithms and AI systems may respond incorrectly to unusual market regimes, incomplete data, model drift, correlations that break down or technical faults. An AI-generated recommendation is not a guarantee of accuracy and should not be treated as a substitute for independent judgement.'},
    {heading:'10. Volatility and gap risk',body:'Prices can move sharply during news, market openings, economic releases and other events. Gaps may cause orders to execute materially away from intended levels. Stop-loss orders may not guarantee the exact loss amount during fast markets.'},
    {heading:'11. Weekend and liquidity risk',body:'Markets may reopen after periods of limited liquidity with significant price changes. Crypto markets may trade continuously while other markets close, creating different risk conditions across connected strategies.'},
    {heading:'12. Leverage risk',body:'Leverage permits a larger position than the cash deposited but increases the sensitivity of equity to price movements. Small adverse price movements can create large percentage losses and may trigger liquidation or margin calls.'},
    {heading:'13. Execution, slippage and partial fills',body:'Execution prices can differ from signal prices because of market movement, spreads and liquidity. Orders may be rejected, delayed, partially filled or filled at multiple prices. These effects can materially alter a strategy's realised performance.'},
    {heading:'14. Internet, platform, broker and exchange failure',body:'Internet interruptions, device failure, broker downtime, exchange outages, API changes, authentication errors, cloud incidents and platform maintenance can prevent orders from being sent, modified or closed. Users must not assume continuous technical availability.'},
    {heading:'15. Government and regulatory action',body:'Governments, regulators, brokers and exchanges may impose restrictions, suspend products, change leverage limits, freeze accounts, alter market access or introduce new requirements. Such actions can affect strategy availability and account value.'},
    {heading:'16. Tax and loss of capital',body:'You are responsible for determining and paying taxes arising from your trading activity. Trading losses can reduce capital available for living expenses or other obligations. Only capital that you can afford to lose should be exposed to speculative trading.'},
    {heading:'17. Past performance',body:'Past performance, backtests, simulated results, historical drawdowns, win rates, recovery factors and risk scores are historical observations. They do not guarantee future results and may not reflect costs, slippage, liquidity or future market regimes.'}
  ]},
  'disclaimer': {title:'Disclaimer',summary:'Important limitations on the nature and use of Arcus Strategy information and technology.',updated:'19 August 2026',sections:[
    {heading:'No financial advice',body:'Arcus Strategy information, signals, indicators, algorithms and educational material are provided for informational and technological purposes. They are not personalised financial advice or a recommendation to buy or sell a financial instrument.'},
    {heading:'No investment advice or fiduciary relationship',body:'Use of the platform does not create a fiduciary, advisory, portfolio-management or client-adviser relationship unless a separate written agreement expressly creates one. Users make their own investment decisions.'},
    {heading:'Educational content',body:'Education content is provided through the Education area and individual courses. Courses may contain articles, videos and documents explaining trading technology, risk, strategies and platform functionality. Completion of a course does not establish competence or guarantee trading success.'},
    {heading:'No profit guarantee',body:'No Arcus service guarantees profit, a particular return, account survival, funded status, payout or trading outcome.'},
    {heading:'Third-party content and links',body:'The platform may reference brokers, exchanges, TradingView, reporting services and other third parties. Their content, availability, pricing, execution and policies are outside Arcus control. External links are provided for convenience and do not constitute endorsement.'},
    {heading:'Website availability and errors',body:'Arcus works to keep information accurate and services available, but pages may contain errors, omissions, stale information or technical interruptions. Users should verify important information before acting.'},
    {heading:'No warranty',body:'To the maximum extent permitted by law, information and technology are provided without warranties of uninterrupted availability, merchantability, fitness for a particular purpose or guaranteed accuracy. Mandatory statutory rights remain unaffected.'}
  ]},
  'regulatory-status': {title:'Regulatory Status',summary:'A focused statement about the nature, scope and limits of Arcus Strategy regulatory position.',updated:'19 August 2026',sections:[
    {heading:'What Arcus Strategy is',body:'Arcus Strategy is a technology and service platform focused on algorithmic trading technology, trading automation, market-analysis tools, educational resources, copy-trading infrastructure and related customer services. Individual products may rely on third-party brokers, exchanges, platforms or technology providers.'},
    {heading:'What Arcus Strategy is not',body:'Unless expressly stated in a separate written agreement and applicable licence, Arcus Strategy should not be understood as a bank, deposit-taking institution, exchange, broker, custodian, or universal investment adviser. Availability of a trading technology product does not itself confer regulatory authorisation.'},
    {heading:'Licensing',body:'Regulatory permissions are jurisdiction-specific and product-specific. Arcus does not represent that every product is authorised for every jurisdiction or every customer. Users must rely only on regulatory statements published through the official Arcus Strategy legal and service materials and must independently verify any licensing requirement that applies to them.'},
    {heading:'Jurisdiction and limitations',body:'A service may be restricted, modified or unavailable in jurisdictions where local law prevents or limits its operation. Nothing on the website should be interpreted as a solicitation to persons for whom the service is prohibited.'}
  ]},
  'refund-policy': {title:'Refund & Cancellation Policy',summary:'Rules governing cancellations, refund requests, chargebacks and access after cancellation.',updated:'19 August 2026',sections:[
    {heading:'Subscriptions',body:'Subscription cancellation stops future renewal when completed before the next billing event. Unless a service page or mandatory law provides a refund right, cancellation does not automatically create a refund for an already-started billing period because access to digital services may already have been provided.'},
    {heading:'TradingView products',body:'Because TradingView indicators, strategies and related digital access can be delivered immediately after purchase, refunds are subject to the product's stated refund window and applicable consumer law. Access may be revoked when a refund is approved.'},
    {heading:'Prop Firm services',body:'Prop Firm Assisted Trading payments may involve third-party challenge fees, appointments or digital onboarding. Refund eligibility depends on the specific service purchased, whether third-party fees have already been incurred, and mandatory consumer rights. Passing, failing or voluntarily abandoning a challenge does not automatically create a refund entitlement.'},
    {heading:'Digital products',body:'Digital products are generally non-refundable after delivery where lawful, unless a stated refund window or mandatory law provides otherwise. Technical problems should first be reported so Arcus can attempt a reasonable remedy.'},
    {heading:'Chargebacks and fraud',body:'Unauthorised or fraudulent transactions should be reported promptly. A payment dispute initiated without first allowing Arcus to investigate may result in account restriction while the dispute is reviewed. Fraudulent use, payment reversal abuse or deliberate misrepresentation may result in termination.'},
    {heading:'How refunds are processed',body:'Approved refunds are normally returned through the original payment method where the processor supports it. Processing times depend on the payment provider and banking network. Refunds may be reduced by non-recoverable third-party charges only where lawful and clearly disclosed.'}
  ]},
  'subscription-terms': {title:'Subscription Terms',summary:'Rules for recurring services including Prop Firm Assisted Trading and ServerLess Algotrading.',updated:'19 August 2026',sections:[
    {heading:'Plans',body:'Arcus may offer monthly, quarterly and yearly plans. The applicable price, billing interval, included features and renewal conditions are shown at purchase. A plan gives access only to the service level purchased.'},
    {heading:'Renewals',body:'Unless cancelled before renewal, recurring subscriptions renew for the same billing period. Renewal reminders may be provided where required or as a customer convenience, but the absence of a reminder does not necessarily cancel an otherwise valid renewal.'},
    {heading:'Expiry and access',body:'Fixed-term subscriptions expire at the end of their paid period. Recurring subscriptions remain active until cancellation, non-payment, suspension or termination. Expiry may disable strategy access, onboarding tools, dashboards and integrations associated with the service.'},
    {heading:'Non-payment',body:'Failed or reversed payments may result in a grace period where available, followed by suspension or access removal. Restoring access may require payment of outstanding amounts or a new subscription.'},
    {heading:'Onboarding and credentials',body:'For services requiring account credentials, successful payment may unlock an onboarding workflow. Users must submit requested information securely and accurately. A “Submit your details” reminder may remain visible in the authenticated home area until required onboarding information has been received.'},
    {heading:'Cancellation',body:'Users may cancel recurring renewal using the available account or support process. Cancellation generally preserves access through the paid period unless the service terms state otherwise. Refunds are governed by the Refund & Cancellation Policy.'}
  ]},
  'copy-trading-terms': {title:'Copy Trading Terms',summary:'Specific terms for trade replication, execution differences, fees and risk acknowledgement.',updated:'19 August 2026',sections:[
    {heading:'How copying works',body:'A copy-trading system receives eligible trading instructions from a source strategy and attempts to reproduce them on a connected account. The system may apply account-specific sizing or risk rules. Copying is an execution process, not a guarantee that the receiving account will match the source.'},
    {heading:'Execution delays and slippage',body:'Orders can be delayed by network latency, broker processing, liquidity or system load. Prices may move between signal generation and execution. Slippage can improve or worsen the result. Stop-loss and take-profit levels can also be affected during fast markets.'},
    {heading:'Different brokers',body:'Two brokers can quote different prices, spreads, symbols, contract sizes and trading hours. A source trade may therefore execute differently or may be unavailable on the receiving broker.'},
    {heading:'Partial fills and rejected orders',body:'Orders may be partially filled, rejected, resized or closed differently because of account restrictions, minimum volumes, margin, liquidity or broker rules. Users should monitor connected accounts and not assume every source trade is replicated.'},
    {heading:'Minimum capital and fees',body:'Each strategy may specify a minimum capital level. Users must also maintain sufficient margin for the chosen risk settings. Performance fees, subscriptions and broker costs apply where disclosed.'},
    {heading:'Stopping copying',body:'Users may stop copying through the relevant platform or account control. Stopping future copying does not automatically close existing positions unless the platform setting expressly provides for that behaviour.'},
    {heading:'Risk acknowledgement',body:'By enabling copy trading, the user accepts that a source strategy can lose money and that copying can magnify, reduce or otherwise alter the source outcome. Historical performance does not guarantee future results.'}
  ]},
  'serverless-algotrading-terms': {title:'ServerLess Algotrading Terms',summary:'Terms governing Arcus cloud-based automated trading connectivity and onboarding.',updated:'19 August 2026',sections:[
    {heading:'How it works',body:'ServerLess Algotrading uses hosted technology to support automated strategy execution or connectivity without requiring the customer to maintain a conventional local trading server. The exact execution architecture depends on the supported broker and product.'},
    {heading:'Subscription renewal',body:'Access is provided for the purchased subscription period and renews according to the Subscription Terms unless cancelled before renewal. Failed payment may suspend automation.'},
    {heading:'Account onboarding after payment',body:'After successful payment, users may be required to submit broker, platform and risk information through the secure onboarding flow. Automation should not be activated until required information has been reviewed and the user has confirmed the intended account.'},
    {heading:'No guarantees',body:'Hosted automation does not guarantee trade execution, profitability, uptime, or identical results across accounts. Market and infrastructure risks remain.'},
    {heading:'Risk controls',body:'Users are responsible for reviewing risk settings, account leverage, strategy permissions and trading symbols. Arcus may implement protective limits where appropriate, but users remain responsible for monitoring their account.'},
    {heading:'Security and credential handling',body:'Trading credentials must be submitted only through official Arcus interfaces or approved connection methods. Users must never post passwords in community chats or send credentials to unknown persons claiming to represent Arcus.'}
  ]},
  'tradingview-products-terms': {title:'TradingView Products Terms',summary:'Terms for Arcus TradingView indicators, strategies, alerts and webhook automation.',updated:'19 August 2026',sections:[
    {heading:'Indicators',body:'Arcus indicators are licensed analytical tools intended for use within the supported TradingView environment. Signal generation is not a promise of future market performance.'},
    {heading:'Strategies and webhooks',body:'TradingView strategies may generate alerts that can be delivered to supported automation platforms. Webhook execution depends on TradingView alert configuration, third-party endpoints, connectivity and destination platform behaviour.'},
    {heading:'Subscription and verification',body:'Access may require an active subscription and verification of the authorised TradingView username or account. Access is personal to the authorised user unless a written enterprise licence states otherwise.'},
    {heading:'Revocation',body:'Arcus may revoke access for expired subscriptions, credential sharing, redistribution, abuse, reverse engineering, unauthorised commercial use or other material breach. Revocation does not waive accrued payment or legal obligations.'},
    {heading:'License restrictions',body:'Users may view and use the product for the authorised purpose but may not copy protected logic, resell access, publish private scripts, extract source code, bypass access controls or provide access to unlicensed users.'},
    {heading:'No redistribution',body:'Sharing scripts, credentials, private links, webhook secrets or paid access outside the authorised account is prohibited. Users are responsible for keeping webhook secrets confidential.'}
  ]},
  'prop-firm-at-terms': {title:'Prop Firm A.T Terms',summary:'Terms for challenge accounts, funded-account assistance, appointments and account onboarding.',updated:'19 August 2026',sections:[
    {heading:'Challenge accounts',body:'Prop Firm Assisted Trading may support users through challenge-account workflows. Challenge rules are determined by the applicable prop firm and may include daily loss limits, maximum drawdown, trading restrictions, prohibited strategies and evaluation periods. Arcus does not guarantee a pass.'},
    {heading:'Funded accounts',body:'A funded-account status is controlled by the relevant prop firm. Users must comply with the firm's rules after funding and understand that the firm may terminate or restrict an account for rule violations.'},
    {heading:'Appointment booking',body:'Where onboarding or trading assistance requires an appointment, users must provide accurate contact information and attend the scheduled session. Missed appointments may be subject to the service's stated rescheduling rules.'},
    {heading:'Account credentials and confidentiality',body:'Credentials are confidential. Users must not disclose them to unauthorised persons. Where Arcus receives credentials solely to provide an authorised service, access is limited to the service purpose and must be handled through approved channels.'},
    {heading:'Trading rules',body:'The applicable prop firm's rules take priority over any general strategy description. Users must not request or instruct Arcus to violate a prop firm's restrictions.'},
    {heading:'Payment, refunds and termination',body:'Payments are governed by the checkout terms and Refund & Cancellation Policy. Fraud, credential abuse, rule evasion or material breach may result in termination. Third-party prop firm fees may have separate refund rules.'}
  ]},
  'aml-kyc-policy': {title:'AML & KYC Policy',summary:'Identity verification and financial-crime prevention controls applied to eligible Arcus services.',updated:'19 August 2026',sections:[
    {heading:'Identity verification',body:'Arcus may require identity verification before enabling certain services, payment features, account connections or high-risk activities. Verification information must be accurate, current and belong to the person requesting access.'},
    {heading:'Fraud prevention',body:'We may use technical, transactional and identity signals to detect account takeover, payment fraud, synthetic identities, credential abuse and other suspicious activity. Accounts may be restricted while a review is conducted.'},
    {heading:'Sanctions and restricted countries',body:'Arcus may screen users and transactions against applicable sanctions and restricted-party information. Services may be unavailable in jurisdictions or to persons where applicable law prohibits access.'},
    {heading:'Suspicious transactions',body:'Transactions or account activity that appear inconsistent with the service, involve unusual payment behaviour, identity discrepancies, fraud indicators or other financial-crime concerns may be reviewed, delayed, rejected or reported where legally required.'},
    {heading:'Source of funds',body:'For appropriate services or risk circumstances, Arcus may request information reasonably necessary to understand the source of funds. Users must not use Arcus services to launder proceeds, evade sanctions or conceal beneficial ownership.'},
    {heading:'Records and cooperation',body:'Compliance records may be retained for the period required by applicable law. Arcus may cooperate with lawful requests from competent authorities. We may be unable to disclose details of a compliance investigation where doing so would compromise legal or security obligations.'}
  ]},
  'acceptable-use-policy': {title:'Acceptable Use Policy',summary:'Rules governing lawful, secure and responsible use of Arcus Strategy systems.',updated:'19 August 2026',sections:[
    {heading:'Prohibited conduct',body:'Users must not use Arcus for spam, scams, phishing, fraud, money laundering, market manipulation, impersonation, harassment, unlawful solicitation or other illegal activity. Users must not misrepresent Arcus products or claim guaranteed returns.'},
    {heading:'Reverse engineering',body:'Unless mandatory law expressly permits it, users must not reverse engineer, decompile, disassemble, extract protected algorithms, bypass access controls or attempt to reconstruct proprietary source code.'},
    {heading:'Automation abuse and scraping',body:'Unauthorised bots, scraping, bulk extraction, credential stuffing, denial-of-service activity and automated requests that interfere with platform performance are prohibited.'},
    {heading:'Reselling and access sharing',body:'Paid access may not be resold, sublicensed or shared outside the authorised licence. Users must not create public services that reproduce Arcus paid functionality without permission.'},
    {heading:'Impersonation',body:'Users must not impersonate Arcus, its employees, brokers, administrators or other users, nor create deceptive pages or communications that appear official.'},
    {heading:'Enforcement',body:'Arcus may investigate suspected violations, preserve evidence, restrict access, remove content, suspend integrations or terminate accounts. Where appropriate, serious incidents may be referred to relevant authorities.'}
  ]},
  'intellectual-property': {title:'Intellectual Property Policy',summary:'Protection of Arcus Strategy technology, content, branding and proprietary systems.',updated:'19 August 2026',sections:[
    {heading:'Protected assets',body:'Arcus Strategy® branding, names, logos, trading algorithms, indicators, trading robots, source code, application code, AI systems, databases, website content, articles, documents, videos, images, designs and other original materials are protected by applicable intellectual-property laws and contractual rights.'},
    {heading:'User licence',body:'Where a product is sold or subscribed to, the user receives only the limited licence necessary to use that product for its authorised purpose and duration. No ownership of source code, algorithms or underlying intellectual property is transferred.'},
    {heading:'Restrictions',body:'Unauthorised copying, redistribution, public display of protected private material, resale, extraction, modification for competing commercial use, reverse engineering and credential sharing are prohibited except where a written licence or mandatory law permits otherwise.'},
    {heading:'Third-party material',body:'Some content may belong to third parties and is used under licence or applicable permission. Third-party trademarks remain the property of their respective owners.'},
    {heading:'Infringement notices',body:'Rights holders who believe material on the platform infringes their rights should provide sufficient information to identify the work, explain the claimed right, identify the relevant material and provide reliable contact information. Arcus may investigate and take appropriate action.'}
  ]},
  'complaint-handling': {title:'Complaint Handling Policy',summary:'A structured process for submitting, investigating and resolving customer complaints.',updated:'19 August 2026',sections:[
    {heading:'Making a complaint',body:'A complaint should describe the service involved, relevant dates, the issue experienced, supporting evidence and the resolution requested. Complaints should be submitted through the official Arcus support or legal contact channel so they can be logged and tracked.'},
    {heading:'Acknowledgement and investigation',body:'Arcus aims to acknowledge complaints promptly and investigate proportionately. The investigation may include account records, payment records, technical logs, communications, third-party information and relevant service terms.'},
    {heading:'Response times',body:'Simple complaints should normally receive an initial response within a reasonable support period. Complex complaints may require additional time, particularly where third-party brokers, payment providers, KYC providers or technical systems must be consulted. Where additional time is needed, the user should be informed.'},
    {heading:'Escalation',body:'If a customer is dissatisfied with an initial response, the complaint may be escalated through the legal or management channel identified by Arcus. Escalation should identify why the initial response is disputed and provide any new evidence.'},
    {heading:'Resolution',body:'Possible resolutions include correction of a technical issue, clarification, account remediation, service credit where contractually appropriate, refund where the Refund Policy permits it, or a reasoned explanation why no further action is available. Complaints do not suspend payment obligations unless Arcus expressly agrees or applicable law requires it.'}
  ]},
  'contact-legal-notices': {title:'Contact & Legal Notices',summary:'Official channels for legal notices, privacy requests, complaints and service communications.',updated:'19 August 2026',sections:[
    {heading:'Official communication channels',body:'Users should use the contact channels published within the authenticated Arcus Strategy website and official Arcus Strategy website for support, legal notices, privacy requests, KYC matters and complaints. Users should never rely on credentials or payment instructions received from unofficial social-media accounts or unknown third parties.'},
    {heading:'Registered company information',body:'Arcus Strategy presents itself to customers through the Arcus Strategy brand and service platform. Legal entity name, company number and registered office should be taken only from the current official corporate registration and legal notice published by the operator. The platform does not invent or infer corporate registration details from a brand name.'},
    {heading:'Business and response hours',body:'Support availability may vary by service and operating region. Automated systems may receive requests outside normal support hours. Response times depend on the nature and urgency of the request, with security, payment and compliance matters prioritised appropriately.'},
    {heading:'Legal notices',body:'Formal legal notices should clearly identify the sender, recipient, subject matter and legal basis for the request. Arcus may require identity verification before discussing account-specific information or releasing personal data.'}
  ]}
};

export default async function LegalDocumentPage({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; const doc=documents[slug];
  if(!doc) return <main className="min-h-screen grid place-items-center bg-[#f7f9f8] p-6"><div className="text-center"><h1 className="text-3xl font-black">Legal document not found</h1><Link href="/legal" className="mt-4 inline-block font-bold text-[#087f3f]">← Legal centre</Link></div></main>;
  return <main className="min-h-screen bg-[#f7f9f8] text-[#101512]"><header className="sticky top-0 z-30 border-b border-[#e1e7e3] bg-white/95 backdrop-blur"><div className="mx-auto flex min-h-[72px] max-w-[1280px] items-center justify-between px-5 sm:px-8"><Link href="/legal" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#087f3f] text-sm font-black text-white">A</span><span><strong className="block text-[14px] tracking-[.16em]">ARCUS</strong><small className="block text-[8px] font-black tracking-[.3em] text-[#087f3f]">STRATEGY</small></span></Link><Link href="/legal" className="text-[12px] font-bold text-[#087f3f]">Legal Centre</Link></div></header><section className="mx-auto max-w-[1000px] px-5 py-12 sm:px-8 lg:py-16"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">ARCUS STRATEGY LEGAL</span><h1 className="mt-3 text-4xl font-black tracking-[-.045em] sm:text-5xl">{doc.title}</h1><p className="mt-5 max-w-3xl text-[15px] leading-8 text-[#68726e]">{doc.summary}</p><div className="mt-5 text-[10px] font-bold uppercase tracking-[.14em] text-[#8b9690]">Effective / reviewed: {doc.updated}</div><article className="mt-10 rounded-3xl border border-[#dfe7e2] bg-white p-6 shadow-sm sm:p-10">{doc.sections.map((s)=><section key={s.heading} className="border-b border-[#edf0ee] py-7 first:pt-0 last:border-b-0"><h2 className="text-lg font-black tracking-[-.02em]">{s.heading}</h2><p className="mt-3 text-[13px] leading-7 text-[#4e5b55]">{s.body}</p></section>)}</article><div className="mt-8 rounded-2xl border border-[#dfe7e2] bg-[#f0f7f2] p-5 text-[11px] leading-6 text-[#52615a]">These documents are drafted as the contractual and disclosure framework for the Arcus Strategy platform. Applicable mandatory law always prevails where it cannot lawfully be excluded or limited.</div></section></main>;
}
