import Link from 'next/link';
import { ArrowLeft, BarChart3, CheckCircle2, CircleHelp, ExternalLink, ShieldAlert } from 'lucide-react';
import CustomerMenu from '../../../../../components/CustomerMenu';
import { getBroker, mamBrokers } from '../../../../../lib/broker-config';

export function generateStaticParams(){return ['mt4','mt5'].flatMap(platform=>mamBrokers.map(b=>({platform,broker:b.slug})))}

export default async function MamBrokerPage({params}:{params:Promise<{platform:string;broker:string}>}){
  const {platform,broker}=await params;
  const data=getBroker(mamBrokers,broker);
  if(!data)return <main className="p-10"><Link href={`/services/mam-trading/${platform}`}>← Back</Link><h1 className="mt-10 text-3xl font-black">Broker unavailable</h1></main>;
  const label=platform.toUpperCase();
  const minimumDeposit=2000;
  return <main className="min-h-screen bg-[#f7f9f8] text-[#101512]">
    <header className="sticky top-0 z-40 border-b border-[#e4e9e6] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex min-h-[76px] max-w-[1200px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href={`/services/mam-trading/${platform}`} className="inline-flex items-center gap-2 font-black text-[#087f3f]"><ArrowLeft size={15}/> {label} MAM</Link><CustomerMenu/></div></header>
    <section className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1200px] px-5 py-8 sm:px-8 lg:px-10"><div className="flex flex-wrap items-center justify-between gap-3"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">{label} MAM / {data.name.toUpperCase()}</span><div className="flex gap-2"><Link href={`/performance-statistics/mam/${platform}/${data.slug}`} className="inline-flex items-center gap-2 rounded-xl bg-[#087f3f] px-4 py-2.5 text-[11px] font-extrabold text-white"><BarChart3 size={14}/> Performance Statistics</Link><Link href={`/risk-analysis/mam/${platform}/${data.slug}`} className="inline-flex items-center gap-2 rounded-xl border border-[#f0c9cd] bg-[#fff7f7] px-4 py-2.5 text-[11px] font-extrabold text-[#c93642]"><ShieldAlert size={14}/> Risk Analysis</Link></div></div></div></section>
    <section className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1200px] px-5 py-12 sm:px-8 lg:px-10 lg:py-16"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">{label} MAM / {data.name.toUpperCase()}</span><h1 className="mt-3 max-w-4xl text-4xl font-black tracking-[-.045em] sm:text-5xl">Access Arcus Strategy MAM on {data.name}.</h1><p className="mt-5 max-w-3xl text-[15px] leading-7 text-[#68726e]">Use the broker's MAM environment to participate in the Arcus Strategy managed allocation. Your broker account remains yours and Arcus does not request your broker password.</p></div></section>
    <section className="mx-auto max-w-[1050px] px-5 py-10 sm:px-8 lg:px-10 lg:py-14"><div className="space-y-4">
      <article className="rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#edf8f1] text-[12px] font-black text-[#087f3f]">01</span><div className="flex-1"><span className="text-[9px] font-black tracking-[.18em] text-[#087f3f]">INSTRUCTION 1</span><h2 className="mt-2 text-xl font-black">Sign up on {data.name} MAM</h2><p className="mt-2 max-w-2xl text-[13px] leading-6 text-[#68726e]">Create your own {data.name} account through the broker's registration process and complete the required onboarding checks.</p><a href={data.slug==='hantec-markets'?'https://hmarkets.com/':'#'} target={data.slug==='hantec-markets'?'_blank':undefined} rel={data.slug==='hantec-markets'?'noreferrer':undefined} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#087f3f] px-5 py-3 text-[11px] font-extrabold text-white">Register with {data.name} <ExternalLink size={14}/></a>{data.slug!=='hantec-markets'&&<p className="mt-2 text-[10px] text-[#9aa39f]">Affiliate registration link will be enabled for this broker when supplied.</p>}</div></div></article>
      <article className="rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#edf8f1] text-[12px] font-black text-[#087f3f]">02</span><div><span className="text-[9px] font-black tracking-[.18em] text-[#087f3f]">INSTRUCTION 2</span><h2 className="mt-2 text-xl font-black">Verify your account and Deposit</h2><p className="mt-2 text-[13px] leading-6 text-[#68726e]">Complete the broker's identity, account and eligibility verification requirements, then fund the account before proceeding to the Arcus Strategy MAM.</p><div className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#f5f8f6] px-4 py-3 text-[11px] font-extrabold text-[#101512]"><CheckCircle2 size={15} className="text-[#087f3f]"/> Minimum deposit: <span className="text-[#087f3f]">${minimumDeposit.toLocaleString()}</span></div></div></div></article>
      <article className="rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#edf8f1] text-[12px] font-black text-[#087f3f]">03</span><div><span className="text-[9px] font-black tracking-[.18em] text-[#087f3f]">INSTRUCTION 3</span><h2 className="mt-2 text-xl font-black">Search for Arcus Strategy MAM</h2><p className="mt-2 text-[13px] leading-6 text-[#68726e]">Open the broker's MAM environment and search for the official Arcus Strategy MAM profile or identifier.</p></div></div></article>
      <article className="rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#edf8f1] text-[12px] font-black text-[#087f3f]">04</span><div><span className="text-[9px] font-black tracking-[.18em] text-[#087f3f]">INSTRUCTION 4</span><h2 className="mt-2 text-xl font-black">Follow Arcus Strategy MAM</h2><p className="mt-2 text-[13px] leading-6 text-[#68726e]">Select the official Arcus Strategy MAM and complete the broker's own follow, allocation or subscription confirmation.</p></div></div></article>
      <article className="rounded-2xl border border-[#dfe7e2] bg-[#101714] p-6 text-white shadow-sm sm:p-8"><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white/10 text-[12px] font-black text-[#65d995]"><CircleHelp size={17}/></span><div className="flex-1"><span className="text-[9px] font-black tracking-[.18em] text-[#65d995]">NEXT ASSISTANCE</span><h2 className="mt-2 text-xl font-black">Need help?</h2><p className="mt-2 text-[13px] leading-6 text-[#b4beb9]">If you are unsure about any step, contact Arcus customer support before activating the MAM relationship. Never send your broker password to support.</p><Link href="/support" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-[11px] font-extrabold text-[#101714]">ASK SUPPORT</Link></div></div></article>
    </div></section>
    <section className="border-t border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1050px] px-5 py-8 sm:px-8 lg:px-10"><div className="flex items-start gap-3 rounded-2xl bg-[#fff7f7] p-5"><ShieldAlert className="mt-0.5 shrink-0 text-[#c93642]" size={18}/><p className="text-[11px] leading-5 text-[#6f5b5e]">MAM trading involves market and allocation risk. Returns can vary and losses can occur. Broker execution, fees, liquidity and other conditions may affect results. Past performance does not guarantee future results.</p></div></div></section>
  </main>
}
