import Link from 'next/link';
import { ArrowRight, BarChart3, Layers3, WalletCards } from 'lucide-react';
import CustomerMenu from '../../components/CustomerMenu';
const categories = [
  { title: 'Copy Trading', description: 'Broker-isolated performance for MT4, MT5, Deriv Synthetic and cTrader copy-trading environments.', href: '/performance-statistics/copy-trading', icon: BarChart3 },
  { title: 'PAMM', description: 'PAMM performance separated by MT4 and MT5 and then by broker.', href: '/performance-statistics/pamm', icon: WalletCards },
  { title: 'MAM', description: 'MAM performance separated by MT4 and MT5 and then by broker.', href: '/performance-statistics/mam', icon: Layers3 },
];
export default function PerformanceStatisticsPage() { return <main className="min-h-screen bg-[#f7f9f8] text-[#101512]"><header className="sticky top-0 z-40 border-b border-[#e4e9e6] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex min-h-[76px] max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/dashboard" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#087f3f] text-sm font-black text-white">A</span><span><strong className="block text-[15px] tracking-[.16em]">ARCUS</strong><small className="block text-[8px] font-black tracking-[.35em] text-[#087f3f]">STRATEGY</small></span></Link><CustomerMenu /></div></header><section className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-10 lg:py-16"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">PERFORMANCE STATISTICS</span><h1 className="mt-3 text-4xl font-black tracking-[-.045em] sm:text-5xl">Review performance by account environment.</h1><p className="mt-5 max-w-3xl text-[15px] leading-7 text-[#68726e]">Select the service first, then the platform and exact broker/account environment. Every account has its own isolated performance dashboard.</p></div></section><section className="mx-auto max-w-[1200px] px-5 py-10 sm:px-8 lg:px-10 lg:py-14"><div className="grid gap-4 md:grid-cols-3">{categories.map(({title,description,href,icon:Icon})=><Link key={title} href={href} className="group rounded-2xl border border-[#dfe7e2] bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:border-[#add8bd] hover:shadow-xl"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#edf8f1] text-[#087f3f]"><Icon size={20}/></span><h2 className="mt-7 text-xl font-black">{title}</h2><p className="mt-3 text-[13px] leading-6 text-[#68726e]">{description}</p><span className="mt-7 inline-flex items-center gap-2 text-[12px] font-extrabold text-[#087f3f]">Open dashboard <ArrowRight size={15}/></span></Link>)}</div><div className="mt-8 rounded-2xl border border-[#dfe7e2] bg-white p-6"><span className="text-[9px] font-black tracking-[.18em] text-[#087f3f]">DATA SOURCE</span><h2 className="mt-2 text-lg font-black">Myfxbook account widgets</h2><p className="mt-2 text-[12px] leading-6 text-[#68726e]">Each final broker/account page contains a dedicated Myfxbook dashboard container. Configure the verified widget URL for each account in the Arcus backend and it will render without mixing statistics between accounts.</p></div></section></main>; }
