import Link from 'next/link';
import { ArrowRight, BarChart3, ChartCandlestick, CircleDollarSign, Layers3 } from 'lucide-react';
import CustomerMenu from '../../../components/CustomerMenu';

const platforms = [
  { name: 'MT4', description: 'Select MT4 to see the brokers through which Arcus currently offers trade replication.', href: '/services/social-trading/mt4', icon: ChartCandlestick },
  { name: 'MT5', description: 'Select MT5 to see the brokers through which Arcus currently offers trade replication.', href: '/services/social-trading/mt5', icon: BarChart3 },
  { name: 'cTrader', description: 'cTrader availability is presented as a separate trading environment.', href: '/services/social-trading/ctrader', icon: Layers3 },
  { name: 'Synthetic Indices', description: 'Synthetic-index copy trading is presented as its own supported environment.', href: '/services/social-trading/synthetic', icon: CircleDollarSign },
];

export default function SocialTradingPage() {
  return <main className="min-h-screen bg-[#f7f9f8] text-[#101512]">
    <header className="sticky top-0 z-40 border-b border-[#e4e9e6] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex min-h-[76px] max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/dashboard" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#087f3f] text-sm font-black text-white">A</span><span><strong className="block text-[15px] tracking-[.16em]">ARCUS</strong><small className="block text-[8px] font-black tracking-[.35em] text-[#087f3f]">STRATEGY</small></span></Link><CustomerMenu /></div></header>
    <section className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-10 lg:py-16"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">SOCIAL TRADING</span><h1 className="mt-3 max-w-4xl text-4xl font-black tracking-[-.045em] sm:text-5xl">Choose your trading platform first.</h1><p className="mt-5 max-w-3xl text-[15px] leading-7 text-[#68726e]">Arcus trade replication is organised by platform because broker availability, account setup and execution conditions can differ. Select your platform below to see the available broker environments.</p></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-10 sm:px-8 lg:px-10 lg:py-14"><div className="grid gap-4 md:grid-cols-2">{platforms.map(({name,description,href,icon:Icon},i)=><Link key={name} href={href} className="group rounded-2xl border border-[#dfe7e2] bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:border-[#add8bd] hover:shadow-xl"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#edf8f1] text-[#087f3f]"><Icon size={20}/></span><span className="text-[9px] font-black tracking-[.18em] text-[#9aa39f]">PLATFORM 0{i+1}</span></div><h2 className="mt-8 text-2xl font-black">{name}</h2><p className="mt-3 max-w-md text-[13px] leading-6 text-[#68726e]">{description}</p><span className="mt-7 inline-flex items-center gap-2 text-[12px] font-extrabold text-[#087f3f]">View broker availability <ArrowRight size={15}/></span></Link>)}</div></section>
    <section className="border-t border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1440px] px-5 py-10 sm:px-8 lg:px-10"><div className="grid gap-5 md:grid-cols-3"><div><strong className="text-sm">1. Platform</strong><p className="mt-2 text-[11px] leading-5 text-[#68726e]">Choose MT4, MT5 or another supported environment.</p></div><div><strong className="text-sm">2. Broker</strong><p className="mt-2 text-[11px] leading-5 text-[#68726e]">Select a broker where the Arcus strategy is available.</p></div><div><strong className="text-sm">3. Replicate</strong><p className="mt-2 text-[11px] leading-5 text-[#68726e]">Follow the broker-specific onboarding process to replicate qualifying Arcus trades.</p></div></div></div></section>
  </main>;
}
