import Link from 'next/link';
import { ArrowRight, Bot, Check, Cloud, Link2, ShieldCheck, Webhook, Zap } from 'lucide-react';
import { tradingViewPlatforms } from '@/lib/tradingview-strategy';

export default function TradingViewStrategyProductPage() {
  return (
    <main className="min-h-screen bg-[#f7f9f8] text-[#101512]">
      <header className="border-b border-[#e4e9e6] bg-white/95 backdrop-blur-xl">
        <div className="mx-auto flex min-h-[74px] max-w-[1280px] items-center justify-between px-5 sm:px-8 lg:px-10">
          <Link href="/" className="flex items-center gap-3" aria-label="Arcus Strategy home">
            <span className="grid h-10 w-10 place-items-center rounded-xl bg-[#087f3f] text-sm font-black text-white">A</span>
            <span><strong className="block text-[15px] tracking-[.16em]">ARCUS</strong><small className="block text-[8px] font-black tracking-[.35em] text-[#087f3f]">STRATEGY</small></span>
          </Link>
          <Link href="/products" className="text-[12px] font-bold text-[#087f3f]">← Products</Link>
        </div>
      </header>

      <section className="border-b border-[#e4e9e6] bg-white">
        <div className="mx-auto grid max-w-[1280px] gap-12 px-5 py-14 sm:px-8 lg:grid-cols-[1.12fr_.88fr] lg:px-10 lg:py-20">
          <div className="flex flex-col justify-center">
            <div className="flex items-center gap-3 text-[10px] font-black tracking-[.2em] text-[#087f3f]"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#edf8f1]"><Bot size={17}/></span>TRADINGVIEW STRATEGY</div>
            <h1 className="mt-6 max-w-4xl text-4xl font-black tracking-[-.045em] sm:text-5xl lg:text-6xl lg:leading-[1.02]">Turn Trading Signals into Automated Trade Execution.</h1>
            <p className="mt-6 max-w-3xl text-[15px] leading-7 text-[#68726e] sm:text-[16px]">The Arcus Strategy TradingView Strategy is designed for traders who want to automate their trading directly from TradingView using webhook technology. Once a trading signal is generated by our proprietary strategy, webhook alerts can be sent instantly to supported automation platforms, which then execute trades automatically in your connected brokerage or cryptocurrency exchange account.</p>
            <p className="mt-4 max-w-3xl text-[15px] leading-7 text-[#68726e] sm:text-[16px]">This allows you to benefit from disciplined, rules-based trading without manually placing every trade. Simply connect your preferred automation platform, configure your account once, and let your strategy execute according to predefined trading conditions.</p>
            <p className="mt-4 max-w-3xl text-[15px] leading-7 text-[#68726e] sm:text-[16px]">Whether you trade Forex, Cryptocurrencies, Indices, Gold, or other supported markets, Arcus Strategy provides a flexible automation solution that integrates with leading third-party trading platforms.</p>
            <div className="mt-8 flex flex-wrap gap-3">
              <Link href="#platforms" className="inline-flex items-center gap-2 rounded-xl bg-[#087f3f] px-5 py-3.5 text-[12px] font-black text-white transition hover:-translate-y-0.5 hover:bg-[#066b35]">Choose an integration <ArrowRight size={15}/></Link>
              <Link href="/products" className="inline-flex items-center rounded-xl border border-[#dfe7e2] bg-white px-5 py-3.5 text-[12px] font-black">Back to products</Link>
            </div>
          </div>

          <div className="flex items-center justify-center">
            <div className="w-full max-w-[460px] rounded-[28px] border border-[#dfe7e2] bg-[#fbfcfb] p-5 shadow-[0_24px_70px_rgba(16,21,18,.08)]">
              <div className="flex items-center justify-between border-b border-[#e7ece9] pb-4"><div><span className="text-[9px] font-black tracking-[.18em] text-[#9aa39f]">ARCUS AUTOMATION</span><h2 className="mt-1 text-sm font-black">TradingView → Webhook → Execution</h2></div><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#edf8f1] text-[#087f3f]"><Webhook size={16}/></span></div>
              <div className="mt-5 space-y-3">
                {[['01','Strategy signal','TradingView generates a qualifying alert.'],['02','Webhook delivery','The alert is delivered to the configured automation platform.'],['03','Trade execution','The platform processes the alert and executes according to its configuration.']].map(([n,t,d]) => <div key={n} className="flex gap-4 rounded-2xl border border-[#e4e9e6] bg-white p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-[#edf8f1] text-[9px] font-black text-[#087f3f]">{n}</span><div><p className="text-[12px] font-black">{t}</p><p className="mt-1 text-[10px] leading-5 text-[#68726e]">{d}</p></div></div>)}
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-[1280px] px-5 py-14 sm:px-8 lg:px-10 lg:py-18">
        <div className="max-w-3xl"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">FEATURES</span><h2 className="mt-3 text-3xl font-black tracking-[-.035em] sm:text-4xl">Automation built around TradingView alerts.</h2></div>
        <div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {['Automated Buy & Sell Signal Execution','TradingView Webhook Integration','Real-Time Trade Automation','Supports Forex and Cryptocurrency Markets','Connect Your Existing Broker or Exchange','Compatible with Multiple Automation Platforms','Fully Cloud-Based Automation','Easy Setup with Step-by-Step Guidance'].map((feature, i) => <div key={feature} className="rounded-2xl border border-[#dfe7e2] bg-white p-5 shadow-sm"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#edf8f1] text-[#087f3f]"><Check size={15}/></span><p className="mt-5 text-[13px] font-bold leading-6">{feature}</p><span className="mt-5 block text-[9px] font-black tracking-[.18em] text-[#b0b8b4]">0{i+1}</span></div>)}
        </div>
      </section>

      <section className="border-y border-[#e4e9e6] bg-white">
        <div className="mx-auto max-w-[1280px] px-5 py-14 sm:px-8 lg:px-10 lg:py-18">
          <div className="max-w-3xl"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">WHY CHOOSE ARCUS STRATEGY?</span><h2 className="mt-3 text-3xl font-black tracking-[-.035em] sm:text-4xl">Consistent execution without manually monitoring every alert.</h2><p className="mt-5 text-[15px] leading-7 text-[#68726e]">Arcus Strategy combines advanced algorithmic trading logic with TradingView&apos;s powerful alert system to deliver a reliable automation experience. Instead of manually monitoring charts, your configured automation platform receives webhook alerts and executes trades according to your chosen settings, helping you maintain consistent execution and reduce emotional decision-making.</p></div>
          <div className="mt-9 grid gap-4 md:grid-cols-3">
            {[['Webhook',Webhook,'Instant alert delivery into supported workflows.'],['Cloud automation',Cloud,'Automation can operate without keeping a local workstation running.'],['Execution controls',ShieldCheck,'Your connected platform and configuration determine how alerts are processed.']].map(([title, Icon, description]) => <div key={String(title)} className="rounded-2xl border border-[#dfe7e2] bg-[#fbfcfb] p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#edf8f1] text-[#087f3f]">{typeof Icon === 'function' ? <Icon size={16}/> : null}</span><h3 className="mt-4 text-sm font-black">{String(title)}</h3><p className="mt-2 text-[12px] leading-6 text-[#68726e]">{String(description)}</p></div>)}
          </div>
          <div className="mt-8 rounded-2xl border border-[#ead9dc] bg-[#fff8f8] p-6"><div className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#fff1f2] text-[#c93642]"><ShieldCheck size={18}/></span><div><h3 className="text-sm font-black">Important risk notice</h3><p className="mt-2 text-[13px] leading-6 text-[#68726e]">Automated trading involves risk. Market conditions, execution quality, and your selected platform configuration may affect trading outcomes. Users are responsible for reviewing and testing their automation settings before trading with live capital.</p></div></div></div>
        </div>
      </section>

      <section id="platforms" className="mx-auto max-w-[1280px] px-5 py-14 sm:px-8 lg:px-10 lg:py-18">
        <div className="max-w-3xl"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">STRATEGY AVAILABLE ON</span><h2 className="mt-3 text-3xl font-black tracking-[-.035em] sm:text-4xl">Choose your automation platform.</h2><p className="mt-4 text-[14px] leading-7 text-[#68726e]">Each integration opens its own Arcus Strategy onboarding page. You will not be sent directly to a third-party platform before reviewing the setup and subscription flow.</p></div>
        <div className="mt-9 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {tradingViewPlatforms.map((platform, i) => <Link key={platform.slug} href={`/products/tradingview-strategy/${platform.slug}`} className="group rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-[#add8bd] hover:shadow-lg"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf8f1] text-[#087f3f]"><Zap size={17}/></span><span className="text-[9px] font-black tracking-[.18em] text-[#9aa39f]">0{i+1}</span></div><h3 className="mt-6 text-lg font-black">{platform.name}</h3><p className="mt-2 text-[12px] leading-6 text-[#68726e]">{platform.description}</p><span className="mt-5 inline-flex items-center gap-1 text-[10px] font-black tracking-[.12em] text-[#087f3f]">VIEW SETUP <ArrowRight size={14} className="transition group-hover:translate-x-1"/></span></Link>)}
        </div>
      </section>

      <section className="bg-[#101512] text-white"><div className="mx-auto max-w-[1280px] px-5 py-14 sm:px-8 lg:px-10 lg:py-16"><div className="flex flex-col gap-7 lg:flex-row lg:items-center lg:justify-between"><div><span className="text-[10px] font-black tracking-[.2em] text-[#5fc48c]">ARCUS STRATEGY AUTOMATION</span><h2 className="mt-3 text-3xl font-black tracking-[-.035em]">Select an integration and begin your guided setup.</h2><p className="mt-3 max-w-2xl text-[13px] leading-6 text-[#b7c0bb]">Platform Integration Page → Arcus Strategy Subscription Page → Payment Confirmation → Webhook/API Setup Wizard → Platform Connection Guide → Automation Activated.</p></div><Link href="#platforms" className="inline-flex w-fit items-center gap-2 rounded-xl bg-[#087f3f] px-6 py-4 text-[12px] font-black text-white transition hover:bg-[#0a9650]">View integrations <ArrowRight size={15}/></Link></div></div></section>
    </main>
  );
}
