import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, CreditCard, ExternalLink, ShieldCheck, Webhook } from 'lucide-react';
import { getTradingViewPlatform, tradingViewPlatforms } from '@/lib/tradingview-strategy';

export function generateStaticParams() { return tradingViewPlatforms.map((platform) => ({ platform: platform.slug })); }

export default async function TradingViewIntegrationPage({ params }: { params: Promise<{ platform: string }> }) {
  const { platform: slug } = await params;
  const platform = getTradingViewPlatform(slug);
  if (!platform) return <main className="grid min-h-screen place-items-center bg-[#f7f9f8] p-6 text-[#101512]"><div className="text-center"><h1 className="text-3xl font-black">Integration not found</h1><Link href="/products/tradingview-strategy" className="mt-5 inline-flex rounded-xl bg-[#087f3f] px-5 py-3 text-[12px] font-black text-white">Back to TradingView Strategy</Link></div></main>;

  return <main className="min-h-screen bg-[#f7f9f8] text-[#101512]">
    <header className="border-b border-[#e4e9e6] bg-white/95 backdrop-blur-xl"><div className="mx-auto flex min-h-[74px] max-w-[1280px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/products/tradingview-strategy" className="inline-flex items-center gap-2 text-[12px] font-bold text-[#087f3f]"><ArrowLeft size={15}/> TradingView Strategy</Link><span className="text-[9px] font-black tracking-[.18em] text-[#9aa39f]">PLATFORM INTEGRATION</span></div></header>
    <section className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1100px] px-5 py-14 sm:px-8 lg:px-10 lg:py-20"><div className="max-w-4xl"><div className="flex items-center gap-3 text-[10px] font-black tracking-[.2em] text-[#087f3f]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf8f1]">{platform.name.slice(0,1)}</span>ARCUS STRATEGY × {platform.name.toUpperCase()}</div><h1 className="mt-6 text-4xl font-black tracking-[-.045em] sm:text-5xl lg:text-6xl">Automate Your Trading with {platform.name}</h1><p className="mt-6 max-w-3xl text-[15px] leading-7 text-[#68726e] sm:text-[16px]">{platform.description}</p><div className="mt-8 flex flex-wrap gap-3"><Link href={`/products/tradingview-strategy/subscribe?platform=${platform.slug}`} className="inline-flex items-center gap-2 rounded-xl bg-[#087f3f] px-5 py-3.5 text-[12px] font-black text-white transition hover:bg-[#066b35]">Subscribe &amp; start setup <ArrowRight size={15}/></Link><Link href="#setup" className="inline-flex items-center rounded-xl border border-[#dfe7e2] px-5 py-3.5 text-[12px] font-black">View setup</Link></div></div></div></section>
    <section className="mx-auto max-w-[1100px] px-5 py-14 sm:px-8 lg:px-10 lg:py-18"><div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf8f1] text-[#087f3f]"><Check size={17}/></div><h2 className="mt-5 text-xl font-black">Features</h2><ul className="mt-5 space-y-3">{platform.features.map((feature) => <li key={feature} className="flex gap-3 text-[13px] leading-6 text-[#68726e]"><Check size={15} className="mt-1 shrink-0 text-[#087f3f]"/>{feature}</li>)}</ul></div><div id="setup" className="rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf8f1] text-[#087f3f]"><Webhook size={17}/></div><h2 className="mt-5 text-xl font-black">How It Works</h2><ol className="mt-5 space-y-4">{platform.setup.map((step, index) => <li key={step} className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-[#edf8f1] text-[10px] font-black text-[#087f3f]">{index+1}</span><span className="text-[13px] leading-6 text-[#68726e]">{step}</span></li>)}</ol></div></div><div className="mt-8 grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-[#dfe7e2] bg-white p-6"><h2 className="text-xl font-black">Requirements</h2><div className="mt-5 space-y-3">{['Active Arcus Strategy subscription','TradingView account with the required alert capability','An active account with the selected automation platform','Supported broker or exchange connection where applicable','A tested webhook/API configuration before live deployment'].map((item) => <div key={item} className="flex gap-3 rounded-xl bg-[#f3f7f4] p-3 text-[12px] leading-5 text-[#68726e]"><Check size={15} className="mt-0.5 shrink-0 text-[#087f3f]"/>{item}</div>)}</div></div><div className="rounded-2xl border border-[#dfe7e2] bg-white p-6"><h2 className="text-xl font-black">Arcus onboarding flow</h2><div className="mt-5 space-y-3">{['Platform integration page','Arcus Strategy subscription','Payment confirmation','Webhook/API setup wizard','Platform connection guide','Automation activation'].map((item, index) => <div key={item} className="flex items-center gap-3 text-[12px] font-bold"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#edf8f1] text-[10px] font-black text-[#087f3f]">{index+1}</span>{item}</div>)}</div></div></div></section>
    <section className="border-y border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1100px] px-5 py-14 sm:px-8 lg:px-10 lg:py-18"><div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-[#dfe7e2] bg-[#fbfcfb] p-5"><CreditCard size={17} className="text-[#087f3f]"/><h3 className="mt-4 text-sm font-black">1. Arcus subscription</h3><p className="mt-2 text-[12px] leading-6 text-[#68726e]">Complete your Arcus Strategy subscription before platform connection.</p></div><div className="rounded-2xl border border-[#dfe7e2] bg-[#fbfcfb] p-5"><Webhook size={17} className="text-[#087f3f]"/><h3 className="mt-4 text-sm font-black">2. Guided configuration</h3><p className="mt-2 text-[12px] leading-6 text-[#68726e]">After payment confirmation, follow the webhook/API setup wizard.</p></div><div className="rounded-2xl border border-[#dfe7e2] bg-[#fbfcfb] p-5"><ExternalLink size={17} className="text-[#087f3f]"/><h3 className="mt-4 text-sm font-black">3. Platform connection</h3><p className="mt-2 text-[12px] leading-6 text-[#68726e]">Only after the Arcus onboarding steps do you proceed to the platform connection instructions.</p></div></div><div className="mt-8 flex flex-wrap gap-3"><Link href={`/products/tradingview-strategy/subscribe?platform=${platform.slug}`} className="inline-flex items-center gap-2 rounded-xl bg-[#087f3f] px-5 py-3.5 text-[12px] font-black text-white">Subscribe to Arcus Strategy <ArrowRight size={15}/></Link><Link href="/support" className="inline-flex items-center gap-2 rounded-xl border border-[#dfe7e2] px-5 py-3.5 text-[12px] font-black">Need assistance? <ArrowRight size={15}/></Link></div></div></section>
    <section className="mx-auto max-w-[1100px] px-5 py-14 sm:px-8 lg:px-10 lg:py-18"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">FAQ</span><h2 className="mt-3 text-3xl font-black tracking-[-.035em]">Frequently asked questions.</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{[['Do I connect my account directly to Arcus Strategy?','The TradingView Strategy uses the selected automation platform as the execution layer. Follow the Arcus onboarding flow before connecting any broker or exchange.'],['Will the integration guarantee profitable trades?','No. Automated execution does not guarantee profitability. Market conditions, execution quality and configuration can materially affect outcomes.'],['Can I test the automation first?','You should review and test your TradingView alerts, webhook/API configuration and platform settings before using live capital.'],['Where do I get platform-specific instructions?','This Arcus Strategy integration page is the starting point. Subscription and the setup wizard lead into the platform-specific connection guide.']].map(([question, answer]) => <div key={question} className="rounded-2xl border border-[#dfe7e2] bg-white p-5"><h3 className="text-sm font-black">{question}</h3><p className="mt-2 text-[12px] leading-6 text-[#68726e]">{answer}</p></div>)}</div></section>
    <section className="bg-[#101512] text-white"><div className="mx-auto max-w-[1100px] px-5 py-12 sm:px-8 lg:px-10"><div className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#1b3025] text-[#5fc48c]"><ShieldCheck size={18}/></span><div><h2 className="text-sm font-black">Risk disclaimer</h2><p className="mt-2 text-[12px] leading-6 text-[#b7c0bb]">Automated trading involves risk. Market conditions, execution quality, third-party platform availability, and your configuration may affect results. Review and test your automation settings before using live capital.</p></div></div></div></section>
  </main>;
}
