import Link from 'next/link';
import { ArrowLeft, ArrowRight, CheckCircle2, ShieldCheck, Webhook } from 'lucide-react';
import { getTradingViewPlatform, tradingViewPlatforms } from '@/lib/tradingview-strategy';

export default async function TradingViewStrategySetupPage({ searchParams }: { searchParams: Promise<{ platform?: string }> }) {
  const { platform: slug = 'zignaly' } = await searchParams;
  const platform = getTradingViewPlatform(slug) ?? tradingViewPlatforms[0];

  return (
    <main className="min-h-screen bg-[#f7f9f8] text-[#101512]">
      <header className="border-b border-[#e4e9e6] bg-white"><div className="mx-auto flex min-h-[74px] max-w-[1100px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href={`/products/tradingview-strategy/${platform.slug}`} className="inline-flex items-center gap-2 text-[12px] font-bold text-[#087f3f]"><ArrowLeft size={15}/> {platform.name} integration</Link><span className="text-[9px] font-black tracking-[.18em] text-[#9aa39f]">SETUP WIZARD</span></div></header>
      <section className="mx-auto max-w-[1000px] px-5 py-14 sm:px-8 lg:px-10 lg:py-20"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">STEP 2 OF 3</span><h1 className="mt-3 text-4xl font-black tracking-[-.045em] sm:text-5xl">Configure your {platform.name} automation.</h1><p className="mt-5 max-w-3xl text-[14px] leading-7 text-[#68726e]">After subscription and payment confirmation, the application will guide you through the webhook/API setup and platform connection. This wizard is the application hand-off point; live credentials and secrets should only be entered into the secure connection workflow when it is enabled.</p>
        <div className="mt-9 grid gap-4 md:grid-cols-3">{['Payment confirmed','Webhook/API setup','Platform connection'].map((step, index) => <div key={step} className={`rounded-2xl border p-5 ${index === 0 ? 'border-[#add8bd] bg-[#edf8f1]' : 'border-[#dfe7e2] bg-white'}`}><span className="text-[9px] font-black tracking-[.18em] text-[#087f3f]">0{index + 1}</span><h2 className="mt-3 text-sm font-black">{step}</h2><p className="mt-2 text-[11px] leading-5 text-[#68726e]">{index === 0 ? 'Ready for the billing provider to confirm the subscription.' : 'Prepared for the platform-specific configuration guide.'}</p></div>)}</div>
        <div className="mt-8 rounded-3xl border border-[#dfe7e2] bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#edf8f1] text-[#087f3f]"><Webhook size={17}/></span><div><h2 className="text-xl font-black">{platform.name} connection guide</h2><p className="mt-2 text-[12px] leading-6 text-[#68726e]">The platform-specific instructions are prepared below. When the production connection layer is enabled, this step can host the generated webhook, API configuration and secure connection controls.</p><ol className="mt-6 space-y-4">{platform.setup.map((item, index) => <li key={item} className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-[#f3f7f4] text-[10px] font-black text-[#087f3f]">{index + 1}</span><span className="text-[12px] leading-6 text-[#68726e]">{item}</span></li>)}</ol></div></div><div className="mt-7 rounded-2xl bg-[#f3f7f4] p-5"><div className="flex gap-3"><CheckCircle2 size={17} className="mt-0.5 shrink-0 text-[#087f3f]"/><div><h3 className="text-[12px] font-black">Production activation</h3><p className="mt-1 text-[11px] leading-5 text-[#68726e]">Once payment, webhook configuration and platform connection are verified, the final automation activation can be completed through the application.</p></div></div></div></div>
        <div className="mt-8 flex flex-wrap gap-3"><Link href={`/products/tradingview-strategy/${platform.slug}`} className="inline-flex items-center gap-2 rounded-xl border border-[#dfe7e2] bg-white px-5 py-3.5 text-[12px] font-black"><ArrowLeft size={15}/> Back</Link><Link href="/support" className="inline-flex items-center gap-2 rounded-xl bg-[#087f3f] px-5 py-3.5 text-[12px] font-black text-white">Contact support <ArrowRight size={15}/></Link></div>
        <div className="mt-8 rounded-2xl border border-[#ead9dc] bg-[#fff8f8] p-5"><div className="flex gap-3"><ShieldCheck size={17} className="mt-0.5 shrink-0 text-[#c93642]"/><p className="text-[11px] leading-6 text-[#68726e]">Do not share passwords, private keys, API secrets or other sensitive credentials in ordinary forms or support messages. Automated trading can result in losses.</p></div></div>
      </section>
    </main>
  );
}
