import Link from 'next/link';
import { ArrowRight, BarChart3, CircleAlert, LayoutDashboard, ShieldCheck, Sparkles } from 'lucide-react';
import CustomerMenu from '../../components/CustomerMenu';

const quickActions = [
  { title: 'Services', label: 'SERVICE HUB', description: 'Explore the trading and execution services currently available to authenticated customers.', href: '/services', icon: Sparkles, accent: 'green' },
  { title: 'Performance Statistics', label: 'PERFORMANCE', description: 'Review performance information for the specific broker and trading environment you select.', href: '/performance-statistics', icon: BarChart3, accent: 'green' },
  { title: 'Risk Analysis', label: 'RISK INTELLIGENCE', description: 'Understand drawdown, exposure, volatility and other risk characteristics before proceeding.', href: '/risk-analysis', icon: CircleAlert, accent: 'red' },
];

export default function DashboardPage() {
  return (
    <main className="min-h-screen bg-[#f7f9f8] text-[#101512]">
      <header className="sticky top-0 z-40 border-b border-[#e4e9e6] bg-white/95 backdrop-blur-xl">
        <div className="mx-auto flex min-h-[76px] max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-10">
          <Link href="/dashboard" className="flex items-center gap-3" aria-label="Arcus Strategy Home">
            <span className="grid h-10 w-10 place-items-center rounded-xl bg-[#087f3f] text-sm font-black text-white shadow-sm">A</span>
            <span><strong className="block text-[15px] tracking-[.16em]">ARCUS</strong><small className="block text-[8px] font-black tracking-[.35em] text-[#087f3f]">STRATEGY</small></span>
          </Link>
          <div className="flex items-center gap-3"><span className="hidden rounded-full border border-[#dbe7df] bg-[#f4faf6] px-3 py-1.5 text-[10px] font-black tracking-wider text-[#087f3f] sm:inline-flex">AUTHENTICATED</span><CustomerMenu /></div>
        </div>
      </header>

      <section className="border-b border-[#e4e9e6] bg-white">
        <div className="mx-auto grid max-w-[1440px] gap-12 px-5 py-12 sm:px-8 lg:grid-cols-[1.15fr_.85fr] lg:px-10 lg:py-16">
          <div><div className="mb-4 flex items-center gap-2 text-[10px] font-black uppercase tracking-[.2em] text-[#087f3f]"><LayoutDashboard size={14} /> Customer Home</div><h1 className="max-w-3xl text-4xl font-black tracking-[-.045em] sm:text-5xl lg:text-6xl">Welcome to your <span className="text-[#087f3f]">Arcus Strategy</span> workspace.</h1><p className="mt-5 max-w-2xl text-[15px] leading-7 text-[#68726e]">Your authenticated home is the starting point for exploring Arcus services. Use the menu in the top-left area of the application to move between the service hub, private trading areas and customer support without keeping navigation tabs permanently visible.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/services" className="inline-flex items-center gap-2 rounded-lg bg-[#087f3f] px-5 py-3 text-[13px] font-extrabold text-white shadow-lg shadow-[#087f3f]/15 hover:bg-[#066b35]">Explore Services <ArrowRight size={16} /></Link><Link href="/performance-statistics" className="inline-flex items-center gap-2 rounded-lg border border-[#d7e0da] bg-white px-5 py-3 text-[13px] font-extrabold text-[#26302b] hover:border-[#087f3f] hover:text-[#087f3f]">View Performance</Link></div></div>
          <div className="rounded-2xl border border-[#dfe7e2] bg-[#101714] p-6 text-white shadow-[0_25px_60px_rgba(16,40,27,.13)]"><div className="flex items-center justify-between"><div><span className="text-[9px] font-black tracking-[.2em] text-[#65d995]">ARCUS CONTROL CENTRE</span><h2 className="mt-2 text-lg font-extrabold">Account overview</h2></div><span className="rounded-full border border-[#65d995]/25 bg-[#65d995]/10 px-3 py-1.5 text-[9px] font-black tracking-wider text-[#65d995]">ACTIVE</span></div><div className="my-6 h-px bg-white/10" /><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-white/10 bg-white/[.035] p-4"><span className="text-[9px] font-bold tracking-wider text-[#8d9993]">CAPITAL</span><strong className="mt-2 block text-sm">Your capital remains with your selected broker.</strong></div><div className="rounded-xl border border-white/10 bg-white/[.035] p-4"><span className="text-[9px] font-bold tracking-wider text-[#8d9993]">REPLICATION</span><strong className="mt-2 block text-sm">Qualifying Arcus trades can be replicated.</strong></div><div className="rounded-xl border border-white/10 bg-white/[.035] p-4"><span className="text-[9px] font-bold tracking-wider text-[#8d9993]">PERFORMANCE</span><strong className="mt-2 block text-sm">Statistics are organised by trading environment.</strong></div><div className="rounded-xl border border-white/10 bg-white/[.035] p-4"><span className="text-[9px] font-bold tracking-wider text-[#8d9993]">RISK</span><strong className="mt-2 block text-sm">Review risk before choosing a service.</strong></div></div></div>
        </div>
      </section>

      <section className="mx-auto max-w-[1440px] px-5 py-10 sm:px-8 lg:px-10 lg:py-14"><div className="mb-6"><span className="text-[10px] font-black tracking-[.2em] text-[#087f3f]">CUSTOMER TOOLS</span><h2 className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">Your core Arcus workspace.</h2><p className="mt-2 max-w-2xl text-[13px] leading-6 text-[#68726e]">Select a destination below, or open the top-left menu whenever you need to move to another part of your account.</p></div><div className="grid gap-4 md:grid-cols-3">{quickActions.map(({ title, label, description, href, icon: Icon, accent }) => <Link key={title} href={href} className="group rounded-2xl border border-[#dfe7e2] bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-[#b9ddc7] hover:shadow-xl"><div className={`grid h-11 w-11 place-items-center rounded-xl ${accent === 'red' ? 'bg-[#fff0f1] text-[#d52f3f]' : 'bg-[#edf8f1] text-[#087f3f]'}`}><Icon size={19} /></div><span className="mt-7 block text-[10px] font-black tracking-[.16em] text-[#68726e]">{label}</span><h3 className="mt-2 text-lg font-extrabold">{title}</h3><p className="mt-2 text-[13px] leading-6 text-[#68726e]">{description}</p><span className="mt-5 inline-flex items-center gap-1 text-[12px] font-extrabold text-[#087f3f]">Open <ArrowRight size={14} /></span></Link>)}</div></section>

      <section className="border-y border-[#e4e9e6] bg-white"><div className="mx-auto max-w-[1440px] px-5 py-10 sm:px-8 lg:px-10"><div className="grid gap-5 md:grid-cols-3"><div className="rounded-xl border border-[#e3e9e5] p-5"><ShieldCheck className="text-[#087f3f]" size={19} /><h3 className="mt-4 text-sm font-extrabold">Broker-controlled capital</h3><p className="mt-2 text-[11px] leading-5 text-[#68726e]">Arcus does not take custody of customer trading capital through the copy-trading workflow.</p></div><div className="rounded-xl border border-[#e3e9e5] p-5"><BarChart3 className="text-[#087f3f]" size={19} /><h3 className="mt-4 text-sm font-extrabold">Broker-specific performance</h3><p className="mt-2 text-[11px] leading-5 text-[#68726e]">Performance information is organised around the broker and platform you choose.</p></div><div className="rounded-xl border border-[#e3e9e5] p-5"><CircleAlert className="text-[#c93642]" size={19} /><h3 className="mt-4 text-sm font-extrabold">Risk comes first</h3><p className="mt-2 text-[11px] leading-5 text-[#68726e]">Trading involves substantial risk. Review the applicable risk information before proceeding.</p></div></div></div></section>

      <footer className="bg-white"><div className="mx-auto flex max-w-[1440px] flex-col gap-4 px-5 py-8 sm:px-8 md:flex-row md:items-center md:justify-between lg:px-10"><div><strong className="text-[12px] tracking-[.15em]">ARCUS STRATEGY</strong><p className="mt-1 text-[10px] text-[#7b8580]">Authenticated customer workspace.</p></div><Link href="/" className="text-[11px] font-bold text-[#68726e] hover:text-[#087f3f]">Sign out</Link></div></footer>
    </main>
  );
}
