'use client';

import Link from 'next/link';
import { FileText, GraduationCap, HelpCircle, Megaphone, Image, CalendarDays, BarChart3, Plus, ArrowRight, Clock3, CheckCircle2, Eye, Pencil, Archive, Video, FileStack } from 'lucide-react';

const stats = [['Published Articles','XX'],['Drafts','XX'],['Scheduled','XX'],['Courses','XX']];
const recent = [['Introduction to Copy Trading','Education','Draft','Updated recently'],['Understanding Risk Before You Invest','Risk Management','Scheduled','Scheduled'],['Arcus Strategy Platform Guide','Platform','Published','Published']];
const calendar = [['Mon','Introduction to Copy Trading','Draft'],['Tue','Risk Management Guide','Scheduled'],['Wed','Platform Update','Published'],['Thu','Managing Your Trading Account','Draft'],['Fri','Monthly Market Education','Planned']];

export default function CopywriterDashboard(){
 return <main className="min-h-screen bg-[#f5f7f6] text-[#101512]">
  <header className="border-b border-[#dfe6e2] bg-white px-5 py-6 sm:px-8 xl:px-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[8px] font-black uppercase tracking-[.22em] text-[#087f3f]">Arcus Content · CMS</p><h1 className="mt-1 text-2xl font-black tracking-[-.035em]">Copywriter Dashboard</h1><p className="mt-1 max-w-2xl text-[10px] text-[#707a75]">Create, organize, review, schedule and publish customer-facing Arcus content from one controlled workspace.</p></div><div className="flex gap-2"><Link href="/admin/content/blog/new" className="inline-flex items-center gap-2 rounded-xl bg-[#087f3f] px-4 py-2.5 text-[9px] font-black text-white"><Plus size={13}/>Create article</Link><Link href="/admin/content/education/courses/new" className="inline-flex items-center gap-2 rounded-xl border border-[#d3ddd7] bg-white px-4 py-2.5 text-[9px] font-black"><Plus size={13}/>Create course</Link></div></div></header>
  <section className="grid gap-3 px-5 py-5 sm:grid-cols-2 xl:grid-cols-4 xl:px-10">{stats.map(([a,b])=><div key={a} className="rounded-2xl border border-[#dfe6e2] bg-white p-5"><span className="text-[8px] font-black uppercase tracking-[.12em] text-[#7b8580]">{a}</span><strong className="mt-2 block text-2xl font-black">{b}</strong><span className="mt-1 block text-[8px] text-[#7b8580]">Content workspace</span></div>)}</section>
  <section className="grid gap-5 px-5 py-4 sm:px-8 xl:grid-cols-[1.45fr_.8fr] xl:px-10"><div className="rounded-2xl border border-[#dfe6e2] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-[8px] font-black uppercase tracking-[.18em] text-[#087f3f]">Editorial queue</p><h2 className="mt-1 text-base font-black">Recent content</h2></div><Link href="/admin/content/blog" className="text-[9px] font-black text-[#087f3f]">View all <ArrowRight className="ml-1 inline" size={12}/></Link></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b border-[#edf0ee]"><th className="px-2 py-3 text-[8px] uppercase text-[#7d8782]">Title</th><th className="px-2 py-3 text-[8px] uppercase text-[#7d8782]">Category</th><th className="px-2 py-3 text-[8px] uppercase text-[#7d8782]">Status</th><th className="px-2 py-3 text-[8px] uppercase text-[#7d8782]">Updated</th><th/></tr></thead><tbody>{recent.map(r=><tr key={r[0]} className="border-b border-[#f0f2f1]"><td className="px-2 py-3 text-[9px] font-bold">{r[0]}</td><td className="px-2 py-3 text-[8px] text-[#66716b]">{r[1]}</td><td className="px-2 py-3"><span className="rounded-full bg-[#f2f6f3] px-2 py-1 text-[7px] font-black">{r[2]}</span></td><td className="px-2 py-3 text-[8px] text-[#7b8580]">{r[3]}</td><td className="px-2 py-3"><Link href="/admin/content/blog" className="text-[#087f3f]"><Pencil size={13}/></Link></td></tr>)}</tbody></table></div></div><div className="rounded-2xl border border-[#dfe6e2] bg-white p-6"><div className="flex items-center gap-2"><CalendarDays size={16} className="text-[#087f3f]"/><h2 className="text-base font-black">Content calendar</h2></div><div className="mt-4 space-y-2">{calendar.map(r=><div key={r[0]} className="flex items-center justify-between rounded-xl bg-[#f7f9f8] p-3"><span className="w-9 text-[8px] font-black uppercase text-[#7b8580]">{r[0]}</span><span className="flex-1 px-2 text-[8px] font-bold">{r[1]}</span><span className="text-[7px] font-black text-[#087f3f]">{r[2]}</span></div>)}</div><Link href="/admin/content/calendar" className="mt-4 inline-block text-[8px] font-black text-[#087f3f]">Open calendar →</Link></div></section>
  <section className="grid gap-5 px-5 py-4 sm:px-8 xl:grid-cols-3 xl:px-10"><ContentCard icon={<FileText size={16}/>} title="Blog" text="Create, edit, draft, preview, schedule, publish, unpublish and archive articles." links={[['All Articles','/admin/content/blog'],['Drafts','/admin/content/blog?status=draft'],['Scheduled','/admin/content/blog?status=scheduled'],['Published','/admin/content/blog?status=published'],['Categories','/admin/content/blog?view=categories']]}/><ContentCard icon={<GraduationCap size={16}/>} title="Education" text="Manage courses, lessons and learning assets with controlled course ordering." links={[['Courses','/admin/content/education/courses'],['Lessons','/admin/content/education/lessons'],['Videos','/admin/content/education/videos'],['Documents','/admin/content/education/documents']]}/><ContentCard icon={<HelpCircle size={16}/>} title="FAQ & Announcements" text="Maintain customer FAQs and publish platform, service and maintenance announcements." links={[['FAQ','/admin/content/faq'],['Announcements','/admin/content/announcements'],['Media Library','/admin/content/media'],['Analytics','/admin/content/analytics']]}/></section>
  <section className="grid gap-5 px-5 py-4 pb-10 sm:px-8 xl:grid-cols-[1.1fr_.9fr] xl:px-10"><div className="rounded-2xl border border-[#dfe6e2] bg-white p-6"><div className="flex items-center gap-2"><FileStack size={16} className="text-[#087f3f]"/><h2 className="text-base font-black">Education structure</h2></div><div className="mt-4 space-y-3">{[['Introduction to Copy Trading',['Article','Video','Document']],['Understanding Risk',['Article','Video','Document']],['Managing Your Trading Account',['Article','Video','Document']]].map(([course,items])=><div key={course as string} className="rounded-xl border border-[#e7ebe9] p-4"><strong className="text-[10px]">{course as string}</strong><div className="mt-2 flex flex-wrap gap-2">{(items as string[]).map(i=><span key={i} className="inline-flex items-center gap-1 rounded-lg bg-[#f6f8f7] px-2.5 py-1.5 text-[8px] font-bold">{i==='Article'?<FileText size={11}/>:i==='Video'?<Video size={11}/>:<FileStack size={11}/>} {i}</span>)}</div></div>)}</div></div><div className="rounded-2xl border border-[#dfe6e2] bg-white p-6"><p className="text-[8px] font-black uppercase tracking-[.18em] text-[#087f3f]">Publishing controls</p><h2 className="mt-1 text-base font-black">Editorial workflow</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{[[Clock3,'Draft'],[Eye,'Preview'],[CalendarDays,'Schedule'],[CheckCircle2,'Publish'],[Archive,'Unpublish / Archive'],[BarChart3,'Analytics']].map(([Icon,label])=><div key={label as string} className="flex items-center gap-2 rounded-xl bg-[#f7f9f8] p-3 text-[8px] font-black"><Icon size={14} className="text-[#087f3f]"/>{label as string}</div>)}</div><div className="mt-5 rounded-xl border border-[#eadede] bg-[#fffafa] p-4"><strong className="text-[9px]">Content-only security boundary</strong><p className="mt-1 text-[8px] leading-4 text-[#7b716f]">This role does not include customer accounts, payments, trading credentials, financial administration or trading operations.</p></div></div></section>
 </main>
}
function ContentCard({icon,title,text,links}:{icon:React.ReactNode;title:string;text:string;links:string[][]}){return <div className="rounded-2xl border border-[#dfe6e2] bg-white p-6"><div className="flex items-center gap-2 text-[#087f3f]">{icon}<h2 className="text-base font-black text-[#101512]">{title}</h2></div><p className="mt-2 text-[9px] leading-4 text-[#707a75]">{text}</p><div className="mt-4 space-y-1.5">{links.map(([label,href])=><Link key={label} href={href} className="flex items-center justify-between rounded-lg px-2 py-2 text-[9px] font-bold hover:bg-[#f5f7f6]">{label}<ArrowRight size={12} className="text-[#087f3f]"/></Link>)}</div></div>}
